/**
 * Genera content/municipalities/roses/syllabus.json a partir del temari
 * canònic de la convocatòria de 2026 (roses-bases-2026-interins).
 *
 * La numeració canònica és la de 2026. `number2025` registra l'equivalència
 * amb la convocatòria de places en propietat de 2025, on els temes de règim
 * disciplinari i de pressupostos apareixen en ordre invers.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { Syllabus, type SyllabusTopic, type BlockId } from '../content/schemas/index.ts'

type Row = [
  number, // núm. 2026
  string, // títol ca
  string, // títol es
  string, // abast ca
  string, // abast es
  string[], // fonts principals
]

const ROWS: Row[] = [
  [1, 'La Constitució de 1978. Principis generals',
   'La Constitución de 1978. Principios generales',
   'Estructura de la Constitució, valors superiors, principis constitucionals, model territorial i reforma constitucional.',
   'Estructura de la Constitución, valores superiores, principios constitucionales, modelo territorial y reforma constitucional.',
   ['ce-1978']],
  [2, 'Els drets fonamentals a la Constitució de 1978',
   'Los derechos fundamentales en la Constitución de 1978',
   'Títol I: drets i deures, garanties, suspensió de drets i el paper del Defensor del Poble i del Tribunal Constitucional.',
   'Título I: derechos y deberes, garantías, suspensión de derechos y el papel del Defensor del Pueblo y del Tribunal Constitucional.',
   ['ce-1978']],
  [3, 'L’Estatut d’Autonomia de Catalunya de 2006',
   'El Estatuto de Autonomía de Cataluña de 2006',
   'Drets i deures de l’àmbit civil i social, drets en l’àmbit polític i de l’Administració, drets i deures lingüístics i govern local.',
   'Derechos y deberes del ámbito civil y social, derechos en el ámbito político y de la Administración, derechos y deberes lingüísticos y gobierno local.',
   ['lo-6-2006-eac']],
  [4, 'La Generalitat de Catalunya, el Parlament i el Consell Executiu',
   'La Generalitat de Cataluña, el Parlamento y el Consejo Ejecutivo',
   'Organització institucional de la Generalitat i competències en matèria de seguretat pública.',
   'Organización institucional de la Generalitat y competencias en materia de seguridad pública.',
   ['lo-6-2006-eac', 'llei-4-2003-seguretat-publica']],
  [5, 'El municipi: concepte, elements, potestats i competències',
   'El municipio: concepto, elementos, potestades y competencias',
   'Territori, població i organització; potestats administratives i competències municipals pròpies i delegades.',
   'Territorio, población y organización; potestades administrativas y competencias municipales propias y delegadas.',
   ['llei-7-1985-lrbrl']],
  [6, 'Les ordenances i els bans',
   'Las ordenanzas y los bandos',
   'Concepte, procediment d’aprovació, destinataris, publicació i control del compliment.',
   'Concepto, procedimiento de aprobación, destinatarios, publicación y control del cumplimiento.',
   ['llei-7-1985-lrbrl', 'roses-ordenances-index']],
  [7, 'Els òrgans jurisdiccionals: poder judicial i Tribunal Constitucional',
   'Los órganos jurisdiccionales: poder judicial y Tribunal Constitucional',
   'Estructura del poder judicial, principis, CGPJ i funcions del Tribunal Constitucional.',
   'Estructura del poder judicial, principios, CGPJ y funciones del Tribunal Constitucional.',
   ['ce-1978']],
  [8, 'Drets i deures dels funcionaris públics. Codi de conducta',
   'Derechos y deberes de los funcionarios públicos. Código de conducta',
   'Drets individuals i col·lectius, deures, principis ètics i principis de conducta de l’EBEP.',
   'Derechos individuales y colectivos, deberes, principios éticos y principios de conducta del EBEP.',
   ['rdleg-5-2015-trebep']],
  [9, 'Règim d’incompatibilitats del personal al servei de les administracions públiques',
   'Régimen de incompatibilidades del personal al servicio de las administraciones públicas',
   'Principi general, activitats públiques i privades, excepcions i autoritzacions de compatibilitat.',
   'Principio general, actividades públicas y privadas, excepciones y autorizaciones de compatibilidad.',
   ['llei-53-1984-incompat']],
  [10, 'Pressupostos i hisendes locals',
   'Presupuestos y haciendas locales',
   'Recursos de les hisendes locals, principis pressupostaris, elaboració, aprovació, execució i liquidació del pressupost.',
   'Recursos de las haciendas locales, principios presupuestarios, elaboración, aprobación, ejecución y liquidación del presupuesto.',
   ['rdleg-2-2004-trlrhl']],
  [11, 'Règim disciplinari dels funcionaris d’un cos de Policia Local',
   'Régimen disciplinario de los funcionarios de un cuerpo de Policía Local',
   'Faltes molt greus, greus i lleus; sancions; prescripció i procediment disciplinari.',
   'Faltas muy graves, graves y leves; sanciones; prescripción y procedimiento disciplinario.',
   ['llei-16-1991-policies-locals', 'decret-179-2015-disciplinari']],
  [12, 'El procediment administratiu com a garantia d’una actuació correcta',
   'El procedimiento administrativo como garantía de una actuación correcta',
   'Concepte, finalitat i principis generals del procediment administratiu comú.',
   'Concepto, finalidad y principios generales del procedimiento administrativo común.',
   ['llei-39-2015-pac']],
  [13, 'L’acte administratiu',
   'El acto administrativo',
   'Concepte, elements, requisits, motivació, notificació, eficàcia, nul·litat i anul·labilitat.',
   'Concepto, elementos, requisitos, motivación, notificación, eficacia, nulidad y anulabilidad.',
   ['llei-39-2015-pac']],
  [14, 'Les persones en el procediment administratiu',
   'Las personas en el procedimiento administrativo',
   'Capacitat d’obrar, condició d’interessat, representació, drets de les persones i registre electrònic.',
   'Capacidad de obrar, condición de interesado, representación, derechos de las personas y registro electrónico.',
   ['llei-39-2015-pac']],
  [15, 'Aspectes generals de l’activitat administrativa',
   'Aspectos generales de la actividad administrativa',
   'Termes i terminis, còmput, obligació de resoldre, silenci administratiu i abstenció i recusació.',
   'Términos y plazos, cómputo, obligación de resolver, silencio administrativo y abstención y recusación.',
   ['llei-39-2015-pac', 'llei-40-2015-rjsp']],
  [16, 'La regulació del procediment administratiu',
   'La regulación del procedimiento administrativo',
   'Iniciació, ordenació, instrucció i finalització del procediment; mesures provisionals.',
   'Iniciación, ordenación, instrucción y finalización del procedimiento; medidas provisionales.',
   ['llei-39-2015-pac']],
  [17, 'Execució i revisió de l’acte administratiu',
   'Ejecución y revisión del acto administrativo',
   'Executivitat, execució forçosa, revisió d’ofici i recursos administratius.',
   'Ejecutividad, ejecución forzosa, revisión de oficio y recursos administrativos.',
   ['llei-39-2015-pac']],
  [18, 'Transparència i informació pública',
   'Transparencia e información pública',
   'Publicitat activa, dret d’accés a la informació pública, límits i bon govern.',
   'Publicidad activa, derecho de acceso a la información pública, límites y buen gobierno.',
   ['llei-19-2013-transp', 'llei-19-2014-transp-cat']],
  [19, 'Ciberseguretat',
   'Ciberseguridad',
   'Reptes i amenaces, estratègies de seguretat, mesures d’autoprotecció i Agència de Ciberseguretat de Catalunya.',
   'Retos y amenazas, estrategias de seguridad, medidas de autoprotección y Agencia de Ciberseguridad de Cataluña.',
   ['agencia-ciberseguretat-catalunya']],
  [20, 'Protecció de dades com a dret fonamental',
   'Protección de datos como derecho fundamental',
   'Principis del tractament, bases de legitimació, drets de les persones i tractament amb finalitats policials.',
   'Principios del tratamiento, bases de legitimación, derechos de las personas y tratamiento con fines policiales.',
   ['rgpd-2016-679', 'lo-3-2018-lopdgdd', 'ce-1978']],
  [21, 'Llei orgànica 2/1986, de forces i cossos de seguretat',
   'Ley orgánica 2/1986, de fuerzas y cuerpos de seguridad',
   'Concepte, missió, objectius, principis bàsics d’actuació i cossos policials existents.',
   'Concepto, misión, objetivos, principios básicos de actuación y cuerpos policiales existentes.',
   ['lo-2-1986-fcs']],
  [22, 'Llei 4/2003, del sistema de seguretat pública de Catalunya',
   'Ley 4/2003, del sistema de seguridad pública de Cataluña',
   'Coordinació, col·laboració, competències i òrgans del sistema de seguretat pública.',
   'Coordinación, colaboración, competencias y órganos del sistema de seguridad pública.',
   ['llei-4-2003-seguretat-publica']],
  [23, 'Les juntes locals de seguretat',
   'Las juntas locales de seguridad',
   'Naturalesa, composició, funcions i funcionament segons la Llei 4/2003 i el Decret 151/1998.',
   'Naturaleza, composición, funciones y funcionamiento según la Ley 4/2003 y el Decreto 151/1998.',
   ['llei-4-2003-seguretat-publica', 'decret-151-1998-juntes']],
  [24, 'Llei 16/1991, de les policies locals',
   'Ley 16/1991, de las policías locales',
   'Estructura, organització, funcions, escales i categories i principis bàsics d’actuació.',
   'Estructura, organización, funciones, escalas y categorías y principios básicos de actuación.',
   ['llei-16-1991-policies-locals']],
  [25, 'Ètica i deontologia professional',
   'Ética y deontología profesional',
   'Declaració Universal dels Drets Humans, Carta de Drets Fonamentals de la UE i Codi d’ètica de la Policia de Catalunya.',
   'Declaración Universal de los Derechos Humanos, Carta de Derechos Fundamentales de la UE y Código de ética de la Policía de Cataluña.',
   ['ddhh-1948', 'carta-drets-ue', 'codi-etic-policia-catalunya']],
  [26, 'Llei orgànica 4/2015, de protecció de la seguretat ciutadana',
   'Ley orgánica 4/2015, de protección de la seguridad ciudadana',
   'Reunions i manifestacions, potestats d’actuació, armes i explosius i règim sancionador.',
   'Reuniones y manifestaciones, potestades de actuación, armas y explosivos y régimen sancionador.',
   ['lo-4-2015-psc']],
  [27, 'Furts i robatoris',
   'Hurtos y robos',
   'Tipus bàsics i agreujats de furt i robatori, robatori amb força i amb violència o intimidació.',
   'Tipos básicos y agravados de hurto y robo, robo con fuerza y con violencia o intimidación.',
   ['lo-10-1995-cp']],
  [28, 'Jurisdicció penal',
   'Jurisdicción penal',
   'Òrgans de l’ordre jurisdiccional penal, competències i parts del procediment.',
   'Órganos del orden jurisdiccional penal, competencias y partes del procedimiento.',
   ['lecrim-1882', 'ce-1978']],
  [29, 'Codi penal: garanties, aplicació de la llei i seguretat viària',
   'Código penal: garantías, aplicación de la ley y seguridad vial',
   'Principi de legalitat, àmbit d’aplicació de la llei penal i delictes contra la seguretat viària.',
   'Principio de legalidad, ámbito de aplicación de la ley penal y delitos contra la seguridad vial.',
   ['lo-10-1995-cp']],
  [30, 'Llei orgànica 1/2015, modificadora del Codi penal',
   'Ley orgánica 1/2015, modificadora del Código penal',
   'Supressió de les faltes, delictes lleus, presó permanent revisable i principals novetats.',
   'Supresión de las faltas, delitos leves, prisión permanente revisable y principales novedades.',
   ['lo-1-2015-reforma-cp', 'lo-10-1995-cp']],
  [31, 'Coneixements generals de Roses',
   'Conocimientos generales de Roses',
   'Estructura urbana, carrers, barris, nuclis urbans i rurals, serveis, comunicacions, característiques socials i culturals i equipaments públics.',
   'Estructura urbana, calles, barrios, núcleos urbanos y rurales, servicios, comunicaciones, características sociales y culturales y equipamientos públicos.',
   ['roses-web-municipi']],
  [32, 'Permisos i llicències de conducció',
   'Permisos y licencias de conducción',
   'Classes de permisos, condicions dels vehicles, immobilització i retirada de vehicles.',
   'Clases de permisos, condiciones de los vehículos, inmovilización y retirada de vehículos.',
   ['rd-818-2009-rgcond', 'rd-2822-1998-rgv', 'rdleg-6-2015-ltsv']],
  [33, 'Conducció sota els efectes d’alcohol o drogues',
   'Conducción bajo los efectos de alcohol o drogas',
   'Taxes, obligació de sotmetre’s a les proves, procediment de control i conseqüències administratives i penals.',
   'Tasas, obligación de someterse a las pruebas, procedimiento de control y consecuencias administrativas y penales.',
   ['rdleg-6-2015-ltsv', 'rd-1428-2003-rgc', 'lo-10-1995-cp']],
  [34, 'Animals domèstics i de companyia',
   'Animales domésticos y de compañía',
   'Responsabilitats de les persones propietàries, identificació, registre i règim dels gossos potencialment perillosos.',
   'Responsabilidades de las personas propietarias, identificación, registro y régimen de los perros potencialmente peligrosos.',
   ['llei-50-1999-app', 'rd-287-2002-app', 'roses-ordenanca-convivencia']],
  [35, 'Ordenança municipal de circulació de Roses',
   'Ordenanza municipal de circulación de Roses',
   'Objecte, àmbit d’aplicació i ordenació del trànsit al terme municipal de Roses.',
   'Objeto, ámbito de aplicación y ordenación del tráfico en el término municipal de Roses.',
   ['roses-ordenanca-circulacio']],
  [36, 'Ordenança municipal de convivència ciutadana de Roses',
   'Ordenanza municipal de convivencia ciudadana de Roses',
   'Mesures per fomentar i garantir la convivència, conductes prohibides i règim sancionador municipal.',
   'Medidas para fomentar y garantizar la convivencia, conductas prohibidas y régimen sancionador municipal.',
   ['roses-ordenanca-convivencia']],
  [37, 'Policia judicial i persona detinguda',
   'Policía judicial y persona detenida',
   'Funcions de policia judicial, drets i garanties de la persona detinguda, detenció i procediment d’habeas corpus.',
   'Funciones de policía judicial, derechos y garantías de la persona detenida, detención y procedimiento de habeas corpus.',
   ['lecrim-1882', 'lo-6-1984-habeas', 'ce-1978']],
  [38, 'Llei 27/2003: ordre de protecció de les víctimes de violència domèstica',
   'Ley 27/2003: orden de protección de las víctimas de violencia doméstica',
   'Pressupòsits, procediment, contingut de l’ordre i actuació policial.',
   'Presupuestos, procedimiento, contenido de la orden y actuación policial.',
   ['llei-27-2003-ordre-proteccio', 'lecrim-1882']],
  [39, 'Llei orgànica 3/2007: igualtat efectiva entre dones i homes',
   'Ley orgánica 3/2007: igualdad efectiva entre mujeres y hombres',
   'Principi d’igualtat, discriminació directa i indirecta, assetjament i polítiques públiques d’igualtat.',
   'Principio de igualdad, discriminación directa e indirecta, acoso y políticas públicas de igualdad.',
   ['lo-3-2007-igualtat']],
  [40, 'Llei orgànica 5/2000: responsabilitat penal i detenció de menors',
   'Ley orgánica 5/2000: responsabilidad penal y detención de menores',
   'Àmbit d’aplicació, mesures aplicables i especialitats de la detenció de persones menors d’edat.',
   'Ámbito de aplicación, medidas aplicables y especialidades de la detención de personas menores de edad.',
   ['lo-5-2000-menors']],
]

function blockFor(n: number): BlockId {
  if (n <= 20) return 'institucions'
  if (n <= 30) return 'seguretat-i-penal'
  if (n <= 36) return 'roses-transit-convivencia'
  return 'actuacio-i-proteccio'
}

/**
 * Equivalència amb la convocatòria de 2025: només s'inverteixen els temes 10 i
 * 11 (pressupostos i règim disciplinari). La resta coincideix.
 */
function number2025For(n: number): number {
  if (n === 10) return 11
  if (n === 11) return 10
  return n
}

const topics: SyllabusTopic[] = ROWS.map(([n, tCa, tEs, sCa, sEs, sources]) => ({
  topicId: `roses-t${String(n).padStart(2, '0')}`,
  number: n,
  number2025: number2025For(n),
  block: blockFor(n),
  title: { ca: tCa, es: tEs },
  scope: { ca: sCa, es: sEs },
  primarySourceIds: sources,
  examTrack: 'coneixements-professionals',
}))

const syllabus = Syllabus.parse({
  municipality: 'roses',
  callId: 'roses-2026-interins',
  callTitle: {
    ca: 'Convocatòria de 7 places d’agent interí de la Policia Local de Roses i borsa de treball (2026)',
    es: 'Convocatoria de 7 plazas de agente interino de la Policía Local de Roses y bolsa de trabajo (2026)',
  },
  callSourceId: 'roses-bases-2026-interins',
  contrastSourceId: 'roses-bases-2025-propietat',
  topics,
})

mkdirSync('content/municipalities/roses', { recursive: true })
writeFileSync(
  'content/municipalities/roses/syllabus.json',
  JSON.stringify(syllabus, null, 2) + '\n',
)
console.log(`syllabus.json escrit amb ${syllabus.topics.length} temes`)
