/**
 * Preguntes d'actualitat adoptades del paquet de candidats 2026-08-24.
 * **Generat** per `scripts/transcription/import_current_affairs.py`.
 *
 * Cada pregunta té la seva font oberta, contrastada i desada a `sources/cache/`
 * amb el seu SHA-256. Cap s'ha adoptat sense demostrar-ne el fet al document.
 *
 * Totes porten `dynamic: true` amb `reviewBy`: quan la data passa, `isCurrent()`
 * les deixa fora dels quadernets i de la quota, i el simulacre de cultura
 * general es torna a bloquejar sol.
 */
import type { Question } from '../../../schemas/index.ts'

export const CURRENT_AFFAIRS_QUESTIONS: Question[] = [
  {
    questionId: 'actualitat-2026-roses-001',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quin import té el pressupost específic de l\'Ajuntament de Roses per a l\'any 2026, sense sumar-hi les societats municipals?',
    options: [
      { optionId: 'a', text: '44.649.900 €' },
      { optionId: 'b', text: '46.800.000 €' },
      { optionId: 'c', text: '48.400.660 €', whyWrong: 'És el pressupost consolidat, que sí que suma les societats municipals.' },
      { optionId: 'd', text: '50.240.600 €' },
    ],
    correct: 'a',
    explanation: {
      ca: 'El pressupost específic de l\'Ajuntament és de 44.649.900 euros; el consolidat amb les societats municipals és de 48.400.660 euros. (Font: Ajuntament de Roses, 2025-10-28.)',
      es: 'El presupuesto específico del Ayuntamiento es de 44.649.900 euros; el consolidado con las sociedades municipales es de 48.400.660 euros. (Fuente: Ajuntament de Roses, 2025-10-28.)',
    },
    references: [
      {
        sourceId: 'roses-budget-2026',
        locator: 'apartat sobre el pressupost específic de l\'Ajuntament',
        validAt: '2025-10-28',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-01-31',
    tags: ['actualitat', 'ambit-roses'],
  },
  {
    questionId: 'actualitat-2026-roses-002',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quina quantitat preveu el pressupost de Roses de 2026 per a inversions?',
    options: [
      { optionId: 'a', text: '1,4 milions d\'euros' },
      { optionId: 'b', text: '2,4 milions d\'euros' },
      { optionId: 'c', text: '3,4 milions d\'euros' },
      { optionId: 'd', text: '4,2 milions d\'euros' },
    ],
    correct: 'b',
    explanation: {
      ca: 'El pressupost municipal de 2026 preveu 2,4 milions d\'euros per a inversions. (Font: Ajuntament de Roses, 2025-10-28.)',
      es: 'El presupuesto municipal de 2026 prevé 2,4 millones de euros para inversiones. (Fuente: Ajuntament de Roses, 2025-10-28.)',
    },
    references: [
      {
        sourceId: 'roses-budget-2026',
        locator: 'apartat d\'inversions',
        validAt: '2025-10-28',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-01-31',
    tags: ['actualitat', 'ambit-roses'],
  },
  {
    questionId: 'actualitat-2026-roses-003',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'A quina hora situava el programa municipal el pregó teatralitzat de la Festa Major de Roses del 7 d’agost de 2026?',
    options: [
      { optionId: 'a', text: '21.00 h' },
      { optionId: 'b', text: '21.15 h' },
      { optionId: 'c', text: '21.30 h' },
      { optionId: 'd', text: '21.45 h' },
    ],
    correct: 'c',
    explanation: {
      ca: 'El programa de la Festa Major situava el pregó teatralitzat a les 21.30 h. (Font: Ajuntament de Roses, 2026-08-06.)',
      es: 'El programa de la Fiesta Mayor situaba el pregón teatralizado a las 21.30 h. (Fuente: Ajuntament de Roses, 2026-08-06.)',
    },
    references: [
      {
        sourceId: 'roses-prego-festa-major-2026',
        locator: 'paràgraf amb l\'horari de l\'acte',
        validAt: '2026-08-06',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-02-28',
    tags: ['actualitat', 'ambit-roses'],
  },
  {
    questionId: 'actualitat-2026-roses-004',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quantes funcions de Nits de Circ es van programar a Roses entre el 18 i el 23 d\'agost de 2026?',
    options: [
      { optionId: 'a', text: 'Tres' },
      { optionId: 'b', text: 'Quatre' },
      { optionId: 'c', text: 'Cinc' },
      { optionId: 'd', text: 'Sis' },
    ],
    correct: 'd',
    explanation: {
      ca: 'La sisena edició de Nits de Circ va programar sis funcions consecutives, del 18 al 23 d’agost. (Font: Ajuntament de Roses, 2026-08-04.)',
      es: 'La sexta edición de Nits de Circ programó seis funciones consecutivas, del 18 al 23 de agosto. (Fuente: Ajuntament de Roses, 2026-08-04.)',
    },
    references: [
      {
        sourceId: 'roses-nits-circ-2026',
        locator: 'paràgraf introductori',
        validAt: '2026-08-04',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-02-28',
    tags: ['actualitat', 'ambit-roses'],
  },
  {
    questionId: 'actualitat-2026-roses-005',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'A quin grup d\'edat s\'adrecen les classes de català per a alumnat nouvingut que Roses va oferir l\'agost de 2026?',
    options: [
      { optionId: 'a', text: 'D\'11 a 16 anys' },
      { optionId: 'b', text: 'De 12 a 17 anys' },
      { optionId: 'c', text: 'De 13 a 18 anys' },
      { optionId: 'd', text: 'De 14 a 19 anys' },
    ],
    correct: 'a',
    explanation: {
      ca: 'La iniciativa municipal s\'adreça a alumnes nouvinguts d\'entre 11 i 16 anys. (Font: Ajuntament de Roses, 2026-08-21.)',
      es: 'La iniciativa municipal se dirige a alumnos recién llegados de entre 11 y 16 años. (Fuente: Ajuntament de Roses, 2026-08-21.)',
    },
    references: [
      {
        sourceId: 'roses-catala-nouvinguts-2026',
        locator: 'resum inicial',
        validAt: '2026-08-21',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-02-28',
    tags: ['actualitat', 'ambit-roses'],
  },
  {
    questionId: 'actualitat-2026-roses-006',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quants articles va confiscar l’operatiu contra el top manta que va anunciar l’Ajuntament de Roses el 31 de juliol de 2026?',
    options: [
      { optionId: 'a', text: '1.027' },
      { optionId: 'b', text: '1.207' },
      { optionId: 'c', text: '1.270' },
      { optionId: 'd', text: '1.702' },
    ],
    correct: 'b',
    explanation: {
      ca: 'L’operatiu va confiscar un total de 1.207 articles abans que es posessin a la venda. (Font: Ajuntament de Roses, 2026-07-31.)',
      es: 'El operativo confiscó un total de 1.207 artículos antes de que se pusieran a la venta. (Fuente: Ajuntament de Roses, 2026-07-31.)',
    },
    references: [
      {
        sourceId: 'roses-top-manta-2026-07-31',
        locator: 'paràgraf inicial',
        validAt: '2026-07-31',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-02-28',
    tags: ['actualitat', 'ambit-roses'],
  },
  {
    questionId: 'actualitat-2026-roses-007',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'En quines dates va programar l’Ajuntament el Carnaval de Roses 2026?',
    options: [
      { optionId: 'a', text: 'Del 5 al 9 de febrer' },
      { optionId: 'b', text: 'Del 8 al 12 de febrer' },
      { optionId: 'c', text: 'Del 12 al 16 de febrer' },
      { optionId: 'd', text: 'Del 19 al 23 de febrer' },
    ],
    correct: 'c',
    explanation: {
      ca: 'El programa municipal situava el Carnaval de Roses 2026 del dijous 12 al dilluns 16 de febrer. (Font: Ajuntament de Roses, 2026-01-30.)',
      es: 'El programa municipal situaba el Carnaval de Roses 2026 del jueves 12 al lunes 16 de febrero. (Fuente: Ajuntament de Roses, 2026-01-30.)',
    },
    references: [
      {
        sourceId: 'roses-carnaval-revista-2026',
        locator: 'informació de l\'edició 2026',
        validAt: '2026-01-30',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-02-28',
    tags: ['actualitat', 'ambit-roses'],
  },
  {
    questionId: 'actualitat-2026-roses-008',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Qui va crear la imatge oficial del Carnaval de Roses 2026, protagonitzada per la Sirena de la Badia?',
    options: [
      { optionId: 'a', text: 'Ariadna Vieyra' },
      { optionId: 'b', text: 'Laia Ateca Font' },
      { optionId: 'c', text: 'Nagore Aranburu' },
      { optionId: 'd', text: 'Alma Martín Guillén' },
    ],
    correct: 'd',
    explanation: {
      ca: 'La imatge oficial del Carnaval 2026, protagonitzada per la Sirena de la Badia, és obra d\'Alma Martín Guillén. (Font: Ajuntament de Roses, 2025-08-14.)',
      es: 'La imagen oficial del Carnaval 2026, protagonizada por la Sirena de la Badia, es obra de Alma Martín Guillén. (Fuente: Ajuntament de Roses, 2025-08-14.)',
    },
    references: [
      {
        sourceId: 'roses-cartell-carnaval-2026',
        locator: 'títol i presentació del cartell',
        validAt: '2025-08-14',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-02-28',
    tags: ['actualitat', 'ambit-roses'],
  },
  {
    questionId: 'actualitat-2026-cat-009',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'A quin període corresponia la proposta de pressupostos de carboni que el Govern va presentar al Parlament de Catalunya el setembre de 2025?',
    options: [
      { optionId: 'a', text: '2026-2030' },
      { optionId: 'b', text: '2027-2031' },
      { optionId: 'c', text: '2028-2032' },
      { optionId: 'd', text: '2030-2034' },
    ],
    correct: 'a',
    explanation: {
      ca: 'La proposta de pressupostos de carboni presentada al Parlament cobreix el quinquenni 2026-2030. (Font: Parlament de Catalunya, 2025-09-09.)',
      es: 'La propuesta de presupuestos de carbono presentada al Parlamento cubre el quinquenio 2026-2030. (Fuente: Parlament de Catalunya, 2025-09-09.)',
    },
    references: [
      {
        sourceId: 'cat-carboni-2026-2030',
        locator: 'paràgraf sobre els pressupostos de carboni',
        validAt: '2025-09-09',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-03-31',
    tags: ['actualitat', 'ambit-catalunya'],
  },
  {
    questionId: 'actualitat-2026-cat-010',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quin preu públic per crèdit es va fixar per a tots els graus i màsters habilitants de les universitats públiques catalanes el curs 2025-2026?',
    options: [
      { optionId: 'a', text: '15,69 €' },
      { optionId: 'b', text: '17,69 €' },
      { optionId: 'c', text: '18,46 €' },
      { optionId: 'd', text: '19,37 €' },
    ],
    correct: 'b',
    explanation: {
      ca: 'El decret va unificar el preu dels graus i màsters habilitants en 17,69 euros per crèdit. (Font: Generalitat de Catalunya, 2025-06-17.)',
      es: 'El decreto unificó el precio de los grados y másteres habilitantes en 17,69 euros por crédito. (Fuente: Generalitat de Catalunya, 2025-06-17.)',
    },
    references: [
      {
        sourceId: 'cat-preus-universitaris-2025-2026',
        locator: 'primer paràgraf després dels destacats',
        validAt: '2025-06-17',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-01-31',
    tags: ['actualitat', 'ambit-catalunya'],
  },
  {
    questionId: 'actualitat-2026-cat-011',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quantes regions europees agrupava l\'ESRA segons la nota del Govern català del 29 d\'octubre de 2024?',
    options: [
      { optionId: 'a', text: '21' },
      { optionId: 'b', text: '26' },
      { optionId: 'c', text: '31' },
      { optionId: 'd', text: '36' },
    ],
    correct: 'c',
    explanation: {
      ca: 'La nota oficial indicava que l\'Aliança de Regions Europees de Semiconductors agrupava 31 regions. (Font: Generalitat de Catalunya, 2024-10-29.)',
      es: 'La nota oficial indicaba que la Alianza de Regiones Europeas de Semiconductores agrupaba 31 regiones. (Fuente: Generalitat de Catalunya, 2024-10-29.)',
    },
    references: [
      {
        sourceId: 'cat-esra-2026',
        locator: 'segon punt destacat i descripció de l\'aliança',
        validAt: '2024-10-29',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2026-12-31',
    tags: ['actualitat', 'ambit-catalunya'],
  },
  {
    questionId: 'actualitat-2026-cat-012',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Segons la nota del Govern català del 29 d\'octubre de 2024, quants agents formaven l\'ecosistema català de semiconductors?',
    options: [
      { optionId: 'a', text: '160' },
      { optionId: 'b', text: '210' },
      { optionId: 'c', text: '230' },
      { optionId: 'd', text: '260' },
    ],
    correct: 'd',
    explanation: {
      ca: 'L’ecosistema català de semiconductors constava de 260 agents. (Font: Generalitat de Catalunya, 2024-10-29.)',
      es: 'El ecosistema catalán de semiconductores constaba de 260 agentes. (Fuente: Generalitat de Catalunya, 2024-10-29.)',
    },
    references: [
      {
        sourceId: 'cat-esra-2026',
        locator: 'apartat sobre l\'ecosistema de semiconductors',
        validAt: '2024-10-29',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2026-12-31',
    tags: ['actualitat', 'ambit-catalunya'],
  },
  {
    questionId: 'actualitat-2026-cat-013',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quin creixement del consum de les llars per al 2026 preveia l\'escenari macroeconòmic català publicat el maig de 2025?',
    options: [
      { optionId: 'a', text: '2,3%' },
      { optionId: 'b', text: '2,5%' },
      { optionId: 'c', text: '2,8%' },
      { optionId: 'd', text: '3,2%' },
    ],
    correct: 'a',
    explanation: {
      ca: 'L\'escenari preveia que el consum de les llars creixeria un 2,3% el 2026. (Font: Generalitat de Catalunya, 2025-05-15.)',
      es: 'El escenario preveía que el consumo de los hogares crecería un 2,3% en 2026. (Fuente: Generalitat de Catalunya, 2025-05-15.)',
    },
    references: [
      {
        sourceId: 'cat-previsions-2026',
        locator: 'apartat «L\'escenari per al 2026»',
        validAt: '2025-05-15',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2026-12-31',
    tags: ['actualitat', 'ambit-catalunya'],
  },
  {
    questionId: 'actualitat-2026-cat-014',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quina taxa d\'atur per a Catalunya l\'any 2026 preveia l\'escenari macroeconòmic publicat pel Govern el maig de 2025?',
    options: [
      { optionId: 'a', text: '7,4%' },
      { optionId: 'b', text: '8,4%' },
      { optionId: 'c', text: '8,9%' },
      { optionId: 'd', text: '9,4%' },
    ],
    correct: 'b',
    explanation: {
      ca: 'La previsió situava la taxa d\'atur de Catalunya en el 8,4% el 2026. (Font: Generalitat de Catalunya, 2025-05-15.)',
      es: 'La previsión situaba la tasa de paro de Cataluña en el 8,4% en 2026. (Fuente: Generalitat de Catalunya, 2025-05-15.)',
    },
    references: [
      {
        sourceId: 'cat-previsions-2026',
        locator: 'final de l\'apartat «L\'escenari per al 2026»',
        validAt: '2025-05-15',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2026-12-31',
    tags: ['actualitat', 'ambit-catalunya'],
  },
  {
    questionId: 'actualitat-2026-es-015',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quin import té el Bono Cultural Joven 2026?',
    options: [
      { optionId: 'a', text: '200 €' },
      { optionId: 'b', text: '300 €' },
      { optionId: 'c', text: '400 €' },
      { optionId: 'd', text: '500 €' },
    ],
    correct: 'c',
    explanation: {
      ca: 'El Bono Cultural Joven 2026 és un ajut de 400 euros per als joves nascuts el 2008. (Font: La Moncloa, Govern d\'Espanya, 2026-06-22.)',
      es: 'El Bono Cultural Joven 2026 es una ayuda de 400 euros para los jóvenes nacidos en 2008. (Fuente: La Moncloa, Govern d\'Espanya, 2026-06-22.)',
    },
    references: [
      {
        sourceId: 'es-bono-cultural-2026',
        locator: 'presentació de les dues modalitats',
        validAt: '2026-06-22',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-03-31',
    tags: ['actualitat', 'ambit-espanya'],
  },
  {
    questionId: 'actualitat-2026-es-016',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quin d’aquests usos admet el Bono Cultural Joven 2026?',
    options: [
      { optionId: 'a', text: 'Material esportiu' },
      { optionId: 'b', text: 'Viatges turístics' },
      { optionId: 'c', text: 'Telefonia mòbil' },
      { optionId: 'd', text: 'Instruments musicals' },
    ],
    correct: 'd',
    explanation: {
      ca: 'El Bono Cultural Joven 2026 admet cursos i tallers, instruments musicals i material artístic. (Font: La Moncloa, Govern d\'Espanya, 2026-06-22.)',
      es: 'El Bono Cultural Joven 2026 admite cursos y talleres, instrumentos musicales y material artístico. (Fuente: La Moncloa, Govern d\'Espanya, 2026-06-22.)',
    },
    references: [
      {
        sourceId: 'es-bono-cultural-2026',
        locator: 'modalitat 1 i nous usos',
        validAt: '2026-06-22',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-03-31',
    tags: ['actualitat', 'ambit-espanya'],
  },
  {
    questionId: 'actualitat-2026-es-017',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quin import va autoritzar el Consell de Ministres per als ajuts generals de l’ICAA a la producció de llargmetratges el 2026?',
    options: [
      { optionId: 'a', text: '62 milions d\'euros' },
      { optionId: 'b', text: '72 milions d\'euros' },
      { optionId: 'c', text: '82 milions d\'euros' },
      { optionId: 'd', text: '92 milions d\'euros' },
    ],
    correct: 'a',
    explanation: {
      ca: 'La convocatòria d\'ajuts generals per a llargmetratges es va autoritzar per 62 milions d\'euros. (Font: La Moncloa, Govern d\'Espanya, 2026-05-05.)',
      es: 'La convocatoria de ayudas generales para largometrajes se autorizó por 62 millones de euros. (Fuente: La Moncloa, Govern d\'Espanya, 2026-05-05.)',
    },
    references: [
      {
        sourceId: 'es-icaa-2026',
        locator: 'apartat «Cultura»',
        validAt: '2026-05-05',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-03-31',
    tags: ['actualitat', 'ambit-espanya'],
  },
  {
    questionId: 'actualitat-2026-es-018',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'En aprovar el projecte d’Estatut de les persones en formació pràctica no laboral, el març de 2026, el Govern espanyol va dir que s’havia superat la xifra de dos milions de joves. Quin percentatge eren dones?',
    options: [
      { optionId: 'a', text: '51%' },
      { optionId: 'b', text: '56%' },
      { optionId: 'c', text: '61%' },
      { optionId: 'd', text: '66%' },
    ],
    correct: 'b',
    explanation: {
      ca: 'En presentar el projecte d’Estatut de les persones en formació pràctica no laboral, el Govern va xifrar en un 56% les dones d’aquest col·lectiu. (Font: La Moncloa, Govern d\'Espanya, 2026-03-03.)',
      es: 'Al presentar el proyecto de Estatuto de las personas en formación práctica no laboral, el Gobierno cifró en un 56% las mujeres de este colectivo. (Fuente: La Moncloa, Govern d\'Espanya, 2026-03-03.)',
    },
    references: [
      {
        sourceId: 'es-estatut-practiques-2026',
        locator: 'segon paràgraf',
        validAt: '2026-03-03',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-03-31',
    tags: ['actualitat', 'ambit-espanya'],
  },
  {
    questionId: 'actualitat-2026-es-019',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'On es va reunir Pedro Sánchez amb el papa Lleó XIV a Madrid el 8 de juny de 2026?',
    options: [
      { optionId: 'a', text: 'Al Congrés dels Diputats' },
      { optionId: 'b', text: 'Al Palau de la Moncloa' },
      { optionId: 'c', text: 'A la Nunciatura Apostòlica' },
      { optionId: 'd', text: 'Al Palau de la Zarzuela' },
    ],
    correct: 'c',
    explanation: {
      ca: 'La trobada es va celebrar a la Nunciatura Apostòlica de Madrid. (Font: La Moncloa, Govern d\'Espanya, 2026-06-08.)',
      es: 'El encuentro se celebró en la Nunciatura Apostólica de Madrid. (Fuente: La Moncloa, Govern d\'Espanya, 2026-06-08.)',
    },
    references: [
      {
        sourceId: 'es-visita-lleo-xiv-2026',
        locator: 'capçalera de lloc i paràgraf inicial',
        validAt: '2026-06-08',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-06-08',
    tags: ['actualitat', 'ambit-espanya'],
  },
  {
    questionId: 'actualitat-2026-eu-020',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Per quina vegada exercia Irlanda la presidència del Consell de la Unió Europea durant el segon semestre de 2026?',
    options: [
      { optionId: 'a', text: 'Cinquena' },
      { optionId: 'b', text: 'Sisena' },
      { optionId: 'c', text: 'Setena' },
      { optionId: 'd', text: 'Vuitena' },
    ],
    correct: 'd',
    explanation: {
      ca: 'Irlanda va assumir la presidència del Consell l’1 de juliol de 2026, per vuitena vegada. (Font: Consell de la Unió Europea, Presidència irlandesa, 2026-07-01.)',
      es: 'Irlanda asumió la presidencia del Consejo el 1 de julio de 2026, por octava vez. (Fuente: Consell de la Unió Europea, Presidència irlandesa, 2026-07-01.)',
    },
    references: [
      {
        sourceId: 'eu-presidencia-irlanda-2026',
        locator: 'paràgraf inicial',
        validAt: '2026-07-01',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2026-12-31',
    tags: ['actualitat', 'ambit-internacional'],
  },
  {
    questionId: 'actualitat-2026-eu-021',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quins són els tres eixos centrals del programa de la presidència irlandesa del Consell de la UE de 2026?',
    options: [
      { optionId: 'a', text: 'Competitivitat, valors i seguretat' },
      { optionId: 'b', text: 'Clima, agricultura i turisme' },
      { optionId: 'c', text: 'Fiscalitat, pesca i cultura' },
      { optionId: 'd', text: 'Energia, educació i transport' },
    ],
    correct: 'a',
    explanation: {
      ca: 'El programa irlandès s\'articula al voltant de competitivitat, valors i seguretat. (Font: Consell de la Unió Europea, Presidència irlandesa, 2026-07-01.)',
      es: 'El programa irlandés se articula en torno a competitividad, valores y seguridad. (Fuente: Consell de la Unió Europea, Presidència irlandesa, 2026-07-01.)',
    },
    references: [
      {
        sourceId: 'eu-presidencia-irlanda-2026',
        locator: 'introducció i llista dels tres pilars',
        validAt: '2026-07-01',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2026-12-31',
    tags: ['actualitat', 'ambit-internacional'],
  },
  {
    questionId: 'actualitat-2026-cultura-022',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quants premis Goya va obtenir «Los Domingos» en la 40a edició, celebrada el 2026?',
    options: [
      { optionId: 'a', text: 'Quatre' },
      { optionId: 'b', text: 'Cinc' },
      { optionId: 'c', text: 'Sis', whyWrong: 'Sis són els Goya tècnics de «Sirat», no els premis de «Los Domingos».' },
      { optionId: 'd', text: 'Set' },
    ],
    correct: 'b',
    explanation: {
      ca: '«Los Domingos» va obtenir cinc dels tretze premis als quals optava, inclòs el de millor pel·lícula. (Font: Academia de las Artes y las Ciencias Cinematográficas de España, 2026-03-01.)',
      es: '«Los Domingos» obtuvo cinco de los trece premios a los que optaba, incluido el de mejor película. (Fuente: Academia de las Artes y las Ciencias Cinematográficas de España, 2026-03-01.)',
    },
    references: [
      {
        sourceId: 'goya-2026',
        locator: 'primer paràgraf',
        validAt: '2026-03-01',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-03-31',
    tags: ['actualitat', 'ambit-espanya'],
  },
  {
    questionId: 'actualitat-2026-cultura-023',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Quants premis Goya tècnics va obtenir «Sirat» en l\'edició de 2026?',
    options: [
      { optionId: 'a', text: 'Quatre' },
      { optionId: 'b', text: 'Cinc', whyWrong: 'Cinc són els premis de «Los Domingos», la gran guanyadora de la nit.' },
      { optionId: 'c', text: 'Sis' },
      { optionId: 'd', text: 'Set' },
    ],
    correct: 'c',
    explanation: {
      ca: '«Sirat» va obtenir sis guardons en categories tècniques. (Font: Academia de las Artes y las Ciencias Cinematográficas de España, 2026-03-01.)',
      es: '«Sirat» obtuvo seis galardones en categorías técnicas. (Fuente: Academia de las Artes y las Ciencias Cinematográficas de España, 2026-03-01.)',
    },
    references: [
      {
        sourceId: 'goya-2026',
        locator: 'primer paràgraf i relació de premis de «Sirat»',
        validAt: '2026-03-01',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-03-31',
    tags: ['actualitat', 'ambit-espanya'],
  },
  {
    questionId: 'actualitat-2026-cultura-024',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Per a quin dia es va programar la gran final de la 70a edició del Festival d’Eurovisió, a Viena?',
    options: [
      { optionId: 'a', text: '10 de maig' },
      { optionId: 'b', text: '12 de maig' },
      { optionId: 'c', text: '14 de maig' },
      { optionId: 'd', text: '16 de maig' },
    ],
    correct: 'd',
    explanation: {
      ca: 'L’EBU va anunciar la gran final per a dissabte 16 de maig, al Wiener Stadthalle de Viena. (Font: European Broadcasting Union, Eurovision Song Contest, 2025-08-20.)',
      es: 'La EBU anunció la gran final para el sábado 16 de mayo, en el Wiener Stadthalle de Viena. (Fuente: European Broadcasting Union, Eurovision Song Contest, 2025-08-20.)',
    },
    references: [
      {
        sourceId: 'eurovision-2026',
        locator: 'paràgraf amb el calendari de semifinals i final',
        validAt: '2025-08-20',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-05-16',
    tags: ['actualitat', 'ambit-internacional'],
  },
  {
    questionId: 'actualitat-2026-esport-025',
    topicId: 'roses-t31',
    track: 'cultura-general',
    origin: 'authored',
    status: 'active',
    difficulty: 'mitjana',
    stem: 'Per a quines dates es van programar els Jocs Olímpics d’Hivern Milano Cortina 2026?',
    options: [
      { optionId: 'a', text: 'Del 6 al 22 de febrer' },
      { optionId: 'b', text: 'Del 12 al 28 de febrer' },
      { optionId: 'c', text: 'Del 6 al 15 de març' },
      { optionId: 'd', text: 'Del 12 al 28 de març' },
    ],
    correct: 'a',
    explanation: {
      ca: 'El Comitè Olímpic Internacional situava els Jocs Milano Cortina 2026 del 6 al 22 de febrer. (Font: Comitè Olímpic Internacional, 2025-02-06.)',
      es: 'El Comité Olímpico Internacional situaba los Juegos Milano Cortina 2026 del 6 al 22 de febrero. (Fuente: Comitè Olímpic Internacional, 2025-02-06.)',
    },
    references: [
      {
        sourceId: 'olimpics-hivern-2026',
        locator: 'descripció oficial de l\'esdeveniment',
        validAt: '2025-02-06',
        reviewStatus: 'verified',
      },
    ],
    dynamic: true,
    reviewBy: '2027-02-28',
    tags: ['actualitat', 'ambit-internacional'],
  },
]
