import type { Question } from '../../../schemas/index.ts'
import { questionsFor, ref } from '../authoring.ts'

export const QUESTIONS_37_40: Question[] = [
  ...questionsFor(37, [
    {
      n: 1,
      stem: 'Quin d’aquests NO és un dret de la persona detinguda segons la Llei d’enjudiciament criminal?',
      options: [
        'Guardar silenci i no declarar contra si mateixa',
        'Ser reconeguda pel metge forense',
        'Escollir el jutjat que instruirà la causa',
        'Accedir als elements de les actuacions essencials per impugnar la legalitat de la detenció',
      ],
      correct: 'c',
      whyWrong: {
        a: 'És un dret expressament reconegut.',
        b: 'És un dret expressament reconegut.',
        d: 'És un dret expressament reconegut.',
      },
      explainCa: 'La competència judicial ve determinada per la llei i no és disponible per a les parts. La resta d’opcions són drets recollits expressament al catàleg de drets de la persona detinguda.',
      explainEs: 'La competencia judicial viene determinada por la ley y no es disponible para las partes. El resto de opciones son derechos recogidos expresamente en el catálogo de derechos de la persona detenida.',
      refs: [ref('lecrim-1882', 'art. 520')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Els particulars, davant un delicte:',
      options: [
        'Estan obligats a detenir en tot cas',
        'Poden detenir en els supòsits taxats que preveu la llei',
        'No poden detenir mai',
        'Poden detenir amb autorització telefònica d’un agent',
      ],
      correct: 'b',
      whyWrong: {
        a: "L'obligació de detenir recau sobre l’autoritat i els agents de policia judicial.",
        c: 'La llei ho permet expressament en supòsits concrets.',
        d: 'No existeix cap autorització d’aquest tipus.',
      },
      explainCa: 'Els particulars **poden** detenir qui intenti cometre un delicte en el moment d’anar a cometre’l, el delinqüent in fraganti, qui s’hagi fugat d’un establiment penal o mentre és conduït a la presó, i el processat o condemnat en rebel·lia. L’autoritat i els agents de policia judicial, en canvi, **han** de detenir.',
      explainEs: 'Los particulares **pueden** detener a quien intente cometer un delito en el momento de ir a cometerlo, al delincuente in fraganti, a quien se haya fugado de un establecimiento penal o mientras es conducido a prisión, y al procesado o condenado en rebeldía. La autoridad y los agentes de policía judicial, en cambio, **deben** detener.',
      refs: [ref('lecrim-1882', 'art. 490 i 492')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Qui NO està legitimat per instar un procediment d’habeas corpus?',
      options: [
        'El Ministeri Fiscal',
        'El Defensor del Poble',
        'Qualsevol veí del municipi sense relació amb la persona detinguda',
        'El cònjuge de la persona privada de llibertat',
      ],
      correct: 'c',
      whyWrong: {
        a: 'Està expressament legitimat.',
        b: 'Està expressament legitimat.',
        d: 'Està expressament legitimat.',
      },
      explainCa: 'La legitimació és taxada: la persona privada de llibertat, el seu cònjuge o persona unida per relació anàloga d’afectivitat, descendents, ascendents, germans, els representants legals si és menor o persona amb la capacitat modificada, el Ministeri Fiscal i el Defensor del Poble. També pot iniciar-lo d’ofici el jutge competent.',
      explainEs: 'La legitimación es tasada: la persona privada de libertad, su cónyuge o persona unida por relación análoga de afectividad, descendientes, ascendientes, hermanos, los representantes legales si es menor o persona con la capacidad modificada, el Ministerio Fiscal y el Defensor del Pueblo. También puede iniciarlo de oficio el juez competente.',
      refs: [ref('lo-6-1984-habeas', 'art. 3')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'Quin jutge és competent per conèixer d’un procediment d’habeas corpus?',
      options: [
        'El jutge d’instrucció del lloc on es trobi la persona detinguda',
        'El jutge del domicili de la persona detinguda',
        'El president de l’audiència provincial',
        'El jutge de vigilància penitenciària',
      ],
      correct: 'a',
      whyWrong: {
        b: 'El criteri és el lloc de la privació de llibertat, no el domicili.',
        c: 'No té atribuïda aquesta competència.',
        d: 'Actua sobre l’execució de penes privatives de llibertat.',
      },
      explainCa: 'És competent el jutge d’instrucció del lloc on es trobi la persona privada de llibertat; si no consta, el del lloc on es va produir la detenció; i, en defecte d’aquests, el del lloc on s’hagin tingut les últimes notícies del seu parador. Ha de resoldre en vint-i-quatre hores.',
      explainEs: 'Es competente el juez de instrucción del lugar donde se encuentre la persona privada de libertad; si no consta, el del lugar donde se produjo la detención; y, en defecto de estos, el del lugar donde se hayan tenido las últimas noticias sobre su paradero. Debe resolver en veinticuatro horas.',
      refs: [ref('lo-6-1984-habeas', 'art. 2 i 7')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'L’habeas corpus serveix per:',
      options: [
        'Determinar si la persona detinguda és culpable',
        'Examinar la legalitat de la privació de llibertat',
        'Substituir el judici oral',
        'Revisar la qualificació jurídica dels fets',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La culpabilitat es dilucida al procés penal, no en aquest procediment.',
        c: 'És un procediment de garantia, no d’enjudiciament.',
        d: 'La qualificació correspon a la instrucció i al judici.',
      },
      explainCa: 'L’habeas corpus és un procediment sumari i urgent que té per objecte únic i exclusiu examinar la legalitat de la privació de llibertat i, si escau, posar immediatament la persona en llibertat o a disposició judicial. No entra en el fons de la causa.',
      explainEs: 'El habeas corpus es un procedimiento sumario y urgente que tiene por objeto único y exclusivo examinar la legalidad de la privación de libertad y, en su caso, poner inmediatamente a la persona en libertad o a disposición judicial. No entra en el fondo de la causa.',
      refs: [ref('lo-6-1984-habeas', 'art. 1'), ref('ce-1978', 'art. 17.4')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(38, [
    {
      n: 1,
      stem: 'Qui pot acordar una ordre de protecció d’una víctima de violència domèstica?',
      options: [
        'El cap de la policia local',
        'El jutge competent',
        'El Ministeri Fiscal per si sol',
        'Els serveis socials municipals',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La policia recull i tramita la sol·licitud, però no acorda la mesura.',
        c: 'El Ministeri Fiscal la pot sol·licitar, però no acordar-la.',
        d: 'Poden rebre i traslladar la sol·licitud, no acordar-la.',
      },
      explainCa: 'L’ordre de protecció l’acorda sempre l’autoritat judicial mitjançant resolució. La policia, els serveis socials, les oficines d’atenció a la víctima i el Ministeri Fiscal poden rebre o instar la sol·licitud, però la decisió correspon al jutge.',
      explainEs: 'La orden de protección la acuerda siempre la autoridad judicial mediante resolución. La policía, los servicios sociales, las oficinas de atención a la víctima y el Ministerio Fiscal pueden recibir o instar la solicitud, pero la decisión corresponde al juez.',
      refs: [ref('llei-27-2003-ordre-proteccio', 'competència judicial'), ref('lecrim-1882', 'art. 544 ter')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'En quin termini màxim s’ha de celebrar l’audiència urgent per resoldre una ordre de protecció?',
      options: ['24 hores', '48 hores', '72 hores', '5 dies'],
      correct: 'c',
      whyWrong: {
        a: 'És el termini de resolució d’un habeas corpus i el de detenció d’un menor.',
        b: 'No correspon al termini legal.',
        d: 'No correspon al termini legal.',
      },
      explainCa: 'Rebuda la sol·licitud, el jutge de guàrdia convoca una audiència urgent amb la víctima o el seu representant legal, el sol·licitant, el presumpte agressor assistit de lletrat i el Ministeri Fiscal. Aquesta audiència s’ha de celebrar en un termini màxim de setanta-dues hores des de la presentació de la sol·licitud.',
      explainEs: 'Recibida la solicitud, el juez de guardia convoca una audiencia urgente con la víctima o su representante legal, el solicitante, el presunto agresor asistido de letrado y el Ministerio Fiscal. Esta audiencia debe celebrarse en un plazo máximo de setenta y dos horas desde la presentación de la solicitud.',
      refs: [ref('lecrim-1882', 'art. 544 ter.4'), ref('llei-27-2003-ordre-proteccio', 'procediment')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Els dos pressupòsits per acordar una ordre de protecció són:',
      options: [
        'Denúncia prèvia i informe mèdic',
        'Indicis fundats de delicte i situació objectiva de risc per a la víctima',
        'Convivència acreditada i menors a càrrec',
        'Antecedents penals de l’agressor i reincidència',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Ni la denúncia prèvia ni l’informe mèdic són pressupòsits legals autònoms.',
        c: 'La convivència no és imprescindible.',
        d: 'Els antecedents no són un requisit.',
      },
      explainCa: 'Cal que existeixin indicis fundats de la comissió d’un delicte contra la vida, la integritat física o moral, la llibertat sexual, la llibertat o la seguretat d’alguna de les persones incloses en l’àmbit protegit, i que en resulti una situació objectiva de risc que requereixi l’adopció d’alguna mesura de protecció.',
      explainEs: 'Es necesario que existan indicios fundados de la comisión de un delito contra la vida, la integridad física o moral, la libertad sexual, la libertad o la seguridad de alguna de las personas incluidas en el ámbito protegido, y que resulte una situación objetiva de riesgo que requiera la adopción de alguna medida de protección.',
      refs: [ref('lecrim-1882', 'art. 544 ter.1')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Les mesures civils que pot contenir una ordre de protecció:',
      options: [
        'Tenen vigència indefinida',
        'Tenen una vigència temporal limitada i s’han de ratificar en el procés civil corresponent',
        'No existeixen: l’ordre només conté mesures penals',
        'Les acorda directament el servei social',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Tenen una vigència limitada precisament per no substituir el procés civil.',
        c: 'L’ordre és un estatut integral amb mesures penals i civils.',
        d: 'Les acorda el jutge.',
      },
      explainCa: 'L’ordre de protecció pot incloure mesures civils com l’atribució de l’ús de l’habitatge familiar, el règim de custòdia i visites, i la prestació d’aliments. Aquestes mesures tenen una vigència temporal limitada, pensada perquè es consolidin —o no— en el procés de família corresponent.',
      explainEs: 'La orden de protección puede incluir medidas civiles como la atribución del uso de la vivienda familiar, el régimen de custodia y visitas, y la prestación de alimentos. Estas medidas tienen una vigencia temporal limitada, pensada para que se consoliden —o no— en el proceso de familia correspondiente.',
      refs: [ref('lecrim-1882', 'art. 544 ter.7')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Una víctima demana protecció a la comissaria de la Policia Local de Roses. L’actuació correcta és:',
      options: [
        'Indicar-li que s’adreci pel seu compte al jutjat',
        'Recollir la sol·licitud, instruir les diligències i remetre-la immediatament al jutjat de guàrdia',
        'Esperar que presenti denúncia formal en un altre cos',
        'Derivar-la exclusivament als serveis socials',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei preveu que la policia reculli i traslladi la sol·licitud.',
        c: 'La sol·licitud es pot presentar davant qualsevol força o cos de seguretat.',
        d: 'La derivació social no substitueix el trasllat judicial urgent.',
      },
      explainCa: 'La sol·licitud d’ordre de protecció es pot presentar davant les forces i cossos de seguretat. Rebuda, s’ha de remetre de manera immediata al jutge de guàrdia competent, sense perjudici de la coordinació amb els serveis socials i amb l’oficina d’atenció a la víctima.',
      explainEs: 'La solicitud de orden de protección puede presentarse ante las fuerzas y cuerpos de seguridad. Recibida, debe remitirse de manera inmediata al juez de guardia competente, sin perjuicio de la coordinación con los servicios sociales y con la oficina de atención a la víctima.',
      refs: [ref('lecrim-1882', 'art. 544 ter.3'), ref('llei-27-2003-ordre-proteccio', 'presentació de la sol·licitud')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(39, [
    {
      n: 1,
      stem: 'Es produeix discriminació indirecta per raó de sexe quan:',
      options: [
        'Una persona és tractada obertament pitjor per raó del seu sexe',
        'Una disposició, criteri o pràctica aparentment neutres posen persones d’un sexe en desavantatge particular',
        'Es prenen mesures d’acció positiva',
        'Es garanteix una presència equilibrada en un tribunal de selecció',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Aquesta és la definició de discriminació directa.',
        c: 'Les accions positives estan expressament permeses per la llei.',
        d: 'La presència equilibrada és un instrument d’igualtat, no una discriminació.',
      },
      explainCa: 'La discriminació indirecta es produeix quan una disposició, un criteri o una pràctica aparentment neutres posen persones d’un sexe en desavantatge particular respecte de persones de l’altre, llevat que puguin justificar-se objectivament amb una finalitat legítima i que els mitjans siguin adequats i necessaris.',
      explainEs: 'La discriminación indirecta se produce cuando una disposición, un criterio o una práctica aparentemente neutros ponen a personas de un sexo en desventaja particular respecto de personas del otro, salvo que puedan justificarse objetivamente con una finalidad legítima y que los medios sean adecuados y necesarios.',
      refs: [ref('lo-3-2007-igualtat', 'art. 6')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Segons la Llei orgànica 3/2007, l’assetjament sexual i l’assetjament per raó de sexe:',
      options: [
        'Es consideren sempre actes discriminatoris',
        'Només són discriminatoris si els comet un superior jeràrquic',
        'Requereixen intenció acreditada per ser il·lícits',
        'Només afecten l’àmbit laboral privat',
      ],
      correct: 'a',
      whyWrong: {
        b: 'La condició de l’autor no condiciona la qualificació.',
        c: 'La llei atén tant al propòsit com a l’efecte de la conducta.',
        d: "S'apliquen també a l’àmbit públic.",
      },
      explainCa: 'La llei estableix que l’assetjament sexual i l’assetjament per raó de sexe es consideren en tot cas actes discriminatoris, i afegeix que el condicionament d’un dret o d’una expectativa de dret a l’acceptació d’una situació d’assetjament també és discriminació.',
      explainEs: 'La ley establece que el acoso sexual y el acoso por razón de sexo se consideran en todo caso actos discriminatorios, y añade que el condicionamiento de un derecho o de una expectativa de derecho a la aceptación de una situación de acoso también es discriminación.',
      refs: [ref('lo-3-2007-igualtat', 'art. 7')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Les accions positives previstes per la llei d’igualtat:',
      options: [
        'Estan prohibides per vulnerar el principi d’igualtat',
        'Són mesures específiques i temporals, admissibles mentre subsisteixi la desigualtat que pretenen corregir',
        'Són permanents i indefinides',
        'Només les pot adoptar el sector privat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei les admet expressament com a instrument d’igualtat real.',
        c: 'La temporalitat n’és un element essencial.',
        d: 'Els poders públics n’han d’adoptar de manera destacada.',
      },
      explainCa: 'Els poders públics poden adoptar mesures específiques a favor de les dones per corregir situacions patents de desigualtat de fet respecte dels homes. Aquestes mesures han de ser raonables i proporcionades en relació amb l’objectiu perseguit i s’han d’aplicar mentre subsisteixin aquestes situacions.',
      explainEs: 'Los poderes públicos pueden adoptar medidas específicas a favor de las mujeres para corregir situaciones patentes de desigualdad de hecho respecto de los hombres. Estas medidas deben ser razonables y proporcionadas en relación con el objetivo perseguido y deben aplicarse mientras subsistan dichas situaciones.',
      refs: [ref('lo-3-2007-igualtat', 'art. 11')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Un tracte desfavorable a una dona relacionat amb l’embaràs o la maternitat:',
      options: [
        'És lícit si respon a raons organitzatives',
        'Constitueix en tot cas discriminació directa per raó de sexe',
        'Només és discriminació si es produeix durant la baixa',
        'És una qüestió laboral aliena a la llei d’igualtat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Les raons organitzatives no justifiquen aquest tracte.',
        c: 'La protecció no es limita al període de baixa.',
        d: 'La llei d’igualtat ho regula expressament.',
      },
      explainCa: 'La llei disposa que constitueix discriminació directa per raó de sexe tot tracte desfavorable a les dones relacionat amb l’embaràs o la maternitat. És una de les manifestacions més clares i menys matisables de la discriminació directa.',
      explainEs: 'La ley dispone que constituye discriminación directa por razón de sexo todo trato desfavorable a las mujeres relacionado con el embarazo o la maternidad. Es una de las manifestaciones más claras y menos matizables de la discriminación directa.',
      refs: [ref('lo-3-2007-igualtat', 'art. 8')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'La indemnitat davant represàlies significa que:',
      options: [
        'Les denúncies falses no tenen conseqüències',
        'Ningú pot patir un tracte advers per haver denunciat o participat en un procediment sobre discriminació',
        'Les persones denunciades no poden ser sancionades',
        'Les denúncies són sempre anònimes',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La indemnitat no ampara la denúncia falsa.',
        c: 'La protecció opera a favor de qui denuncia o testifica.',
        d: "L'anonimat no és el contingut d’aquesta garantia.",
      },
      explainCa: 'La llei considera discriminació per raó de sexe qualsevol tracte advers o efecte negatiu que es produeixi en una persona com a conseqüència de la presentació d’una queixa, reclamació, denúncia, demanda o recurs destinats a impedir la seva discriminació i a exigir el compliment efectiu del principi d’igualtat.',
      explainEs: 'La ley considera discriminación por razón de sexo cualquier trato adverso o efecto negativo que se produzca en una persona como consecuencia de la presentación de una queja, reclamación, denuncia, demanda o recurso destinados a impedir su discriminación y a exigir el cumplimiento efectivo del principio de igualdad.',
      refs: [ref('lo-3-2007-igualtat', 'art. 9')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(40, [
    {
      n: 1,
      stem: 'A quines edats s’aplica la Llei orgànica 5/2000, reguladora de la responsabilitat penal dels menors?',
      options: [
        'A partir dels 12 i fins als 18 anys',
        'A partir dels 14 i fins als 18 anys',
        'A partir dels 16 i fins als 21 anys',
        'A partir dels 14 i fins als 21 anys',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Els menors de catorze anys no tenen responsabilitat penal.',
        c: "L'edat mínima és catorze anys.",
        d: 'El límit superior és divuit anys.',
      },
      explainCa: 'La llei s’aplica per exigir responsabilitat a les persones majors de catorze anys i menors de divuit per la comissió de fets tipificats com a delictes. Als menors de catorze anys no se’ls exigeix responsabilitat penal: se’ls aplica la normativa de protecció de menors.',
      explainEs: 'La ley se aplica para exigir responsabilidad a las personas mayores de catorce años y menores de dieciocho por la comisión de hechos tipificados como delitos. A los menores de catorce años no se les exige responsabilidad penal: se les aplica la normativa de protección de menores.',
      refs: [ref('lo-5-2000-menors', 'art. 1 i 3')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Quin és el termini màxim de detenció d’un menor per part de funcionaris de policia?',
      options: ['12 hores', '24 hores', '48 hores', '72 hores'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon al termini legal.',
        c: 'No correspon al termini legal.',
        d: '72 hores és el termini màxim general per a persones majors d’edat.',
      },
      explainCa: 'La detenció d’un menor no pot durar més temps del estrictament necessari i, en tot cas, dins el termini màxim de vint-i-quatre hores el menor detingut ha de ser posat en llibertat o a disposició del Ministeri Fiscal.',
      explainEs: 'La detención de un menor no puede durar más tiempo del estrictamente necesario y, en todo caso, dentro del plazo máximo de veinticuatro horas el menor detenido debe ser puesto en libertad o a disposición del Ministerio Fiscal.',
      refs: [ref('lo-5-2000-menors', 'art. 17.4')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Un menor detingut ha de ser posat a disposició de:',
      options: [
        'El jutge d’instrucció',
        'El Ministeri Fiscal',
        'El jutge de menors directament',
        "L'entitat pública de protecció de menors",
      ],
      correct: 'b',
      whyWrong: {
        a: 'El jutge d’instrucció no dirigeix la investigació en el procés de menors.',
        c: 'El jutge de menors decideix, però la posada a disposició inicial és davant el Fiscal.',
        d: 'Correspon als menors de catorze anys, no als detinguts per un fet delictiu.',
      },
      explainCa: 'En el procés de menors, la investigació la dirigeix el Ministeri Fiscal. Per això el menor detingut es posa a disposició del Fiscal, i no del jutge, dins el termini màxim de vint-i-quatre hores.',
      explainEs: 'En el proceso de menores, la investigación la dirige el Ministerio Fiscal. Por eso el menor detenido se pone a disposición del Fiscal, y no del juez, dentro del plazo máximo de veinticuatro horas.',
      refs: [ref('lo-5-2000-menors', 'art. 16 i 17')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Durant la detenció d’un menor, la custòdia s’ha de fer:',
      options: [
        'Als mateixos calabossos que els majors d’edat si no hi ha altre espai',
        'En dependències adequades i separades de les que s’utilitzen per als majors d’edat',
        'Al domicili familiar sota vigilància',
        'A l’entitat de protecció de menors en tot cas',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La separació és una exigència legal, no una recomanació.',
        c: 'La custòdia policial no es fa al domicili.',
        d: 'L’entitat de protecció actua en supòsits diferents.',
      },
      explainCa: 'La llei exigeix que el menor detingut romangui custodiat en dependències adequades i separades de les que s’utilitzen per als majors d’edat, i que se li dispensi les cures, la protecció i l’assistència social, psicològica, mèdica i física que requereixi.',
      explainEs: 'La ley exige que el menor detenido permanezca custodiado en dependencias adecuadas y separadas de las que se utilizan para los mayores de edad, y que se le dispense los cuidados, la protección y la asistencia social, psicológica, médica y física que requiera.',
      refs: [ref('lo-5-2000-menors', 'art. 17.3')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Quin és el criteri rector per triar la mesura aplicable a un menor?',
      options: [
        'La gravetat objectiva del fet exclusivament',
        "L'interès superior del menor",
        'La petició de la víctima',
        'La reincidència en tot cas',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La gravetat es té en compte, però no és el criteri rector únic.',
        c: 'La víctima és part, però no determina la mesura.',
        d: 'La reincidència és una circumstància, no el criteri rector.',
      },
      explainCa: 'El procés de menors té naturalesa formalment penal però materialment sancionadora-educativa. El criteri rector per determinar la mesura és l’interès superior del menor, valorat per equips tècnics especialitzats, juntament amb les circumstàncies del fet i de l’autor.',
      explainEs: 'El proceso de menores tiene naturaleza formalmente penal pero materialmente sancionadora-educativa. El criterio rector para determinar la medida es el interés superior del menor, valorado por equipos técnicos especializados, junto con las circunstancias del hecho y del autor.',
      refs: [ref('lo-5-2000-menors', 'exposició de motius i art. 7')],
      difficulty: 'mitjana',
    },
  ]),
]
