import type { Question } from '../../../schemas/index.ts'
import { questionsFor, refv } from '../authoring.ts'

export const QUESTIONS_26_30: Question[] = [
  ...questionsFor(26, [
    {
      n: 1,
      stem: 'El temps màxim de permanència en dependències policials per a una diligència d’identificació és de:',
      options: ['2 hores', '6 hores', '12 hores', '24 hores'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon al límit legal.',
        c: 'No correspon al límit legal.',
        d: '24 hores és el termini màxim de detenció d’un menor, no una diligència d’identificació.',
      },
      explainCa: 'Quan no es pot identificar una persona per cap mitjà, se la pot requerir per acompanyar els agents a dependències properes que disposin dels mitjans adequats. La permanència ha de ser pel temps estrictament necessari i, en tot cas, no pot superar les sis hores.',
      explainEs: 'Cuando no se puede identificar a una persona por ningún medio, se le puede requerir para acompañar a los agentes a dependencias próximas que dispongan de los medios adecuados. La permanencia debe ser por el tiempo estrictamente necesario y, en todo caso, no puede superar las seis horas.',
      refs: [refv('lo-4-2015-psc', 'art. 16', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'El trasllat a dependències per a una diligència d’identificació:',
      options: [
        'Equival jurídicament a una detenció',
        'No és una detenció, però s’ha de registrar al llibre-registre corresponent',
        'No requereix cap constància documental',
        'Genera antecedents policials automàticament',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És una figura diferent, amb règim i durada propis.',
        c: 'La llei exigeix expressament un llibre-registre.',
        d: 'No genera antecedents per si mateixa.',
      },
      explainCa: 'La diligència d’identificació no és una detenció i no comporta els drets de l’article 520 de la Llei d’enjudiciament criminal, però la llei obliga a portar un llibre-registre on constin les diligències practicades, la causa, la identitat i la durada.',
      explainEs: 'La diligencia de identificación no es una detención y no comporta los derechos del artículo 520 de la Ley de enjuiciamiento criminal, pero la ley obliga a llevar un libro-registro donde consten las diligencias practicadas, la causa, la identidad y la duración.',
      refs: [refv('lo-4-2015-psc', 'art. 16.3', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'Un registre corporal que obligui a deixar a la vista parts del cos normalment cobertes:',
      options: [
        'Es pot fer a la via pública si hi ha urgència',
        'S’ha de fer en un lloc reservat, fora de la vista de tercers, i se n’ha d’estendre diligència',
        'Requereix sempre autorització judicial prèvia',
        'Està prohibit en tot cas',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei exigeix expressament un lloc reservat.',
        c: 'No cal autorització judicial per al registre corporal extern amb els requisits legals.',
        d: 'És possible amb els requisits i garanties que fixa la llei.',
      },
      explainCa: 'Quan el registre exigeixi deixar a la vista parts del cos normalment cobertes, s’ha de fer en un lloc reservat i fora de la vista de terceres persones, se n’ha de deixar constància escrita mitjançant diligència i, sempre que sigui possible, l’ha de practicar un agent del mateix sexe.',
      explainEs: 'Cuando el registro exija dejar a la vista partes del cuerpo normalmente cubiertas, debe hacerse en un lugar reservado y fuera de la vista de terceras personas, debe dejarse constancia escrita mediante diligencia y, siempre que sea posible, debe practicarlo un agente del mismo sexo.',
      refs: [refv('lo-4-2015-psc', 'art. 20', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quin és el rang de la sanció econòmica per a una infracció greu de la Llei orgànica 4/2015?',
      options: [
        'De 100 a 600 euros',
        'De 601 a 30.000 euros',
        'De 30.001 a 600.000 euros',
        'De 1.000 a 10.000 euros',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Correspon a les infraccions lleus.',
        c: 'Correspon a les infraccions molt greus.',
        d: 'No correspon a cap tram legal.',
      },
      explainCa: 'La llei estableix tres trams: les infraccions molt greus se sancionen amb multa de 30.001 a 600.000 euros, les greus de 601 a 30.000 euros i les lleus de 100 a 600 euros.',
      explainEs: 'La ley establece tres tramos: las infracciones muy graves se sancionan con multa de 30.001 a 600.000 euros, las graves de 601 a 30.000 euros y las leves de 100 a 600 euros.',
      refs: [refv('lo-4-2015-psc', 'art. 39', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Una reunió pacífica i sense armes en un lloc de trànsit públic:',
      options: [
        'Requereix autorització administrativa prèvia',
        'Requereix comunicació prèvia a l’autoritat, però no autorització',
        'No requereix cap tràmit',
        'Requereix autorització judicial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La Constitució exclou expressament l’autorització prèvia.',
        c: 'En llocs de trànsit públic i manifestacions cal comunicació prèvia.',
        d: 'No hi intervé cap autorització judicial prèvia.',
      },
      explainCa: 'El dret de reunió no està sotmès a autorització prèvia. En els casos de reunions en llocs de trànsit públic i de manifestacions cal donar comunicació prèvia a l’autoritat, que només les pot prohibir per raons fonamentades d’alteració de l’ordre públic amb perill per a persones o béns.',
      explainEs: 'El derecho de reunión no está sometido a autorización previa. En los casos de reuniones en lugares de tránsito público y de manifestaciones hay que dar comunicación previa a la autoridad, que solo puede prohibirlas por razones fundadas de alteración del orden público con peligro para personas o bienes.',
      refs: [refv('ce-1978', 'art. 21', '2026-08-24'), refv('lo-4-2015-psc', 'art. 23', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(27, [
    {
      n: 1,
      stem: 'Quina és la diferència essencial entre furt i robatori?',
      options: [
        'El valor del que se sostreu',
        'L’ús de força en les coses o de violència o intimidació en les persones',
        'El lloc on es comet el fet',
        'L’hora en què es comet el fet',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El valor distingeix delicte de delicte lleu dins el furt, però no furt de robatori.',
        c: 'El lloc pot agreujar el tipus, però no el transforma.',
        d: 'L’hora no és un element del tipus.',
      },
      explainCa: 'El furt consisteix a prendre coses mobles alienes amb ànim de lucre i sense la voluntat del propietari. Hi ha robatori quan, a més, s’empra força en les coses per accedir-hi o violència o intimidació en les persones.',
      explainEs: 'El hurto consiste en tomar cosas muebles ajenas con ánimo de lucro y sin la voluntad del propietario. Hay robo cuando, además, se emplea fuerza en las cosas para acceder a ellas o violencia o intimidación en las personas.',
      refs: [refv('lo-10-1995-cp', 'art. 234 i 237', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Quin és el llindar que separa el furt delicte del furt delicte lleu?',
      options: ['200 euros', '300 euros', '400 euros', '600 euros'],
      correct: 'c',
      whyWrong: {
        a: 'No correspon al llindar legal.',
        b: 'No correspon al llindar legal.',
        d: 'No correspon al llindar legal.',
      },
      explainCa: 'El furt de coses el valor de les quals excedeixi els 400 euros és delicte; si no els excedeix, es tracta d’un delicte lleu. Aquest llindar es va consolidar amb la reforma de 2015 en desaparèixer les faltes.',
      explainEs: 'El hurto de cosas cuyo valor exceda de 400 euros es delito; si no los excede, se trata de un delito leve. Este umbral se consolidó con la reforma de 2015 al desaparecer las faltas.',
      refs: [refv('lo-10-1995-cp', 'art. 234', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'Quin d’aquests supòsits NO constitueix força en les coses segons el Codi penal?',
      options: [
        'L’escalament',
        'L’ús de claus falses',
        'Arrencar un objecte pesant per poder-se’l endur',
        'La inutilització de sistemes específics d’alarma o guarda',
      ],
      correct: 'c',
      whyWrong: {
        a: 'És un dels supòsits expressos.',
        b: 'És un dels supòsits expressos.',
        d: 'És un dels supòsits expressos.',
      },
      explainCa: 'La força que qualifica el robatori és la que s’empra **per accedir** a la cosa o al lloc on es troba, no la que es fa servir per traslladar-la. Arrencar un objecte perquè pesa o està fixat no és, per si sol, força en les coses en el sentit del Codi penal.',
      explainEs: 'La fuerza que califica el robo es la que se emplea **para acceder** a la cosa o al lugar donde se encuentra, no la que se usa para trasladarla. Arrancar un objeto porque pesa o está fijado no es, por sí solo, fuerza en las cosas en el sentido del Código penal.',
      refs: [refv('lo-10-1995-cp', 'art. 238', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'A efectes del delicte de robatori amb força, es consideren claus falses:',
      options: [
        'Només els ganxets i instruments anàlegs',
        'Els ganxets, les claus legítimes perdudes o obtingudes il·lícitament i qualsevol altra no destinada pel propietari a obrir el pany',
        'Únicament les claus copiades sense permís',
        'Només les claus metàl·liques, mai els dispositius electrònics',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La definició legal és molt més àmplia.',
        c: 'La còpia il·lícita és només un dels supòsits.',
        d: 'Les targetes magnètiques i els comandaments a distància es consideren claus.',
      },
      explainCa: 'El Codi penal considera claus falses els ganxets i altres instruments anàlegs, les claus legítimes perdudes pel propietari o obtingudes per un mitjà que constitueixi infracció penal, i qualsevol altra que no sigui la destinada pel propietari per obrir el pany violentat. Les targetes magnètiques o perforades i els comandaments d’obertura a distància es consideren claus.',
      explainEs: 'El Código penal considera llaves falsas las ganzúas y otros instrumentos análogos, las llaves legítimas perdidas por el propietario u obtenidas por un medio que constituya infracción penal, y cualquier otra que no sea la destinada por el propietario para abrir la cerradura violentada. Las tarjetas magnéticas o perforadas y los mandos de apertura a distancia se consideran llaves.',
      refs: [refv('lo-10-1995-cp', 'art. 239', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Una persona s’emporta del passeig marítim de Roses una bicicleta que no estava lligada, valorada en 300 euros. Quina qualificació correspon?',
      options: [
        'Robatori amb força en les coses',
        'Furt en la modalitat de delicte lleu',
        'Furt en la modalitat de delicte',
        'Robatori amb violència',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No hi ha força en les coses: la bicicleta no estava assegurada.',
        c: 'El valor no supera els 400 euros.',
        d: 'No hi ha violència ni intimidació sobre cap persona.',
      },
      explainCa: 'No hi ha força en les coses perquè no cal vèncer cap obstacle per accedir a la bicicleta, ni violència ni intimidació sobre persones. És, per tant, un furt, i com que el valor no supera els 400 euros, es qualifica com a delicte lleu.',
      explainEs: 'No hay fuerza en las cosas porque no hay que vencer ningún obstáculo para acceder a la bicicleta, ni violencia ni intimidación sobre personas. Es, por tanto, un hurto, y como el valor no supera los 400 euros, se califica como delito leve.',
      refs: [refv('lo-10-1995-cp', 'art. 234 i 237', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(28, [
    {
      n: 1,
      stem: 'Quin òrgan judicial enjudicia els delictes lleus?',
      options: [
        'El jutjat penal',
        'El jutjat d’instrucció',
        'L’audiència provincial',
        'El jutjat de pau en tot cas',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Jutja delictes amb pena privativa de llibertat de fins a cinc anys.',
        c: 'Jutja els delictes més greus i resol recursos.',
        d: 'Els jutjats de pau tenen competències molt limitades i no generals en aquesta matèria.',
      },
      explainCa: 'Des de la reforma de 2015, que va suprimir les faltes, els delictes lleus els enjudicien els jutjats d’instrucció, que a més investiguen la resta de delictes.',
      explainEs: 'Desde la reforma de 2015, que suprimió las faltas, los delitos leves los enjuician los juzgados de instrucción, que además investigan el resto de delitos.',
      refs: [refv('lecrim-1882', 'competència per a l’enjudiciament de delictes lleus', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'L’acusació popular és la que exerceix:',
      options: [
        'La persona ofesa pel delicte',
        'Qualsevol ciutadà en els delictes públics, encara que no sigui la persona ofesa',
        'El Ministeri Fiscal',
        'L’advocat de la defensa',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Aquesta és l’acusació particular.',
        c: 'El Ministeri Fiscal exerceix l’acció penal pública en defensa de la legalitat.',
        d: 'La defensa no acusa.',
      },
      explainCa: 'L’acusació particular la formula la persona ofesa pel delicte; l’acusació popular pot exercir-la qualsevol ciutadà en els delictes públics encara que no hagi estat perjudicat; i l’acusació privada opera en els delictes només perseguibles a instància de part.',
      explainEs: 'La acusación particular la formula la persona ofendida por el delito; la acusación popular puede ejercerla cualquier ciudadano en los delitos públicos aunque no haya sido perjudicado; y la acusación privada opera en los delitos solo perseguibles a instancia de parte.',
      refs: [refv('lecrim-1882', 'parts acusadores', '2026-08-24'), refv('ce-1978', 'art. 125', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Quin valor té, en principi, l’atestat policial en el procés penal?',
      options: [
        'Valor de prova plena',
        'Valor de denúncia',
        'Cap valor jurídic',
        'Valor de sentència provisional',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Només adquireix valor probatori si es reprodueix i es contradiu al judici oral.',
        c: 'Sí que té valor: el de denúncia.',
        d: 'Un atestat no és una resolució judicial.',
      },
      explainCa: 'L’atestat té, en principi, valor de denúncia. Perquè el seu contingut adquireixi valor probatori cal que es reprodueixi i se sotmeti a contradicció en el judici oral, amb l’excepció de les diligències objectives i irrepetibles com la inspecció ocular o les actes d’intervenció.',
      explainEs: 'El atestado tiene, en principio, valor de denuncia. Para que su contenido adquiera valor probatorio hace falta que se reproduzca y se someta a contradicción en el juicio oral, con la excepción de las diligencias objetivas e irrepetibles como la inspección ocular o las actas de intervención.',
      refs: [refv('lecrim-1882', 'valor de l’atestat', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'La policia judicial actua sota la dependència funcional de:',
      options: [
        'L’alcalde del municipi',
        'Els jutges, els tribunals i el Ministeri Fiscal',
        'El Departament d’Interior',
        'La Delegació del Govern',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La dependència orgànica és municipal, però la funcional en policia judicial no.',
        c: 'Exerceix la coordinació, no la direcció de la investigació.',
        d: 'No dirigeix la investigació penal.',
      },
      explainCa: 'En les funcions d’esbrinament del delicte i descobriment i assegurament del delinqüent, la policia judicial depèn funcionalment dels jutges, dels tribunals i del Ministeri Fiscal, sens perjudici de la seva dependència orgànica del seu cos.',
      explainEs: 'En las funciones de averiguación del delito y descubrimiento y aseguramiento del delincuente, la policía judicial depende funcionalmente de los jueces, de los tribunales y del Ministerio Fiscal, sin perjuicio de su dependencia orgánica de su cuerpo.',
      refs: [refv('ce-1978', 'art. 126', '2026-08-24'), refv('lo-2-1986-fcs', 'art. 31.1', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Quin és l’òrgan penal superior de l’Estat en tots els ordres, excepte en matèria de garanties constitucionals?',
      options: [
        'L’Audiència Nacional',
        'El Tribunal Suprem',
        'El Tribunal Constitucional',
        'El Consell General del Poder Judicial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Té competències especialitzades d’àmbit estatal, però no és l’òrgan superior.',
        c: 'És l’intèrpret suprem de la Constitució, però no forma part del poder judicial.',
        d: 'És l’òrgan de govern del poder judicial, sense funcions jurisdiccionals.',
      },
      explainCa: 'El Tribunal Suprem, amb jurisdicció en tot Espanya, és l’òrgan jurisdiccional superior en tots els ordres, llevat del que disposa la Constitució en matèria de garanties constitucionals. La seva Sala Segona és la sala penal.',
      explainEs: 'El Tribunal Supremo, con jurisdicción en toda España, es el órgano jurisdiccional superior en todos los órdenes, salvo lo dispuesto en la Constitución en materia de garantías constitucionales. Su Sala Segunda es la sala penal.',
      refs: [refv('ce-1978', 'art. 123', '2026-08-24')],
      difficulty: 'facil',
    },
  ]),

  ...questionsFor(29, [
    {
      n: 1,
      stem: 'A partir de quin excés de velocitat es comet delicte contra la seguretat viària en via urbana?',
      options: [
        '40 km/h per sobre del límit',
        '60 km/h per sobre del límit',
        '80 km/h per sobre del límit',
        '100 km/h per sobre del límit',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No correspon al llindar penal.',
        c: '80 km/h és el llindar en via interurbana.',
        d: 'No correspon a cap llindar legal.',
      },
      explainCa: 'És delicte conduir un vehicle de motor o un ciclomotor a una velocitat superior en seixanta quilòmetres per hora a la permesa reglamentàriament en via urbana, o en vuitanta quilòmetres per hora en via interurbana.',
      explainEs: 'Es delito conducir un vehículo de motor o un ciclomotor a una velocidad superior en sesenta kilómetros por hora a la permitida reglamentariamente en vía urbana, o en ochenta kilómetros por hora en vía interurbana.',
      refs: [refv('lo-10-1995-cp', 'art. 379.1', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'La negativa a sotmetre’s a les proves de detecció d’alcohol o drogues és:',
      options: [
        'Una infracció administrativa molt greu',
        'Un delicte autònom, encara que la persona no anés beguda',
        'Una circumstància agreujant del delicte de conducció sota la influència',
        'Un fet atípic si finalment es fa la prova',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La negativa està tipificada penalment, no només administrativament.',
        c: 'És un tipus autònom, no una agreujant.',
        d: 'La consumació es produeix amb la negativa mateixa.',
      },
      explainCa: 'El Codi penal castiga de manera autònoma qui, requerit per un agent de l’autoritat, es negui a sotmetre’s a les proves legalment establertes de comprovació de les taxes d’alcoholèmia i de la presència de drogues. Es castiga la desobediència en si, amb independència del resultat que hauria donat la prova.',
      explainEs: 'El Código penal castiga de manera autónoma a quien, requerido por un agente de la autoridad, se niegue a someterse a las pruebas legalmente establecidas de comprobación de las tasas de alcoholemia y de la presencia de drogas. Se castiga la desobediencia en sí, con independencia del resultado que habría dado la prueba.',
      refs: [refv('lo-10-1995-cp', 'art. 383', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Segons el principi de legalitat penal, les lleis penals:',
      options: [
        'Són sempre retroactives',
        'No són retroactives, llevat que afavoreixin la persona reu',
        'Són retroactives només si ho diu una disposició transitòria',
        'No són mai retroactives en cap circumstància',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La regla general és exactament la contrària.',
        c: 'La retroactivitat favorable opera per imperatiu legal, no per disposició transitòria.',
        d: 'La retroactivitat favorable és un principi consolidat.',
      },
      explainCa: 'Les lleis penals no tenen efecte retroactiu, però sí que el tenen les que afavoreixin la persona reu, encara que en entrar en vigor hi hagi sentència ferma i s’estigui complint condemna.',
      explainEs: 'Las leyes penales no tienen efecto retroactivo, pero sí lo tienen las que favorezcan a la persona reo, aunque al entrar en vigor haya sentencia firme y se esté cumpliendo condena.',
      refs: [refv('lo-10-1995-cp', 'art. 2', '2026-08-24'), refv('ce-1978', 'art. 9.3 i 25.1', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Conduir havent perdut la totalitat dels punts assignats legalment:',
      options: [
        'És només una infracció administrativa molt greu',
        'Constitueix delicte contra la seguretat viària',
        'És atípic si es conserva el document físic del permís',
        'Només és delicte si es reincideix tres vegades',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La conducta està tipificada penalment.',
        c: 'La possessió del document no legitima la conducció.',
        d: 'No cal cap reincidència per a la tipicitat.',
      },
      explainCa: 'El Codi penal castiga qui condueixi un vehicle de motor o ciclomotor havent perdut la vigència del permís per pèrdua total dels punts assignats legalment, després d’haver estat privat cautelarment o definitivament del dret a conduir per decisió judicial, o sense haver obtingut mai permís o llicència.',
      explainEs: 'El Código penal castiga a quien conduzca un vehículo de motor o ciclomotor habiendo perdido la vigencia del permiso por pérdida total de los puntos asignados legalmente, tras haber sido privado cautelar o definitivamente del derecho a conducir por decisión judicial, o sin haber obtenido nunca permiso o licencia.',
      refs: [refv('lo-10-1995-cp', 'art. 384', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Col·locar obstacles imprevisibles a la calçada creant un greu risc per a la circulació:',
      options: [
        'És una simple infracció administrativa',
        'Constitueix un delicte contra la seguretat viària',
        'Només és punible si es produeix un accident',
        'És un delicte de danys',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La conducta està expressament tipificada al Codi penal.',
        c: 'És un delicte de perill: no cal resultat lesiu.',
        d: 'El bé jurídic protegit és la seguretat viària, no el patrimoni.',
      },
      explainCa: 'El Codi penal castiga qui originï un greu risc per a la circulació col·locant a la via obstacles imprevisibles, vessant substàncies lliscants o inflamables, mutant o alterant la senyalització, o no restablint la seguretat de la via quan hi estigui obligat. És un delicte de perill: no cal que es produeixi cap accident.',
      explainEs: 'El Código penal castiga a quien origine un grave riesgo para la circulación colocando en la vía obstáculos imprevisibles, derramando sustancias deslizantes o inflamables, mutando o alterando la señalización, o no restableciendo la seguridad de la vía cuando esté obligado. Es un delito de peligro: no hace falta que se produzca ningún accidente.',
      refs: [refv('lo-10-1995-cp', 'art. 385', '2026-08-24')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(30, [
    {
      n: 1,
      stem: 'Quin llibre del Codi penal va suprimir la Llei orgànica 1/2015?',
      options: ['El llibre I', 'El llibre II', 'El llibre III', 'Cap: només va modificar articles'],
      correct: 'c',
      whyWrong: {
        a: 'Conté les disposicions generals sobre delictes i penes.',
        b: 'Conté els delictes i les seves penes.',
        d: 'La supressió del llibre III va ser un dels canvis centrals.',
      },
      explainCa: 'La reforma de 2015 va suprimir el llibre III del Codi penal, dedicat a les faltes. Algunes conductes es van despenalitzar i altres es van reconvertir en delictes lleus, integrats al llibre II.',
      explainEs: 'La reforma de 2015 suprimió el libro III del Código penal, dedicado a las faltas. Algunas conductas se despenalizaron y otras se reconvirtieron en delitos leves, integrados en el libro II.',
      refs: [refv('lo-1-2015-reforma-cp', 'supressió del llibre III', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Quina pena va introduir la Llei orgànica 1/2015 per a supòsits d’excepcional gravetat?',
      options: [
        'La cadena perpètua',
        'La presó permanent revisable',
        'La reclusió major',
        'La pena de mort per a delictes de terrorisme',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La denominació legal és «presó permanent revisable», amb un règim de revisió obligatòria.',
        c: 'És una denominació del Codi penal anterior a 1995.',
        d: 'La pena de mort està abolida per la Constitució, tret del que puguin disposar les lleis penals militars en temps de guerra.',
      },
      explainCa: 'La Llei orgànica 1/2015 va introduir la presó permanent revisable per a supòsits d’excepcional gravetat expressament taxats, amb un sistema de revisió obligatòria de la situació penitenciària un cop complerta una part de la condemna.',
      explainEs: 'La Ley orgánica 1/2015 introdujo la prisión permanente revisable para supuestos de excepcional gravedad expresamente tasados, con un sistema de revisión obligatoria de la situación penitenciaria una vez cumplida una parte de la condena.',
      refs: [refv('lo-1-2015-reforma-cp', 'presó permanent revisable', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Amb la desaparició de les faltes, moltes conductes menors van passar a ser:',
      options: [
        'Impunes en tot cas',
        'Delictes greus',
        'Delictes lleus o infraccions administratives, especialment de la Llei orgànica 4/2015',
        'Faltes disciplinàries',
      ],
      correct: 'c',
      whyWrong: {
        a: 'La despenalització no equival a impunitat: moltes van passar a la via administrativa.',
        b: 'No es van agreujar.',
        d: 'El règim disciplinari només afecta empleats públics.',
      },
      explainCa: 'La reforma va repartir les antigues faltes en dues direccions: algunes es van convertir en delictes lleus dins el Codi penal i altres van passar a l’àmbit administratiu sancionador, sobretot a la Llei orgànica 4/2015 de protecció de la seguretat ciutadana i a les ordenances municipals.',
      explainEs: 'La reforma repartió las antiguas faltas en dos direcciones: algunas se convirtieron en delitos leves dentro del Código penal y otras pasaron al ámbito administrativo sancionador, sobre todo a la Ley orgánica 4/2015 de protección de la seguridad ciudadana y a las ordenanzas municipales.',
      refs: [
        refv(
          'lo-1-2015-reforma-cp',
          'reconversió de les faltes',
          '2026-08-24',
          'El preàmbul remet a la via administrativa sense anomenar la LO 4/2015.',
        ),
        refv('lo-4-2015-psc', 'règim sancionador', '2026-08-24'),
      ],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'La multireincidència introduïda per la reforma de 2015 permet que:',
      options: [
        'Els furts lleus reiterats es tractin com a delicte encara que cap superi els 400 euros',
        'Es dupliqui automàticament qualsevol pena',
        'S’apliqui la presó permanent revisable al furt',
        'Es prescindeixi del judici oral',
      ],
      correct: 'a',
      whyWrong: {
        b: 'No hi ha cap duplicació automàtica de penes.',
        c: 'La presó permanent revisable només s’aplica a supòsits taxats de màxima gravetat.',
        d: 'Les garanties processals es mantenen íntegres.',
      },
      explainCa: 'La reforma va introduir l’agreujament per multireincidència en el furt: la comissió reiterada de sostraccions de petita quantia pot qualificar-se com a delicte encara que cap fet aïllat superi els 400 euros. Va ser la resposta legislativa a la desaparició de la falta de furt.',
      explainEs: 'La reforma introdujo la agravación por multirreincidencia en el hurto: la comisión reiterada de sustracciones de pequeña cuantía puede calificarse como delito aunque ningún hecho aislado supere los 400 euros. Fue la respuesta legislativa a la desaparición de la falta de hurto.',
      refs: [refv('lo-1-2015-reforma-cp', 'reforma dels delictes contra el patrimoni', '2026-08-24'), refv('lo-10-1995-cp', 'art. 235.1.7è', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Quina d’aquestes figures NO va ser introduïda o reformada per la Llei orgànica 1/2015?',
      options: [
        'El delicte d’assetjament o fustigació persistent',
        'La difusió no consentida d’imatges íntimes obtingudes amb consentiment',
        'El decomís ampliat',
        'El delicte de conducció amb pèrdua total de punts',
      ],
      correct: 'd',
      whyWrong: {
        a: 'Va ser una de les novetats de la reforma.',
        b: 'Va ser una de les novetats de la reforma.',
        c: 'La reforma va ampliar substancialment el règim del decomís.',
      },
      explainCa: 'El delicte de conducció havent perdut la totalitat dels punts ja existia abans de 2015: es va introduir amb la reforma de seguretat viària de 2007. La reforma de 2015 sí que va crear l’assetjament persistent, la difusió no consentida d’imatges íntimes i el decomís ampliat.',
      explainEs: 'El delito de conducción habiendo perdido la totalidad de los puntos ya existía antes de 2015: se introdujo con la reforma de seguridad vial de 2007. La reforma de 2015 sí creó el acoso persistente, la difusión no consentida de imágenes íntimas y el decomiso ampliado.',
      refs: [refv('lo-1-2015-reforma-cp', 'novetats de la reforma', '2026-08-24'), refv('lo-10-1995-cp', 'art. 384', '2026-08-24')],
      difficulty: 'dificil',
    },
  ]),
]
