import type { Question } from '../../../schemas/index.ts'
import { questionsFor, ref, refv } from '../authoring.ts'

export const QUESTIONS_21_25: Question[] = [
  ...questionsFor(21, [
    {
      n: 1,
      stem: 'Segons la Llei orgànica 2/1986, les armes de foc només es poden utilitzar:',
      options: [
        'Sempre que hi hagi resistència a l’autoritat',
        'En situacions de risc racionalment greu per a la vida o la integritat física pròpia o de tercers, o de risc greu per a la seguretat ciutadana',
        'Quan ho autoritzi el comandament de servei',
        'Per impedir la fugida de qualsevol persona detinguda',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La resistència no justifica per si sola l’ús de l’arma de foc.',
        c: 'Cap autorització interna pot ampliar el límit legal.',
        d: 'La simple fugida no autoritza l’ús de l’arma de foc.',
      },
      explainCa: 'La llei estableix que els membres de les forces i cossos de seguretat només poden utilitzar les armes en situacions en què hi hagi un risc racionalment greu per a la seva vida o integritat física o per a la de terceres persones, o un risc greu per a la seguretat ciutadana, i sempre d’acord amb els principis de congruència, oportunitat i proporcionalitat.',
      explainEs: 'La ley establece que los miembros de las fuerzas y cuerpos de seguridad solo pueden utilizar las armas en situaciones en que exista un riesgo racionalmente grave para su vida o integridad física o para la de terceras personas, o un riesgo grave para la seguridad ciudadana, y siempre de acuerdo con los principios de congruencia, oportunidad y proporcionalidad.',
      refs: [refv('lo-2-1986-fcs', 'art. 5.2.d', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quins principis han de regir la utilització dels mitjans a l’abast de la policia?',
      options: [
        'Eficàcia, rapidesa i contundència',
        'Congruència, oportunitat i proporcionalitat',
        'Legalitat, jerarquia i disciplina',
        'Prudència, discreció i reserva',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No són els principis legals de l’ús de mitjans.',
        c: 'Són principis d’organització, no de graduació de l’ús de mitjans.',
        d: 'Descriuen una actitud, no el trípode legal.',
      },
      explainCa: 'La llei imposa actuar amb la decisió necessària i sense demora quan d’això depengui evitar un dany greu, immediat i irreparable, regint-se en fer-ho pels principis de congruència, oportunitat i proporcionalitat en la utilització dels mitjans al seu abast.',
      explainEs: 'La ley impone actuar con la decisión necesaria y sin demora cuando de ello dependa evitar un daño grave, inmediato e irreparable, rigiéndose al hacerlo por los principios de congruencia, oportunidad y proporcionalidad en la utilización de los medios a su alcance.',
      refs: [refv('lo-2-1986-fcs', 'art. 5.2.c', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'La instrucció d’atestats per accidents de circulació correspon a la policia local:',
      options: [
        'A tot el terme municipal, inclosa la xarxa interurbana',
        'Dins el nucli urbà',
        'Només si hi ha víctimes',
        'Només si ho autoritza el jutjat de guàrdia',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Fora del nucli urbà la competència correspon a un altre cos.',
        c: 'La presència de víctimes no és el criteri de delimitació.',
        d: 'No cal cap autorització judicial prèvia per instruir un atestat.',
      },
      explainCa: 'Entre les funcions de les policies locals, la llei inclou instruir atestats per accidents de circulació esdevinguts dins el nucli urbà. Això no eximeix d’assegurar el lloc i prestar auxili a qualsevol punt del terme quan s’hi arriba primer.',
      explainEs: 'Entre las funciones de las policías locales, la ley incluye instruir atestados por accidentes de circulación ocurridos dentro del casco urbano. Esto no exime de asegurar el lugar y prestar auxilio en cualquier punto del término cuando se llega primero.',
      refs: [refv('lo-2-1986-fcs', 'art. 53.1', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quina és la naturalesa de la Guàrdia Civil segons la Llei orgànica 2/1986?',
      options: [
        'Institut armat de naturalesa civil',
        'Institut armat de naturalesa militar',
        'Cos administratiu sense naturalesa armada',
        'Cos autonòmic de seguretat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Aquesta és la naturalesa del Cos Nacional de Policia i de les policies locals.',
        c: 'És un institut armat.',
        d: 'És un cos dependent de l’Administració General de l’Estat.',
      },
      explainCa: 'La llei configura el Cos Nacional de Policia com un institut armat de naturalesa civil i la Guàrdia Civil com un institut armat de naturalesa militar. Els cossos de policia local són també instituts armats de naturalesa civil.',
      explainEs: 'La ley configura el Cuerpo Nacional de Policía como un instituto armado de naturaleza civil y la Guardia Civil como un instituto armado de naturaleza militar. Los cuerpos de policía local son también institutos armados de naturaleza civil.',
      refs: [refv('lo-2-1986-fcs', 'art. 9', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'Quin d’aquests grups NO forma part dels principis bàsics d’actuació de la Llei orgànica 2/1986?',
      options: [
        'Tractament de detinguts',
        'Secret professional',
        'Rendiment econòmic del servei',
        'Relacions amb la comunitat',
      ],
      correct: 'c',
      whyWrong: {
        a: 'És un dels grups de principis.',
        b: 'És un dels grups de principis.',
        d: 'És un dels grups de principis.',
      },
      explainCa: 'Els principis bàsics d’actuació s’estructuren en sis grups: adequació a l’ordenament jurídic, relacions amb la comunitat, tractament de detinguts, dedicació professional, secret professional i responsabilitat. El rendiment econòmic no hi figura.',
      explainEs: 'Los principios básicos de actuación se estructuran en seis grupos: adecuación al ordenamiento jurídico, relaciones con la comunidad, tratamiento de detenidos, dedicación profesional, secreto profesional y responsabilidad. El rendimiento económico no figura.',
      refs: [refv('lo-2-1986-fcs', 'art. 5', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(22, [
    {
      n: 1,
      stem: 'La Llei 4/2003 de Catalunya regula:',
      options: [
        'El règim disciplinari de les policies locals',
        'L’ordenació del sistema de seguretat pública de Catalunya',
        'L’estructura del cos de Mossos d’Esquadra',
        'La protecció de la seguretat ciutadana',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Això correspon a la Llei 16/1991 i al Decret 179/2015.',
        c: 'El cos de Mossos té la seva pròpia llei reguladora.',
        d: 'Això correspon a la Llei orgànica 4/2015, de caràcter estatal.',
      },
      explainCa: 'La Llei 4/2003, de 7 d’abril, d’ordenació del sistema de seguretat pública de Catalunya, articula com es relacionen les administracions, els cossos policials i els serveis d’emergències dins un sistema integrat.',
      explainEs: 'La Ley 4/2003, de 7 de abril, de ordenación del sistema de seguridad pública de Cataluña, articula cómo se relacionan las administraciones, los cuerpos policiales y los servicios de emergencias dentro de un sistema integrado.',
      refs: [refv('llei-4-2003-seguretat-publica', 'objecte de la llei', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Quin és l’òrgan consultiu i de participació superior en matèria de seguretat de Catalunya?',
      options: [
        'La Junta de Seguretat de Catalunya',
        'El Consell de Seguretat de Catalunya',
        'La Comissió de Coordinació Policial',
        'El Consell General del Poder Judicial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La Junta de Seguretat és l’òrgan de coordinació amb l’Estat, amb funcions diferents.',
        c: 'No és l’òrgan superior de participació que preveu la llei.',
        d: 'És l’òrgan de govern del poder judicial, aliè al sistema de seguretat.',
      },
      explainCa: 'El Consell de Seguretat de Catalunya és l’òrgan consultiu i de participació superior en matèria de seguretat, on hi són representades les administracions, els cossos i la societat civil.',
      explainEs: 'El Consejo de Seguridad de Cataluña es el órgano consultivo y de participación superior en materia de seguridad, donde están representadas las administraciones, los cuerpos y la sociedad civil.',
      refs: [refv('llei-4-2003-seguretat-publica', 'òrgans del sistema', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Quin instrument concreta al municipi els objectius del Pla general de seguretat de Catalunya?',
      options: [
        'El reglament orgànic municipal',
        'El pla local de seguretat',
        'L’ordenança de convivència',
        'El pressupost municipal',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Regula l’organització interna de la corporació.',
        c: 'Regula conductes cíviques, no la planificació de seguretat.',
        d: 'És un instrument econòmic.',
      },
      explainCa: 'El pla local de seguretat és l’instrument que concreta al municipi els objectius del Pla general de seguretat de Catalunya, a partir de l’anàlisi de la realitat local, i l’aprova la junta local de seguretat.',
      explainEs: 'El plan local de seguridad es el instrumento que concreta en el municipio los objetivos del Plan general de seguridad de Cataluña, a partir del análisis de la realidad local, y lo aprueba la junta local de seguridad.',
      refs: [refv('llei-4-2003-seguretat-publica', 'planificació de la seguretat', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quin d’aquests serveis NO forma part del sistema de seguretat pública de Catalunya?',
      options: [
        'Els serveis de prevenció i extinció d’incendis',
        'Els serveis de protecció civil',
        'Els serveis d’inspecció tributària',
        'Els serveis d’emergències mèdiques',
      ],
      correct: 'c',
      whyWrong: {
        a: 'Sí que hi forma part.',
        b: 'Sí que hi forma part.',
        d: 'Sí que hi forma part.',
      },
      explainCa: 'El sistema integra les administracions amb competències en seguretat, els cossos policials, els serveis de prevenció i extinció d’incendis i salvaments, els de protecció civil i els d’emergències mèdiques, a més de la seguretat privada en allò que la llei preveu. La inspecció tributària no hi pertany.',
      explainEs: 'El sistema integra las administraciones con competencias en seguridad, los cuerpos policiales, los servicios de prevención y extinción de incendios y salvamentos, los de protección civil y los de emergencias médicas, además de la seguridad privada en lo que la ley prevé. La inspección tributaria no pertenece a él.',
      refs: [refv('llei-4-2003-seguretat-publica', 'integrants del sistema', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'La coordinació de les policies locals per part de la Generalitat implica que:',
      options: [
        'La Generalitat pot donar ordres operatives directes als agents',
        'S’homogeneïtzen mitjans, formació, uniformitat i criteris, mantenint la dependència municipal',
        'Els ajuntaments perden la titularitat dels seus cossos',
        'Els agents passen a ser personal de la Generalitat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El comandament operatiu correspon a l’estructura municipal.',
        c: 'La titularitat continua sent municipal.',
        d: 'Els agents continuen sent personal de l’ajuntament.',
      },
      explainCa: 'Coordinar significa establir criteris comuns i homogeneïtzar mitjans tècnics, formació, uniformitat i sistemes d’informació, però no substituir la dependència jeràrquica de l’alcalde ni alterar la titularitat municipal del cos.',
      explainEs: 'Coordinar significa establecer criterios comunes y homogeneizar medios técnicos, formación, uniformidad y sistemas de información, pero no sustituir la dependencia jerárquica del alcalde ni alterar la titularidad municipal del cuerpo.',
      refs: [
        refv('llei-4-2003-seguretat-publica', 'coordinació de policies locals', '2026-08-24'),
        refv('llei-16-1991-policies-locals', 'dependència municipal', '2026-08-24'),
      ],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(23, [
    {
      n: 1,
      stem: 'Qui presideix la junta local de seguretat?',
      options: [
        'El cap de la policia local',
        'L’alcalde o alcaldessa',
        'El representant del Govern de la Generalitat al territori',
        'El comandament dels Mossos d’Esquadra de l’àrea bàsica policial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Hi participa com a cap del cos, però no la presideix.',
        c: 'Hi participa en representació de la Generalitat.',
        d: 'Hi participa com a comandament policial.',
      },
      explainCa: 'La junta local de seguretat és un òrgan col·legiat presidit per l’alcalde o alcaldessa del municipi, on s’articula la coordinació entre l’ajuntament, els Mossos d’Esquadra i la policia local.',
      explainEs: 'La junta local de seguridad es un órgano colegiado presidido por el alcalde o alcaldesa del municipio, donde se articula la coordinación entre el ayuntamiento, los Mossos d’Esquadra y la policía local.',
      refs: [refv('decret-151-1998-juntes', 'composició i presidència', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'En quins municipis és obligatòria la constitució d’una junta local de seguretat?',
      options: [
        'En tots els municipis de Catalunya',
        'En els municipis que disposen de cos de policia local propi',
        'Només en municipis de més de 50.000 habitants',
        'Només en capitals de comarca',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No és obligatòria en municipis sense cos propi, tot i que se’n poden constituir.',
        c: 'El criteri no és poblacional.',
        d: 'El criteri no és la capitalitat comarcal.',
      },
      explainCa: 'La constitució de la junta local de seguretat és obligatòria en els municipis que tenen cos de policia local propi, precisament perquè hi conflueixen dos cossos policials que cal coordinar. Roses hi entra plenament.',
      explainEs: 'La constitución de la junta local de seguridad es obligatoria en los municipios que tienen cuerpo de policía local propio, precisamente porque en ellos confluyen dos cuerpos policiales que hay que coordinar. Roses entra plenamente.',
      refs: [refv('llei-4-2003-seguretat-publica', 'art. 9.1', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Quina d’aquestes és una funció pròpia de la junta local de seguretat?',
      options: [
        'Dirigir en temps real els dispositius operatius',
        'Analitzar la situació de seguretat, aprovar el pla local de seguretat i fixar criteris de coordinació',
        'Instruir els expedients disciplinaris dels agents',
        'Resoldre els recursos contra les sancions de trànsit',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La direcció operativa correspon als comandaments dels cossos.',
        c: 'Correspon als òrgans competents en matèria de personal.',
        d: 'Correspon a l’òrgan municipal competent en matèria sancionadora.',
      },
      explainCa: 'La junta local de seguretat analitza i valora la situació de seguretat del municipi, elabora i aprova el pla local de seguretat i en fa el seguiment, i estableix els criteris de coordinació i col·laboració entre els cossos que hi actuen.',
      explainEs: 'La junta local de seguridad analiza y valora la situación de seguridad del municipio, elabora y aprueba el plan local de seguridad y hace su seguimiento, y establece los criterios de coordinación y colaboración entre los cuerpos que actúan.',
      refs: [
        refv(
          'decret-151-1998-juntes',
          'art. 2',
          '2026-08-24',
          'L’art. 2.b) diu «elaborar» plans; aprovar-los és de la Llei 4/2003, art. 10.b.',
        ),
        refv('llei-4-2003-seguretat-publica', 'art. 10.b', '2026-08-24'),
      ],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quina norma regula específicament les juntes locals de seguretat a Catalunya?',
      options: [
        'El Decret 151/1998, de 23 de juny',
        'El Decret 179/2015, de 4 d’agost',
        'La Llei 16/1991, de 10 de juliol',
        'La Llei orgànica 4/2015, de 30 de març',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Regula el procediment disciplinari de les policies locals.',
        c: 'Regula les policies locals, però no específicament les juntes.',
        d: 'Regula la protecció de la seguretat ciutadana a escala estatal.',
      },
      explainCa: 'El Decret 151/1998, de 23 de juny, regula les juntes locals de seguretat, desenvolupant les previsions de la legislació catalana en matèria de seguretat pública.',
      explainEs: 'El Decreto 151/1998, de 23 de junio, regula las juntas locales de seguridad, desarrollando las previsiones de la legislación catalana en materia de seguridad pública.',
      refs: [refv('decret-151-1998-juntes', 'norma reguladora', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Un dispositiu conjunt entre policia local i Mossos d’Esquadra per a la Festa Major de Roses:',
      options: [
        'L’ha d’autoritzar el Departament d’Interior cas per cas',
        'Es prepara i s’acorda en el marc de la junta local de seguretat',
        'Només el pot ordenar el jutjat de guàrdia',
        'No és possible perquè cada cos actua per separat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No cal autorització departamental per a cada dispositiu.',
        c: 'El jutjat no dirigeix dispositius preventius de seguretat.',
        d: 'La col·laboració entre cossos és precisament un mandat legal.',
      },
      explainCa: 'La junta local de seguretat és el lloc natural on es planifiquen i s’acorden els dispositius conjunts per a esdeveniments singulars: qui cobreix cada zona, amb quins efectius i sota quin comandament.',
      explainEs: 'La junta local de seguridad es el lugar natural donde se planifican y acuerdan los dispositivos conjuntos para eventos singulares: quién cubre cada zona, con qué efectivos y bajo qué mando.',
      refs: [refv('decret-151-1998-juntes', 'coordinació de dispositius', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(24, [
    {
      n: 1,
      stem: 'Els cossos de policia local de Catalunya són:',
      options: [
        'Instituts armats de naturalesa militar',
        'Instituts armats de naturalesa civil amb estructura i organització jerarquitzada',
        'Cossos administratius sense caràcter armat',
        'Serveis municipals de vigilància sense condició de força de seguretat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La naturalesa militar correspon a la Guàrdia Civil.',
        c: 'Són instituts armats.',
        d: 'Són forces i cossos de seguretat a tots els efectes.',
      },
      explainCa: 'La Llei 16/1991 configura els cossos de policia local com a instituts armats de naturalesa civil, amb estructura i organització jerarquitzada, que depenen de l’alcalde o alcaldessa.',
      explainEs: 'La Ley 16/1991 configura los cuerpos de policía local como institutos armados de naturaleza civil, con estructura y organización jerarquizada, que dependen del alcalde o alcaldesa.',
      refs: [refv('llei-16-1991-policies-locals', 'naturalesa dels cossos', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'A quina escala pertany la categoria d’agent de policia local?',
      options: ['Escala superior', 'Escala executiva', 'Escala intermèdia', 'Escala bàsica'],
      correct: 'd',
      whyWrong: {
        a: "L'escala superior agrupa les categories d’intendent i superiors.",
        b: 'L’escala executiva agrupa sotsinspector i inspector.',
        c: 'L’escala intermèdia agrupa caporal i sergent.',
      },
      explainCa: 'L’escala bàsica correspon a la categoria d’agent, que és la porta d’entrada al cos i la que convoca l’Ajuntament de Roses. Per damunt hi ha l’escala intermèdia, l’executiva i la superior.',
      explainEs: 'La escala básica corresponde a la categoría de agente, que es la puerta de entrada al cuerpo y la que convoca el Ayuntamiento de Roses. Por encima están la escala intermedia, la ejecutiva y la superior.',
      refs: [
        refv('llei-16-1991-policies-locals', 'art. 24.1.d i 24.2.d', '2026-08-24'),
        refv(
          'roses-bases-2026-interins',
          'capçalera de la convocatòria',
          '2026-08-24',
          'Prova que la categoria convocada és agent, grup C1; l’escala és de la Llei 16/1991.',
        ),
      ],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'L’àmbit territorial d’actuació de la policia local és:',
      options: [
        'Tota la comarca de l’Alt Empordà',
        'El terme municipal, llevat dels supòsits previstos legalment',
        'Tot Catalunya quan hi ha requeriment',
        'La província de Girona',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La comarca no és l’àmbit d’actuació ordinari.',
        c: 'Només en supòsits taxats es pot actuar fora del terme.',
        d: 'La província no és l’àmbit d’actuació.',
      },
      explainCa: 'Els cossos de policia local només poden actuar dins el terme municipal, excepte en situacions d’emergència, quan exerceixen funcions de protecció d’autoritats de la corporació fora del terme, o quan una norma o un acord de col·laboració ho preveu expressament.',
      explainEs: 'Los cuerpos de policía local solo pueden actuar dentro del término municipal, salvo en situaciones de emergencia, cuando ejercen funciones de protección de autoridades de la corporación fuera del término, o cuando una norma o un acuerdo de colaboración lo prevé expresamente.',
      refs: [refv('llei-16-1991-policies-locals', 'àmbit territorial', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'De qui depèn jeràrquicament el cos de la Policia Local de Roses?',
      options: [
        'Del Departament d’Interior de la Generalitat',
        'De l’alcalde o alcaldessa de Roses',
        'De la Delegació del Govern a Catalunya',
        'Del Consell Comarcal de l’Alt Empordà',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La Generalitat coordina, però no exerceix el comandament jeràrquic.',
        c: 'No té comandament sobre policies locals.',
        d: 'El consell comarcal no té competències policials.',
      },
      explainCa: 'L’alcalde o alcaldessa és el cap superior del cos de policia local i n’exerceix la direcció, sens perjudici de les funcions de coordinació que corresponen a la Generalitat i de la dependència funcional dels jutges i del Ministeri Fiscal en funcions de policia judicial.',
      explainEs: 'El alcalde o alcaldesa es el jefe superior del cuerpo de policía local y ejerce su dirección, sin perjuicio de las funciones de coordinación que corresponden a la Generalitat y de la dependencia funcional de los jueces y del Ministerio Fiscal en funciones de policía judicial.',
      refs: [refv('llei-16-1991-policies-locals', 'preàmbul III', '2026-08-24'), refv('llei-7-1985-lrbrl', 'art. 21.1.i', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'Quan estudiïs la Llei 16/1991, per què cal treballar sobre el text consolidat?',
      options: [
        'Perquè el text original està en castellà',
        'Perquè ha estat modificada diverses vegades, entre altres per la Llei 3/2023',
        'Perquè el text original no es va publicar mai',
        'Perquè la llei caduca cada deu anys',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El text original està publicat en català al DOGC.',
        c: 'Es va publicar correctament el 1991.',
        d: 'Les lleis no caduquen automàticament.',
      },
      explainCa: 'La Llei 16/1991 ha estat modificada en diverses ocasions al llarg dels anys, entre altres per la Llei 3/2023. Estudiar apunts antics sobre categories, requisits d’accés o segona activitat és una font habitual d’errors a l’examen.',
      explainEs: 'La Ley 16/1991 ha sido modificada en varias ocasiones a lo largo de los años, entre otras por la Ley 3/2023. Estudiar apuntes antiguos sobre categorías, requisitos de acceso o segunda actividad es una fuente habitual de errores en el examen.',
      refs: [refv('llei-16-1991-policies-locals', 'text consolidat i modificacions', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(25, [
    {
      n: 1,
      stem: 'Quants articles té la Declaració Universal dels Drets Humans?',
      options: ['21 articles', '30 articles', '54 articles', '169 articles'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon a cap dada de la Declaració.',
        c: '54 és el nombre d’articles de la Carta de Drets Fonamentals de la UE.',
        d: '169 és el nombre d’articles de la Constitució espanyola.',
      },
      explainCa: 'La Declaració Universal dels Drets Humans consta d’un preàmbul i trenta articles. Va ser adoptada i proclamada per l’Assemblea General de les Nacions Unides el 10 de desembre de 1948.',
      explainEs: 'La Declaración Universal de los Derechos Humanos consta de un preámbulo y treinta artículos. Fue adoptada y proclamada por la Asamblea General de las Naciones Unidas el 10 de diciembre de 1948.',
      refs: [refv('ddhh-1948', 'preàmbul i art. 1 a 30', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'La Carta de Drets Fonamentals de la Unió Europea té el mateix valor jurídic que els Tractats des de:',
      options: [
        'La seva proclamació a Niça l’any 2000',
        'L’entrada en vigor del Tractat de Lisboa el 2009',
        'El Tractat de Maastricht de 1992',
        'L’adhesió d’Espanya a la Comunitat Europea el 1986',
      ],
      correct: 'b',
      whyWrong: {
        a: 'En proclamar-se el 2000 no tenia caràcter jurídicament vinculant.',
        c: 'La Carta encara no existia.',
        d: 'La Carta encara no existia.',
      },
      explainCa: 'La Carta es va proclamar solemnement a Niça l’any 2000 sense caràcter vinculant. L’entrada en vigor del Tractat de Lisboa, el 2009, li va reconèixer el mateix valor jurídic que els Tractats.',
      explainEs: 'La Carta se proclamó solemnemente en Niza en el año 2000 sin carácter vinculante. La entrada en vigor del Tratado de Lisboa, en 2009, le reconoció el mismo valor jurídico que los Tratados.',
      refs: [refv('carta-drets-ue', 'valor jurídic i proclamació', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'El Codi d’ètica de la Policia de Catalunya va ser aprovat per:',
      options: [
        'La Llei 16/1991, de les policies locals',
        'L’Acord GOV/25/2015, de 24 de febrer',
        'El Decret 179/2015, de 4 d’agost',
        'La Llei 4/2003, del sistema de seguretat pública',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Regula les policies locals, no el codi ètic.',
        c: 'Aprova el reglament disciplinari.',
        d: 'Ordena el sistema de seguretat pública.',
      },
      explainCa: 'El Codi d’ètica de la Policia de Catalunya va ser aprovat per l’Acord GOV/25/2015, de 24 de febrer, i s’aplica als Mossos d’Esquadra i a les policies locals, que en poden desenvolupar codis propis.',
      explainEs: 'El Código de ética de la Policía de Cataluña fue aprobado por el Acuerdo GOV/25/2015, de 24 de febrero, y se aplica a los Mossos d’Esquadra y a las policías locales, que pueden desarrollar códigos propios.',
      refs: [refv('codi-etic-policia-catalunya', 'Acord GOV/25/2015', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quina diferència jurídica hi ha entre la Declaració Universal i la Carta de Drets Fonamentals de la UE?',
      options: [
        'Cap: totes dues són tractats vinculants',
        'La Declaració no és un tractat vinculant per si mateixa; la Carta sí que té valor jurídic vinculant',
        'La Carta és una declaració política sense efectes',
        'La Declaració vincula els estats i la Carta no',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La Declaració és una resolució de l’Assemblea General, no un tractat.',
        c: 'La Carta té valor equivalent als Tractats.',
        d: 'Inverteix exactament els termes.',
      },
      explainCa: 'La Declaració Universal és una resolució de l’Assemblea General de les Nacions Unides: té una enorme força moral i ha inspirat el dret internacional posterior, però no és per si mateixa un tractat vinculant. La Carta de la UE, en canvi, té el mateix valor jurídic que els Tractats.',
      explainEs: 'La Declaración Universal es una resolución de la Asamblea General de las Naciones Unidas: tiene una enorme fuerza moral y ha inspirado el derecho internacional posterior, pero no es por sí misma un tratado vinculante. La Carta de la UE, en cambio, tiene el mismo valor jurídico que los Tratados.',
      refs: [refv('ddhh-1948', 'naturalesa jurídica', '2026-08-24'), refv('carta-drets-ue', 'valor jurídic', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Un company t’explica que ha «arreglat» una denúncia a un conegut. Segons els principis ètics i deontològics, això és:',
      options: [
        'Una qüestió privada entre companys',
        'Un tracte de favor prohibit que pot constituir falta disciplinària i, segons el cas, delicte',
        'Una pràctica admissible si no hi ha perjudici econòmic',
        'Una decisió discrecional emparada pel principi d’oportunitat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Afecta l’exercici de la funció pública, no és un assumpte privat.',
        c: 'El perjudici econòmic no és el criteri de licitud.',
        d: 'El principi d’oportunitat no permet afavorir persones concretes.',
      },
      explainCa: 'Els principis ètics prohibeixen expressament acceptar o atorgar tractes de favor. Alterar o suprimir una denúncia legítima pot ser una falta disciplinària molt greu i, segons les circumstàncies, un delicte de prevaricació o de falsedat documental.',
      explainEs: 'Los principios éticos prohíben expresamente aceptar u otorgar tratos de favor. Alterar o suprimir una denuncia legítima puede ser una falta disciplinaria muy grave y, según las circunstancias, un delito de prevaricación o de falsedad documental.',
      refs: [
        refv('codi-etic-policia-catalunya', 'integritat i imparcialitat', '2026-08-24', 'Integritat i imparcialitat; la qualificació penal no surt del Codi d’ètica.'),
        refv('rdleg-5-2015-trebep', 'art. 53', '2026-08-24', 'L’art. 53.7 prohibeix el tracte de favor; la qualificació penal no surt del TREBEP.'),
        refv('lo-10-1995-cp', 'art. 404 i 390', '2026-08-24'),
      ],
      difficulty: 'mitjana',
    },
  ]),
]
