import type { Question } from '../../../schemas/index.ts'
import { questionsFor, ref } from '../authoring.ts'

export const QUESTIONS_31_36: Question[] = [
  ...questionsFor(31, [
    {
      n: 1,
      stem: 'A quina comarca pertany el municipi de Roses?',
      options: ['El Baix Empordà', "L'Alt Empordà", 'El Gironès', 'La Selva'],
      correct: 'b',
      whyWrong: {
        a: 'És la comarca veïna al sud, amb capital a la Bisbal d’Empordà.',
        c: 'És la comarca de la ciutat de Girona.',
        d: 'És una comarca del sud de la província.',
      },
      explainCa: 'Roses és un municipi de la comarca de l’Alt Empordà, a la província de Girona, situat a l’extrem nord del golf de Roses, a la Costa Brava. La capital comarcal és Figueres.',
      explainEs: 'Roses es un municipio de la comarca del Alt Empordà, en la provincia de Girona, situado en el extremo norte del golfo de Roses, en la Costa Brava. La capital comarcal es Figueres.',
      refs: [ref('roses-web-municipi', 'situació geogràfica del municipi')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Entre quins dos parcs naturals se situa el terme municipal de Roses?',
      options: [
        'Cap de Creus i Aiguamolls de l’Empordà',
        'Montseny i Cadí-Moixeró',
        'Delta de l’Ebre i els Ports',
        'Garrotxa i Montgrí',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Són parcs de l’interior de Catalunya.',
        c: 'Són parcs de les Terres de l’Ebre.',
        d: 'Són parcs propers però no els que limiten Roses.',
      },
      explainCa: 'El terme de Roses queda encaixat entre el Parc Natural de Cap de Creus, al nord i a l’est, i el Parc Natural dels Aiguamolls de l’Empordà, al sud. Aquesta situació condiciona molt l’activitat policial: costa esquerpa amb cales de difícil accés i zona humida protegida.',
      explainEs: 'El término de Roses queda encajado entre el Parque Natural de Cap de Creus, al norte y al este, y el Parque Natural de los Aiguamolls de l’Empordà, al sur. Esta situación condiciona mucho la actividad policial: costa abrupta con calas de difícil acceso y zona húmeda protegida.',
      refs: [ref('roses-web-municipi', 'entorn natural del municipi')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'Quina colònia grega es va establir al lloc on avui hi ha la Ciutadella de Roses?',
      options: ['Empòrion', 'Rhode', 'Tarraco', 'Barcino'],
      correct: 'b',
      whyWrong: {
        a: 'Empòrion és la colònia grega de l’Escala, a l’altre extrem del golf.',
        c: 'Tarraco és l’actual Tarragona, d’origen romà.',
        d: 'Barcino és l’actual Barcelona, d’origen romà.',
      },
      explainCa: 'La Ciutadella de Roses conserva al seu interior les restes de la colònia grega de Rhode, que dona nom al municipi, juntament amb la vil·la romana, el monestir romànic de Santa Maria i la vila medieval.',
      explainEs: 'La Ciutadella de Roses conserva en su interior los restos de la colonia griega de Rhode, que da nombre al municipio, junto con la villa romana, el monasterio románico de Santa María y la villa medieval.',
      refs: [ref('roses-web-municipi', 'patrimoni històric: Ciutadella')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'El Castell de la Trinitat de Roses va ser manat construir per:',
      options: [
        'Jaume I el Conqueridor',
        'L’emperador Carles V',
        'Felip V',
        'El comte Ramon Berenguer IV',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És un monarca del segle XIII, molt anterior.',
        c: 'Va regnar al segle XVIII, molt posterior a la construcció.',
        d: 'És un comte del segle XII.',
      },
      explainCa: 'El Castell de la Trinitat, situat sobre la badia, va ser manat construir per l’emperador Carles V l’any 1543 com a part del sistema defensiu de la badia, juntament amb la Ciutadella. El seu nom prové d’una capella anterior de 1508.',
      explainEs: 'El Castell de la Trinitat, situado sobre la bahía, fue mandado construir por el emperador Carlos V en 1543 como parte del sistema defensivo de la bahía, junto con la Ciutadella. Su nombre proviene de una capilla anterior de 1508.',
      refs: [ref('roses-web-municipi', 'patrimoni històric: Castell de la Trinitat')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'El dolmen de la Creu d’en Cobertella, situat al terme de Roses, destaca perquè:',
      options: [
        'És l’únic dolmen de la Costa Brava',
        'És el dolmen més gran de Catalunya',
        'És d’època romana',
        'Es va traslladar des d’un altre municipi',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’Alt Empordà conserva desenes de monuments megalítics.',
        c: 'És un monument megalític, molt anterior a l’època romana.',
        d: 'Es conserva al seu emplaçament original.',
      },
      explainCa: 'El dolmen de la Creu d’en Cobertella, al terme de Roses, és el sepulcre megalític més gran de Catalunya i forma part d’un conjunt megalític molt ric a la zona de Cap de Creus i l’Alt Empordà.',
      explainEs: 'El dolmen de la Creu d’en Cobertella, en el término de Roses, es el sepulcro megalítico más grande de Cataluña y forma parte de un conjunto megalítico muy rico en la zona de Cap de Creus y el Alt Empordà.',
      refs: [ref('roses-web-municipi', 'patrimoni megalític del municipi')],
      difficulty: 'mitjana',
    },
    {
      n: 6,
      stem: 'A quina cala del terme municipal de Roses hi havia el restaurant elBulli?',
      options: ['Cala Canyelles Petites', 'Cala Montjoi', 'Cala Rostella', 'L’Almadrava'],
      correct: 'b',
      whyWrong: {
        a: 'És una altra cala del terme, però no la del restaurant.',
        c: 'És una altra cala del terme, però no la del restaurant.',
        d: 'És una altra cala del terme, però no la del restaurant.',
      },
      explainCa: 'El restaurant elBulli, dirigit per Ferran Adrià, es trobava a Cala Montjoi, dins el terme municipal de Roses. És un dels elements més coneguts internacionalment del municipi.',
      explainEs: 'El restaurante elBulli, dirigido por Ferran Adrià, se encontraba en Cala Montjoi, dentro del término municipal de Roses. Es uno de los elementos más conocidos internacionalmente del municipio.',
      refs: [ref('roses-web-municipi', 'cales i entorn del municipi')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(32, [
    {
      n: 1,
      stem: 'Quina diferència hi ha entre immobilització i retirada d’un vehicle?',
      options: [
        'Cap: són termes equivalents',
        'La immobilització deixa el vehicle al lloc sense poder circular; la retirada el trasllada al dipòsit',
        'La immobilització només s’aplica a motocicletes',
        'La retirada només la pot ordenar un jutge',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Tenen causes i efectes clarament diferents.',
        c: 'S’aplica a qualsevol classe de vehicle.',
        d: 'L’ordena l’autoritat administrativa competent en matèria de trànsit.',
      },
      explainCa: 'La immobilització manté el vehicle al lloc on es troba fins que desapareix la causa que la va motivar. La retirada comporta el trasllat al dipòsit municipal i només procedeix per les causes taxades que preveu la llei.',
      explainEs: 'La inmovilización mantiene el vehículo en el lugar donde se encuentra hasta que desaparece la causa que la motivó. La retirada comporta el traslado al depósito municipal y solo procede por las causas tasadas que prevé la ley.',
      refs: [ref('rdleg-6-2015-ltsv', 'immobilització i retirada de vehicles')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quan es presumeix que un vehicle està abandonat per romandre al dipòsit?',
      options: [
        'Quan hi ha estat més de quinze dies',
        'Quan hi ha estat més d’un mes',
        'Quan hi ha estat més de dos mesos',
        'Quan hi ha estat més de sis mesos',
      ],
      correct: 'c',
      whyWrong: {
        a: 'No correspon al termini legal.',
        b: 'Un mes és el termini per a un vehicle estacionat a la via pública amb desperfectes.',
        d: 'No correspon al termini legal.',
      },
      explainCa: 'Es presumeix racionalment l’abandonament quan el vehicle roman al dipòsit més de dos mesos, o quan resta estacionat a la via pública durant més d’un mes amb desperfectes que facin impossible el desplaçament pels seus mitjans o li faltin les plaques de matrícula.',
      explainEs: 'Se presume racionalmente el abandono cuando el vehículo permanece en el depósito más de dos meses, o cuando queda estacionado en la vía pública durante más de un mes con desperfectos que hagan imposible su desplazamiento por sus medios o le falten las placas de matrícula.',
      refs: [ref('rdleg-6-2015-ltsv', 'tractament residual del vehicle')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'Quina d’aquestes és causa d’immobilització d’un vehicle?',
      options: [
        'Estar estacionat en una zona blava sense tiquet',
        'Que el conductor superi la taxa d’alcohol permesa o es negui a les proves',
        'Tenir la ITV caducada un sol dia',
        'Circular amb els llums de posició de dia',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Genera denúncia, però no immobilització.',
        c: 'Genera denúncia; la immobilització requereix un supòsit legal específic.',
        d: 'Pot ser infracció lleu, però no causa d’immobilització.',
      },
      explainCa: 'Entre les causes d’immobilització hi ha que el conductor superi les taxes d’alcohol o presenti signes de consum de drogues, que es negui a sotmetre’s a les proves, que el vehicle no disposi de l’assegurança obligatòria, o que superi els límits de càrrega o pes autoritzats.',
      explainEs: 'Entre las causas de inmovilización están que el conductor supere las tasas de alcohol o presente signos de consumo de drogas, que se niegue a someterse a las pruebas, que el vehículo carezca del seguro obligatorio, o que supere los límites de carga o peso autorizados.',
      refs: [ref('rdleg-6-2015-ltsv', 'causes d’immobilització')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Un vehicle estacionat de manera incorrecta però sense crear cap perill ni obstaculitzar res:',
      options: [
        'Sempre es pot retirar amb la grua',
        'No es pot retirar: cal que concorri una de les causes taxades de retirada',
        'S’ha d’immobilitzar obligatòriament',
        'S’ha de deixar sense denunciar',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La retirada no és una conseqüència automàtica de qualsevol infracció d’estacionament.',
        c: 'La immobilització té causes pròpies i diferents.',
        d: 'La infracció es pot denunciar igualment.',
      },
      explainCa: 'La retirada exigeix una causa taxada: perill, pertorbació greu de la circulació o del funcionament d’un servei públic, obstaculització de sortides o passos, ocupació d’espais reservats. Si no en concorre cap, es denuncia la infracció però no es pot retirar el vehicle ni repercutir-ne les despeses.',
      explainEs: 'La retirada exige una causa tasada: peligro, perturbación grave de la circulación o del funcionamiento de un servicio público, obstaculización de salidas o pasos, ocupación de espacios reservados. Si no concurre ninguna, se denuncia la infracción pero no se puede retirar el vehículo ni repercutir sus gastos.',
      refs: [ref('rdleg-6-2015-ltsv', 'causes de retirada de vehicles')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Quin permís habilita per conduir turismes?',
      options: ['El permís A', 'El permís B', 'El permís C1', 'La llicència LCC'],
      correct: 'b',
      whyWrong: {
        a: 'Habilita per conduir motocicletes sense limitació de potència.',
        c: 'Habilita per conduir camions dins uns límits de massa.',
        d: 'És una llicència per a ciclomotors de tres rodes i quadricicles lleugers.',
      },
      explainCa: 'El permís de la classe B habilita per conduir automòbils la massa màxima autoritzada dels quals no excedeixi els límits reglamentaris i estiguin dissenyats per transportar un nombre limitat de persones a més del conductor, és a dir, els turismes.',
      explainEs: 'El permiso de la clase B habilita para conducir automóviles cuya masa máxima autorizada no exceda los límites reglamentarios y estén diseñados para transportar un número limitado de personas además del conductor, es decir, los turismos.',
      refs: [ref('rd-818-2009-rgcond', 'classes de permisos de conducció')],
      difficulty: 'facil',
    },
  ]),

  ...questionsFor(33, [
    {
      n: 1,
      stem: 'Quina taxa d’alcohol en aire espirat converteix la conducta en delicte contra la seguretat viària?',
      options: [
        'Superior a 0,25 mg/l',
        'Superior a 0,50 mg/l',
        'Superior a 0,60 mg/l',
        'Superior a 0,80 mg/l',
      ],
      correct: 'c',
      whyWrong: {
        a: 'És el llindar administratiu general.',
        b: 'No correspon a cap llindar legal en aire espirat.',
        d: 'No correspon al llindar penal.',
      },
      explainCa: 'El Codi penal estableix que en tot cas serà condemnat qui condueixi amb una taxa d’alcohol en aire espirat superior a 0,60 mil·ligrams per litre o amb una taxa d’alcohol en sang superior a 1,2 grams per litre.',
      explainEs: 'El Código penal establece que en todo caso será condenado quien conduzca con una tasa de alcohol en aire espirado superior a 0,60 miligramos por litro o con una tasa de alcohol en sangre superior a 1,2 gramos por litro.',
      refs: [ref('lo-10-1995-cp', 'art. 379.2')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quina és la taxa màxima d’alcohol en aire espirat per a un conductor novell o professional?',
      options: ['0,10 mg/l', '0,15 mg/l', '0,25 mg/l', '0,30 mg/l'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon a cap llindar legal.',
        c: 'És el llindar per als conductors en general.',
        d: '0,30 g/l és el llindar en sang per a aquest col·lectiu, no en aire espirat.',
      },
      explainCa: 'Els conductors novells —durant els dos anys següents a l’obtenció del permís— i els professionals no poden superar una taxa de 0,15 mil·ligrams per litre en aire espirat, o 0,3 grams per litre en sang. Per a la resta de conductors el límit és 0,25 mg/l i 0,5 g/l.',
      explainEs: 'Los conductores noveles —durante los dos años siguientes a la obtención del permiso— y los profesionales no pueden superar una tasa de 0,15 miligramos por litro en aire espirado, o 0,3 gramos por litro en sangre. Para el resto de conductores el límite es 0,25 mg/l y 0,5 g/l.',
      refs: [ref('rd-1428-2003-rgc', 'taxes d’alcoholèmia')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'La pràctica de la prova d’alcoholèmia amb etilòmetre exigeix:',
      options: [
        'Una única determinació',
        'Dues determinacions successives amb un interval mínim de deu minuts',
        'Tres determinacions consecutives',
        'Una determinació i un anàlisi de sang obligatori',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La norma exigeix dues determinacions.',
        c: 'La norma no n’exigeix tres.',
        d: 'L’anàlisi de sang és un dret de contrast de la persona interessada, no un tràmit obligatori.',
      },
      explainCa: 'La prova consisteix en dues determinacions successives amb un etilòmetre homologat, separades per un interval mínim de deu minuts. La persona interessada té dret a contrastar el resultat mitjançant anàlisi de sang, amb les despeses al seu càrrec si es confirma la infracció.',
      explainEs: 'La prueba consiste en dos determinaciones sucesivas con un etilómetro homologado, separadas por un intervalo mínimo de diez minutos. La persona interesada tiene derecho a contrastar el resultado mediante análisis de sangre, con los gastos a su cargo si se confirma la infracción.',
      refs: [ref('rd-1428-2003-rgc', 'pràctica de les proves de detecció alcohòlica')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'Qui està obligat a sotmetre’s a les proves de detecció d’alcohol o drogues?',
      options: [
        'Només qui condueixi de manera manifestament irregular',
        'Els conductors, els implicats com a possibles responsables en un accident, qui presenti símptomes i qui hagi comès una infracció',
        'Només els conductors professionals',
        'Només qui hagi provocat danys personals',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’obligació és molt més àmplia.',
        c: 'Afecta tots els conductors.',
        d: 'No cal cap resultat lesiu.',
      },
      explainCa: 'Estan obligats a sotmetre’s a les proves els conductors de vehicles, les persones implicades directament com a possibles responsables en un accident de circulació, qui presenti símptomes evidents o un comportament que faci presumir la influència de begudes o drogues, i qui hagi comès una infracció de trànsit, a més dels controls preventius reglamentaris.',
      explainEs: 'Están obligados a someterse a las pruebas los conductores de vehículos, las personas implicadas directamente como posibles responsables en un accidente de circulación, quien presente síntomas evidentes o un comportamiento que haga presumir la influencia de bebidas o drogas, y quien haya cometido una infracción de tráfico, además de los controles preventivos reglamentarios.',
      refs: [ref('rdleg-6-2015-ltsv', 'obligació de sotmetre’s a les proves')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'En matèria de drogues al volant, la regla general és que:',
      options: [
        'Hi ha una taxa permesa equivalent a la de l’alcohol',
        'La infracció és conduir amb presència de drogues a l’organisme, amb l’excepció de les prescrites terapèuticament',
        'Només és infracció si es demostra afectació de la capacitat de conduir',
        'Només s’aplica als conductors professionals',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No existeix cap taxa permesa per a drogues.',
        c: 'La presència, per si mateixa, ja constitueix la infracció administrativa.',
        d: 'S’aplica a tots els conductors.',
      },
      explainCa: 'A diferència de l’alcohol, en drogues no hi ha taxa permesa: la infracció administrativa és conduir amb presència de drogues a l’organisme. S’exclouen les substàncies utilitzades sota prescripció facultativa i amb una finalitat terapèutica, sempre que no afectin la capacitat de conduir.',
      explainEs: 'A diferencia del alcohol, en drogas no hay tasa permitida: la infracción administrativa es conducir con presencia de drogas en el organismo. Se excluyen las sustancias utilizadas bajo prescripción facultativa y con una finalidad terapéutica, siempre que no afecten a la capacidad de conducir.',
      refs: [ref('rdleg-6-2015-ltsv', 'presència de drogues en l’organisme')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(34, [
    {
      n: 1,
      stem: 'Quines vies hi ha perquè un gos sigui considerat potencialment perillós?',
      options: [
        'Únicament pertànyer a una raça de la llista',
        'Per raça o encreuament, per episodis d’agressió previs i per ensinistrament per a l’atac i la defensa',
        'Únicament el pes de l’animal',
        'Només per decisió judicial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La raça és només una de les vies.',
        c: 'El pes és un dels indicadors físics, però no l’únic criteri.',
        d: 'La qualificació és administrativa, no judicial.',
      },
      explainCa: 'Un gos pot ser considerat potencialment perillós per pertànyer a una raça de la llista o ser-ne un encreuament, per haver tingut episodis d’agressions a persones o a altres gossos, o per haver estat ensinistrat per a l’atac i la defensa. També s’hi inclouen exemplars amb determinades característiques físiques.',
      explainEs: 'Un perro puede ser considerado potencialmente peligroso por pertenecer a una raza de la lista o ser un cruce, por haber tenido episodios de agresiones a personas o a otros perros, o por haber sido adiestrado para el ataque y la defensa. También se incluyen ejemplares con determinadas características físicas.',
      refs: [ref('llei-50-1999-app', 'concepte'), ref('llei-10-1999-gossos-cat', 'gossos considerats potencialment perillosos')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Qui atorga la llicència per a la tinença de gossos potencialment perillosos?',
      options: [
        'El Departament d’Interior de la Generalitat',
        'L’ajuntament del municipi de residència de la persona sol·licitant',
        'El col·legi de veterinaris',
        'La Delegació del Govern',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No té atribuïda aquesta competència.',
        c: 'Intervé en la identificació i els certificats, però no atorga la llicència.',
        d: 'No té aquesta competència.',
      },
      explainCa: 'La llicència administrativa per a la tinença d’animals potencialment perillosos l’atorga l’ajuntament del municipi de residència de la persona sol·licitant. A Roses és un tràmit municipal específic.',
      explainEs: 'La licencia administrativa para la tenencia de animales potencialmente peligrosos la otorga el ayuntamiento del municipio de residencia de la persona solicitante. En Roses es un trámite municipal específico.',
      refs: [ref('llei-50-1999-app', 'llicència administrativa'), ref('roses-tramits-animals', 'tràmit municipal a Roses')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'Quin d’aquests NO és un requisit per obtenir la llicència de tinença d’un gos potencialment perillós?',
      options: [
        'Ser major d’edat',
        'Disposar d’una assegurança de responsabilitat civil per danys a tercers',
        'Acreditar una formació prèvia com a ensinistrador caní',
        'Acreditar capacitat física i aptitud psicològica',
      ],
      correct: 'c',
      whyWrong: {
        a: 'Sí que és un requisit legal.',
        b: 'Sí que és un requisit legal.',
        d: 'Sí que és un requisit legal.',
      },
      explainCa: 'Els requisits són ser major d’edat, no haver estat condemnat per determinats delictes ni sancionat per infraccions greus o molt greus en la matèria, acreditar capacitat física i aptitud psicològica mitjançant certificat, i disposar d’una assegurança de responsabilitat civil per danys a tercers. No s’exigeix formació com a ensinistrador.',
      explainEs: 'Los requisitos son ser mayor de edad, no haber sido condenado por determinados delitos ni sancionado por infracciones graves o muy graves en la materia, acreditar capacidad física y aptitud psicológica mediante certificado, y disponer de un seguro de responsabilidad civil por daños a terceros. No se exige formación como adiestrador.',
      refs: [ref('llei-50-1999-app', 'requisits de la llicència'), ref('rd-287-2002-app', 'desenvolupament reglamentari')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'A la via pública, un gos potencialment perillós ha d’anar:',
      options: [
        'Solt però sota control visual',
        'Lligat amb corretja no extensible de longitud limitada i amb morrió',
        'Amb morrió però sense corretja',
        'Amb corretja extensible de fins a cinc metres',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La normativa exigeix expressament corretja i morrió.',
        c: 'Falta l’obligació de portar-lo lligat.',
        d: 'La corretja ha de ser no extensible i de longitud limitada.',
      },
      explainCa: 'A les vies públiques i als espais d’ús públic, el gos ha de portar obligatòriament morrió adequat a la seva raça i anar subjecte amb una cadena o corretja no extensible de longitud limitada. A més, una persona no pot conduir més d’un gos potencialment perillós alhora.',
      explainEs: 'En las vías públicas y en los espacios de uso público, el perro debe llevar obligatoriamente bozal adecuado a su raza e ir sujeto con una cadena o correa no extensible de longitud limitada. Además, una persona no puede conducir más de un perro potencialmente peligroso a la vez.',
      refs: [ref('rd-287-2002-app', 'mesures de seguretat a la via pública')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'La identificació per microxip i la inscripció al registre censal municipal són obligatòries per a:',
      options: [
        'Només els gossos potencialment perillosos',
        'Tots els gossos',
        'Només els gossos de més de deu quilos',
        'Només els gossos que surten a la via pública',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llicència és exclusiva dels potencialment perillosos, però la identificació i el cens no.',
        c: 'El pes no és el criteri.',
        d: 'L’obligació no depèn de l’ús que se’n faci.',
      },
      explainCa: 'La identificació mitjançant microxip i la inscripció al registre censal municipal són obligatòries per a tots els gossos. El que és exclusiu dels gossos potencialment perillosos és la llicència administrativa i la inscripció al registre específic.',
      explainEs: 'La identificación mediante microchip y la inscripción en el registro censal municipal son obligatorias para todos los perros. Lo que es exclusivo de los perros potencialmente peligrosos es la licencia administrativa y la inscripción en el registro específico.',
      refs: [
        ref('llei-10-1999-gossos-cat', 'identificació i registre'),
        ref('llei-7-2023-benestar-animal', 'obligacions generals de les persones titulars'),
      ],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(35, [
    {
      n: 1,
      stem: 'Quina d’aquestes competències en matèria de trànsit correspon als municipis?',
      options: [
        'La regulació del trànsit a les autopistes que travessen el terme',
        'La regulació, ordenació, gestió, vigilància i disciplina del trànsit a les vies urbanes',
        'L’expedició dels permisos de conducció',
        'La matriculació dels vehicles',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Les vies interurbanes són competència d’una altra administració.',
        c: 'Correspon a l’administració competent en trànsit i seguretat viària.',
        d: 'Correspon a l’administració competent en trànsit i seguretat viària.',
      },
      explainCa: 'La llei de trànsit atribueix als municipis la regulació, ordenació, gestió, vigilància i disciplina del trànsit a les vies urbanes de la seva titularitat, mitjançant agents propis, així com la instrucció dels expedients sancionadors corresponents.',
      explainEs: 'La ley de tráfico atribuye a los municipios la regulación, ordenación, gestión, vigilancia y disciplina del tráfico en las vías urbanas de su titularidad, mediante agentes propios, así como la instrucción de los expedientes sancionadores correspondientes.',
      refs: [ref('rdleg-6-2015-ltsv', 'competències dels municipis')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Una ordenança municipal de circulació pot:',
      options: [
        'Establir taxes d’alcoholèmia diferents de les estatals',
        'Concretar l’ordenació del trànsit al terme dins el marc que fixa la llei estatal',
        'Tipificar delictes contra la seguretat viària',
        'Modificar les classes de permisos de conducció',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Les taxes són matèria reservada a la normativa estatal.',
        c: 'La tipificació de delictes és reserva de llei orgànica.',
        d: 'És competència estatal.',
      },
      explainCa: 'L’ordenança municipal de circulació concreta al terme municipal l’ordenació del trànsit, la parada i l’estacionament, els usos especials de la via i el funcionament de la grua i el dipòsit, sempre dins el marc de la legislació estatal de trànsit, que no pot contradir.',
      explainEs: 'La ordenanza municipal de circulación concreta en el término municipal la ordenación del tráfico, la parada y el estacionamiento, los usos especiales de la vía y el funcionamiento de la grúa y el depósito, siempre dentro del marco de la legislación estatal de tráfico, que no puede contradecir.',
      refs: [
        ref('roses-ordenanca-circulacio', 'objecte i àmbit', 'Pendent de descàrrega: cal contrastar l’articulat concret.'),
        ref('rdleg-6-2015-ltsv', 'competències municipals'),
      ],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'La realització de les proves de detecció d’alcohol i drogues a les vies urbanes de Roses:',
      options: [
        'Correspon exclusivament als Mossos d’Esquadra',
        'És una competència municipal que exerceix la policia local',
        'Requereix autorització judicial prèvia',
        'Només es pot fer si hi ha hagut un accident',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei atribueix aquesta competència també als municipis.',
        c: 'No cal autorització judicial per a les proves de detecció.',
        d: 'Els controls preventius són plenament possibles sense accident.',
      },
      explainCa: 'La legislació de trànsit inclou entre les competències municipals la realització de les proves per determinar el grau d’intoxicació alcohòlica o per estupefaents de les persones conductores que circulin per vies urbanes del terme municipal.',
      explainEs: 'La legislación de tráfico incluye entre las competencias municipales la realización de las pruebas para determinar el grado de intoxicación alcohólica o por estupefacientes de las personas conductoras que circulen por vías urbanas del término municipal.',
      refs: [ref('rdleg-6-2015-ltsv', 'competències dels municipis')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'L’autorització de proves esportives que discorren íntegrament pel nucli urbà de Roses correspon a:',
      options: [
        'L’Ajuntament de Roses',
        'La Generalitat de Catalunya',
        'La Federació esportiva corresponent',
        'La Delegació del Govern',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Intervé quan la prova discorre per vies interurbanes de la seva titularitat.',
        c: 'Homologa la prova esportivament, però no autoritza l’ús de la via.',
        d: 'Intervé en supòsits d’àmbit superior.',
      },
      explainCa: 'Entre les competències municipals hi ha l’autorització de proves esportives quan discorrin íntegra i exclusivament pel nucli urbà. Si la prova surt del nucli urbà, intervé l’administració titular de la via afectada.',
      explainEs: 'Entre las competencias municipales está la autorización de pruebas deportivas cuando discurran íntegra y exclusivamente por el casco urbano. Si la prueba sale del casco urbano, interviene la administración titular de la vía afectada.',
      refs: [ref('rdleg-6-2015-ltsv', 'competències dels municipis')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Per conèixer els horaris concrets de càrrega i descàrrega d’un carrer de Roses cal consultar:',
      options: [
        'El Reglament general de circulació',
        'L’ordenança municipal de circulació i la senyalització vigent',
        'La Llei de trànsit i seguretat viària',
        'El Codi penal',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Regula normes generals de circulació, no horaris municipals.',
        c: 'Fixa el marc competencial i sancionador, no els horaris locals.',
        d: 'No té res a veure amb la regulació de l’estacionament.',
      },
      explainCa: 'Els horaris de càrrega i descàrrega, les zones regulades i els usos especials de la via són dades pròpiament municipals. Es determinen a l’ordenança municipal de circulació i es concreten amb la senyalització vigent al carrer.',
      explainEs: 'Los horarios de carga y descarga, las zonas reguladas y los usos especiales de la vía son datos propiamente municipales. Se determinan en la ordenanza municipal de circulación y se concretan con la señalización vigente en la calle.',
      refs: [
        ref('roses-ordenanca-circulacio', 'parada, estacionament i càrrega i descàrrega', 'Pendent de descàrrega: cal llegir l’articulat concret al web municipal.'),
      ],
      difficulty: 'facil',
    },
  ]),

  ...questionsFor(36, [
    {
      n: 1,
      stem: 'Quin és el límit màxim de la multa que un municipi pot establir per ordenança per a una infracció molt greu, quan no hi ha normativa sectorial específica?',
      options: ['750 euros', '1.500 euros', '3.000 euros', '30.000 euros'],
      correct: 'c',
      whyWrong: {
        a: 'És el límit de les infraccions lleus.',
        b: 'És el límit de les infraccions greus.',
        d: 'Correspon al règim sancionador de la Llei orgànica 4/2015, no a les ordenances.',
      },
      explainCa: 'La legislació bàsica de règim local fixa els límits de les multes que els ens locals poden establir per ordenança quan no hi ha normativa sectorial específica: fins a 3.000 euros per a infraccions molt greus, fins a 1.500 per a les greus i fins a 750 per a les lleus.',
      explainEs: 'La legislación básica de régimen local fija los límites de las multas que los entes locales pueden establecer por ordenanza cuando no hay normativa sectorial específica: hasta 3.000 euros para infracciones muy graves, hasta 1.500 para las graves y hasta 750 para las leves.',
      refs: [ref('llei-7-1985-lrbrl', 'art. 141')],
      difficulty: 'dificil',
    },
    {
      n: 2,
      stem: 'Un municipi pot tipificar infraccions per ordenança:',
      options: [
        'Sempre, en qualsevol matèria',
        'Per a la convivència d’interès local i l’ús de serveis i espais públics, quan no hi hagi normativa sectorial específica',
        'Només si ho autoritza la Generalitat',
        'Mai: la tipificació és sempre estatal',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La potestat està delimitada materialment.',
        c: 'No cal cap autorització autonòmica.',
        d: 'La llei reconeix expressament aquesta potestat als ens locals.',
      },
      explainCa: 'La llei de bases habilita els ens locals per tipificar infraccions i sancions a les ordenances en matèries de convivència d’interès local i d’ús de serveis, equipaments, infraestructures, instal·lacions i espais públics, sempre que no hi hagi normativa sectorial específica que ho prevegi.',
      explainEs: 'La ley de bases habilita a los entes locales para tipificar infracciones y sanciones en las ordenanzas en materias de convivencia de interés local y de uso de servicios, equipamientos, infraestructuras, instalaciones y espacios públicos, siempre que no haya normativa sectorial específica que lo prevea.',
      refs: [ref('llei-7-1985-lrbrl', 'art. 139')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Si una conducta ja està tipificada per la Llei orgànica 4/2015, l’ordenança municipal:',
      options: [
        'La pot tornar a tipificar amb una sanció pròpia',
        'No la pot tornar a tipificar: cal aplicar la norma sectorial',
        'La pot tipificar si la sanció és inferior',
        'La pot tipificar amb autorització del ple',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Vulneraria el principi non bis in idem i el límit competencial de la potestat municipal.',
        c: 'La quantia de la sanció no salva el problema.',
        d: 'Cap acord del ple pot ampliar la competència legal.',
      },
      explainCa: 'La potestat municipal de tipificació opera de manera subsidiària: només quan no hi ha normativa sectorial específica que ho prevegi. Escollir la via municipal quan la conducta ja té tipificació sectorial fa caure l’expedient.',
      explainEs: 'La potestad municipal de tipificación opera de manera subsidiaria: solo cuando no hay normativa sectorial específica que lo prevea. Escoger la vía municipal cuando la conducta ya tiene tipificación sectorial hace caer el expediente.',
      refs: [ref('llei-7-1985-lrbrl', 'art. 139'), ref('lo-4-2015-psc', 'règim sancionador')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'Quina d’aquestes matèries és típica d’una ordenança de convivència ciutadana?',
      options: [
        'La regulació dels permisos de conducció',
        'L’ús de l’espai públic, els sorolls, la neteja i les conductes incíviques',
        'La tipificació de delictes lleus',
        'El règim disciplinari dels funcionaris',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És competència estatal.',
        c: 'La tipificació de delictes és reserva de llei orgànica.',
        d: 'Té regulació pròpia i diferent.',
      },
      explainCa: 'Les ordenances de convivència regulen l’ús comú de l’espai públic i les conductes que hi incideixen: sorolls, neteja i residus, pintades, consum d’alcohol a la via pública, tinença d’animals, ocupació amb terrasses, ús de platges i activitats en espais públics.',
      explainEs: 'Las ordenanzas de convivencia regulan el uso común del espacio público y las conductas que inciden en él: ruidos, limpieza y residuos, pintadas, consumo de alcohol en la vía pública, tenencia de animales, ocupación con terrazas, uso de playas y actividades en espacios públicos.',
      refs: [ref('roses-ordenanca-convivencia', 'matèries regulades', 'Pendent de descàrrega: cal contrastar l’articulat concret.')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'Per conèixer la qualificació exacta d’una conducta incívica concreta a Roses cal:',
      options: [
        'Aplicar per analogia l’ordenança d’un altre municipi',
        'Consultar el text vigent de l’ordenança de convivència de Roses',
        'Deduir-la de la Llei orgànica 4/2015',
        'Preguntar-ho al comandament de servei',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’analogia està prohibida en matèria sancionadora.',
        c: 'La llei estatal no conté la tipificació municipal.',
        d: 'Una instrucció interna no substitueix la norma.',
      },
      explainCa: 'El principi de tipicitat exigeix que la conducta i la sanció estiguin previstes a la norma aplicable. Les conductes concretes, la seva qualificació i els imports són dades pròpies de l’ordenança de Roses i s’han de consultar al text vigent publicat pel mateix Ajuntament.',
      explainEs: 'El principio de tipicidad exige que la conducta y la sanción estén previstas en la norma aplicable. Las conductas concretas, su calificación y los importes son datos propios de la ordenanza de Roses y deben consultarse en el texto vigente publicado por el propio Ayuntamiento.',
      refs: [
        ref('roses-ordenanca-convivencia', 'règim sancionador municipal', 'Pendent de descàrrega: cal llegir l’articulat concret al web municipal.'),
        ref('llei-40-2015-rjsp', 'art. 27 (principi de tipicitat)'),
      ],
      difficulty: 'mitjana',
    },
  ]),
]
