import type { Question } from '../../../schemas/index.ts'
import { questionsFor, ref, refv } from '../authoring.ts'

export const QUESTIONS_31_36: Question[] = [
  ...questionsFor(31, [
    {
      n: 1,
      stem: 'A quina comarca pertany el municipi de Roses?',
      options: ['El Baix Empordà', "L'Alt Empordà", 'El Gironès', 'La Selva'],
      correct: 'b',
      whyWrong: {
        a: 'És la comarca veïna al sud, amb capital a la Bisbal d’Empordà.',
        c: 'És la comarca de la ciutat de Girona.',
        d: 'És una comarca del sud de la província.',
      },
      explainCa: 'Roses és un municipi de la comarca de l’Alt Empordà, a la província de Girona, situat a l’extrem nord del golf de Roses, a la Costa Brava. La capital comarcal és Figueres.',
      explainEs: 'Roses es un municipio de la comarca del Alt Empordà, en la provincia de Girona, situado en el extremo norte del golfo de Roses, en la Costa Brava. La capital comarcal es Figueres.',
      refs: [ref('roses-web-municipi', 'situació geogràfica del municipi')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Entre quins dos parcs naturals se situa el terme municipal de Roses?',
      options: [
        'Cap de Creus i Aiguamolls de l’Empordà',
        'Montseny i Cadí-Moixeró',
        'Delta de l’Ebre i els Ports',
        'Garrotxa i Montgrí',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Són parcs de l’interior de Catalunya.',
        c: 'Són parcs de les Terres de l’Ebre.',
        d: 'Són parcs propers però no els que limiten Roses.',
      },
      explainCa: 'El terme de Roses queda encaixat entre el Parc Natural de Cap de Creus, al nord i a l’est, i el Parc Natural dels Aiguamolls de l’Empordà, al sud. Aquesta situació condiciona molt l’activitat policial: costa esquerpa amb cales de difícil accés i zona humida protegida.',
      explainEs: 'El término de Roses queda encajado entre el Parque Natural de Cap de Creus, al norte y al este, y el Parque Natural de los Aiguamolls de l’Empordà, al sur. Esta situación condiciona mucho la actividad policial: costa abrupta con calas de difícil acceso y zona húmeda protegida.',
      refs: [ref('roses-web-municipi', 'entorn natural del municipi')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'Quina colònia grega es va establir al lloc on avui hi ha la Ciutadella de Roses?',
      options: ['Empòrion', 'Rhode', 'Tarraco', 'Barcino'],
      correct: 'b',
      whyWrong: {
        a: 'Empòrion és la colònia grega de l’Escala, a l’altre extrem del golf.',
        c: 'Tarraco és l’actual Tarragona, d’origen romà.',
        d: 'Barcino és l’actual Barcelona, d’origen romà.',
      },
      explainCa: 'La Ciutadella de Roses conserva al seu interior les restes de la colònia grega de Rhode, que dona nom al municipi, juntament amb la vil·la romana, el monestir romànic de Santa Maria i la vila medieval.',
      explainEs: 'La Ciutadella de Roses conserva en su interior los restos de la colonia griega de Rhode, que da nombre al municipio, junto con la villa romana, el monasterio románico de Santa María y la villa medieval.',
      refs: [ref('roses-web-municipi', 'patrimoni històric: Ciutadella')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'El Castell de la Trinitat de Roses va ser manat construir per:',
      options: [
        'Jaume I el Conqueridor',
        'L’emperador Carles V',
        'Felip V',
        'El comte Ramon Berenguer IV',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És un monarca del segle XIII, molt anterior.',
        c: 'Va regnar al segle XVIII, molt posterior a la construcció.',
        d: 'És un comte del segle XII.',
      },
      explainCa: 'El Castell de la Trinitat, situat sobre la badia, va ser manat construir per l’emperador Carles V l’any 1543 com a part del sistema defensiu de la badia, juntament amb la Ciutadella. El seu nom prové d’una capella anterior de 1508.',
      explainEs: 'El Castell de la Trinitat, situado sobre la bahía, fue mandado construir por el emperador Carlos V en 1543 como parte del sistema defensivo de la bahía, junto con la Ciutadella. Su nombre proviene de una capilla anterior de 1508.',
      refs: [ref('roses-web-municipi', 'patrimoni històric: Castell de la Trinitat')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'El dolmen de la Creu d’en Cobertella, situat al terme de Roses, destaca perquè:',
      options: [
        'És l’únic dolmen de la Costa Brava',
        'És el dolmen més gran de Catalunya',
        'És d’època romana',
        'Es va traslladar des d’un altre municipi',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’Alt Empordà conserva desenes de monuments megalítics.',
        c: 'És un monument megalític, molt anterior a l’època romana.',
        d: 'Es conserva al seu emplaçament original.',
      },
      explainCa: 'El dolmen de la Creu d’en Cobertella, al terme de Roses, és el sepulcre megalític més gran de Catalunya i forma part d’un conjunt megalític molt ric a la zona de Cap de Creus i l’Alt Empordà.',
      explainEs: 'El dolmen de la Creu d’en Cobertella, en el término de Roses, es el sepulcro megalítico más grande de Cataluña y forma parte de un conjunto megalítico muy rico en la zona de Cap de Creus y el Alt Empordà.',
      refs: [ref('roses-web-municipi', 'patrimoni megalític del municipi')],
      difficulty: 'mitjana',
    },
    {
      n: 6,
      stem: 'A quina cala del terme municipal de Roses hi havia el restaurant elBulli?',
      options: ['Cala Canyelles Petites', 'Cala Montjoi', 'Cala Rostella', 'L’Almadrava'],
      correct: 'b',
      whyWrong: {
        a: 'És una altra cala del terme, però no la del restaurant.',
        c: 'És una altra cala del terme, però no la del restaurant.',
        d: 'És una altra cala del terme, però no la del restaurant.',
      },
      explainCa: 'El restaurant elBulli, dirigit per Ferran Adrià, es trobava a Cala Montjoi, dins el terme municipal de Roses. És un dels elements més coneguts internacionalment del municipi.',
      explainEs: 'El restaurante elBulli, dirigido por Ferran Adrià, se encontraba en Cala Montjoi, dentro del término municipal de Roses. Es uno de los elementos más conocidos internacionalmente del municipio.',
      refs: [ref('roses-web-municipi', 'cales i entorn del municipi')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(32, [
    {
      n: 1,
      stem: 'Quina diferència hi ha entre immobilització i retirada d’un vehicle?',
      options: [
        'Cap: són termes equivalents',
        'La immobilització deixa el vehicle al lloc sense poder circular; la retirada el trasllada al dipòsit',
        'La immobilització només s’aplica a motocicletes',
        'La retirada només la pot ordenar un jutge',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Tenen causes i efectes clarament diferents.',
        c: 'S’aplica a qualsevol classe de vehicle.',
        d: 'L’ordena l’autoritat administrativa competent en matèria de trànsit.',
      },
      explainCa: 'La immobilització manté el vehicle al lloc on es troba fins que desapareix la causa que la va motivar. La retirada comporta el trasllat al dipòsit municipal i només procedeix per les causes taxades que preveu la llei.',
      explainEs: 'La inmovilización mantiene el vehículo en el lugar donde se encuentra hasta que desaparece la causa que la motivó. La retirada comporta el traslado al depósito municipal y solo procede por las causas tasadas que prevé la ley.',
      refs: [ref('rdleg-6-2015-ltsv', 'immobilització i retirada de vehicles')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quan es presumeix que un vehicle està abandonat per romandre al dipòsit?',
      options: [
        'Quan hi ha estat més de quinze dies',
        'Quan hi ha estat més d’un mes',
        'Quan hi ha estat més de dos mesos',
        'Quan hi ha estat més de sis mesos',
      ],
      correct: 'c',
      whyWrong: {
        a: 'No correspon al termini legal.',
        b: 'Un mes és el termini per a un vehicle estacionat a la via pública amb desperfectes.',
        d: 'No correspon al termini legal.',
      },
      explainCa: 'Es presumeix racionalment l’abandonament quan el vehicle roman al dipòsit més de dos mesos, o quan resta estacionat a la via pública durant més d’un mes amb desperfectes que facin impossible el desplaçament pels seus mitjans o li faltin les plaques de matrícula.',
      explainEs: 'Se presume racionalmente el abandono cuando el vehículo permanece en el depósito más de dos meses, o cuando queda estacionado en la vía pública durante más de un mes con desperfectos que hagan imposible su desplazamiento por sus medios o le falten las placas de matrícula.',
      refs: [ref('rdleg-6-2015-ltsv', 'tractament residual del vehicle')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'Quina d’aquestes és causa d’immobilització d’un vehicle?',
      options: [
        'Estar estacionat en una zona blava sense tiquet',
        'Que el conductor superi la taxa d’alcohol permesa o es negui a les proves',
        'Tenir la ITV caducada un sol dia',
        'Circular amb els llums de posició de dia',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Genera denúncia, però no immobilització.',
        c: 'Genera denúncia; la immobilització requereix un supòsit legal específic.',
        d: 'Pot ser infracció lleu, però no causa d’immobilització.',
      },
      explainCa: 'Entre les causes d’immobilització hi ha que el conductor superi les taxes d’alcohol o presenti signes de consum de drogues, que es negui a sotmetre’s a les proves, que el vehicle no disposi de l’assegurança obligatòria, o que superi els límits de càrrega o pes autoritzats.',
      explainEs: 'Entre las causas de inmovilización están que el conductor supere las tasas de alcohol o presente signos de consumo de drogas, que se niegue a someterse a las pruebas, que el vehículo carezca del seguro obligatorio, o que supere los límites de carga o peso autorizados.',
      refs: [ref('rdleg-6-2015-ltsv', 'causes d’immobilització')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Un vehicle estacionat de manera incorrecta però sense crear cap perill ni obstaculitzar res:',
      options: [
        'Sempre es pot retirar amb la grua',
        'No es pot retirar: cal que concorri una de les causes taxades de retirada',
        'S’ha d’immobilitzar obligatòriament',
        'S’ha de deixar sense denunciar',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La retirada no és una conseqüència automàtica de qualsevol infracció d’estacionament.',
        c: 'La immobilització té causes pròpies i diferents.',
        d: 'La infracció es pot denunciar igualment.',
      },
      explainCa: 'La retirada exigeix una causa taxada: perill, pertorbació greu de la circulació o del funcionament d’un servei públic, obstaculització de sortides o passos, ocupació d’espais reservats. Si no en concorre cap, es denuncia la infracció però no es pot retirar el vehicle ni repercutir-ne les despeses.',
      explainEs: 'La retirada exige una causa tasada: peligro, perturbación grave de la circulación o del funcionamiento de un servicio público, obstaculización de salidas o pasos, ocupación de espacios reservados. Si no concurre ninguna, se denuncia la infracción pero no se puede retirar el vehículo ni repercutir sus gastos.',
      refs: [ref('rdleg-6-2015-ltsv', 'causes de retirada de vehicles')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Quin permís habilita per conduir turismes?',
      options: ['El permís A', 'El permís B', 'El permís C1', 'La llicència LCC'],
      correct: 'b',
      whyWrong: {
        a: 'Habilita per conduir motocicletes sense limitació de potència.',
        c: 'Habilita per conduir camions dins uns límits de massa.',
        d: 'És una llicència per a ciclomotors de tres rodes i quadricicles lleugers.',
      },
      explainCa: 'El permís de la classe B habilita per conduir automòbils la massa màxima autoritzada dels quals no excedeixi els límits reglamentaris i estiguin dissenyats per transportar un nombre limitat de persones a més del conductor, és a dir, els turismes.',
      explainEs: 'El permiso de la clase B habilita para conducir automóviles cuya masa máxima autorizada no exceda los límites reglamentarios y estén diseñados para transportar un número limitado de personas además del conductor, es decir, los turismos.',
      refs: [ref('rd-818-2009-rgcond', 'classes de permisos de conducció')],
      difficulty: 'facil',
    },
  ]),

  ...questionsFor(33, [
    {
      n: 1,
      stem: 'Quina taxa d’alcohol en aire espirat converteix la conducta en delicte contra la seguretat viària?',
      options: [
        'Superior a 0,25 mg/l',
        'Superior a 0,50 mg/l',
        'Superior a 0,60 mg/l',
        'Superior a 0,80 mg/l',
      ],
      correct: 'c',
      whyWrong: {
        a: 'És el llindar administratiu general.',
        b: 'No correspon a cap llindar legal en aire espirat.',
        d: 'No correspon al llindar penal.',
      },
      explainCa: 'El Codi penal estableix que en tot cas serà condemnat qui condueixi amb una taxa d’alcohol en aire espirat superior a 0,60 mil·ligrams per litre o amb una taxa d’alcohol en sang superior a 1,2 grams per litre.',
      explainEs: 'El Código penal establece que en todo caso será condenado quien conduzca con una tasa de alcohol en aire espirado superior a 0,60 miligramos por litro o con una tasa de alcohol en sangre superior a 1,2 gramos por litro.',
      refs: [ref('lo-10-1995-cp', 'art. 379.2')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quina és la taxa màxima d’alcohol en aire espirat per a un conductor novell o professional?',
      options: ['0,10 mg/l', '0,15 mg/l', '0,25 mg/l', '0,30 mg/l'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon a cap llindar legal.',
        c: 'És el llindar per als conductors en general.',
        d: '0,30 g/l és el llindar en sang per a aquest col·lectiu, no en aire espirat.',
      },
      explainCa: 'Els conductors novells —durant els dos anys següents a l’obtenció del permís— i els professionals no poden superar una taxa de 0,15 mil·ligrams per litre en aire espirat, o 0,3 grams per litre en sang. Per a la resta de conductors el límit és 0,25 mg/l i 0,5 g/l.',
      explainEs: 'Los conductores noveles —durante los dos años siguientes a la obtención del permiso— y los profesionales no pueden superar una tasa de 0,15 miligramos por litro en aire espirado, o 0,3 gramos por litro en sangre. Para el resto de conductores el límite es 0,25 mg/l y 0,5 g/l.',
      refs: [ref('rd-1428-2003-rgc', 'taxes d’alcoholèmia')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'La pràctica de la prova d’alcoholèmia amb etilòmetre exigeix:',
      options: [
        'Una única determinació',
        'Dues determinacions successives amb un interval mínim de deu minuts',
        'Tres determinacions consecutives',
        'Una determinació i un anàlisi de sang obligatori',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La norma exigeix dues determinacions.',
        c: 'La norma no n’exigeix tres.',
        d: 'L’anàlisi de sang és un dret de contrast de la persona interessada, no un tràmit obligatori.',
      },
      explainCa: 'La prova consisteix en dues determinacions successives amb un etilòmetre homologat, separades per un interval mínim de deu minuts. La persona interessada té dret a contrastar el resultat mitjançant anàlisi de sang, amb les despeses al seu càrrec si es confirma la infracció.',
      explainEs: 'La prueba consiste en dos determinaciones sucesivas con un etilómetro homologado, separadas por un intervalo mínimo de diez minutos. La persona interesada tiene derecho a contrastar el resultado mediante análisis de sangre, con los gastos a su cargo si se confirma la infracción.',
      refs: [ref('rd-1428-2003-rgc', 'pràctica de les proves de detecció alcohòlica')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'Qui està obligat a sotmetre’s a les proves de detecció d’alcohol o drogues?',
      options: [
        'Només qui condueixi de manera manifestament irregular',
        'Els conductors, els implicats com a possibles responsables en un accident, qui presenti símptomes i qui hagi comès una infracció',
        'Només els conductors professionals',
        'Només qui hagi provocat danys personals',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’obligació és molt més àmplia.',
        c: 'Afecta tots els conductors.',
        d: 'No cal cap resultat lesiu.',
      },
      explainCa: 'Estan obligats a sotmetre’s a les proves els conductors de vehicles, les persones implicades directament com a possibles responsables en un accident de circulació, qui presenti símptomes evidents o un comportament que faci presumir la influència de begudes o drogues, i qui hagi comès una infracció de trànsit, a més dels controls preventius reglamentaris.',
      explainEs: 'Están obligados a someterse a las pruebas los conductores de vehículos, las personas implicadas directamente como posibles responsables en un accidente de circulación, quien presente síntomas evidentes o un comportamiento que haga presumir la influencia de bebidas o drogas, y quien haya cometido una infracción de tráfico, además de los controles preventivos reglamentarios.',
      refs: [ref('rdleg-6-2015-ltsv', 'obligació de sotmetre’s a les proves')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'En matèria de drogues al volant, la regla general és que:',
      options: [
        'Hi ha una taxa permesa equivalent a la de l’alcohol',
        'La infracció és conduir amb presència de drogues a l’organisme, amb l’excepció de les prescrites terapèuticament',
        'Només és infracció si es demostra afectació de la capacitat de conduir',
        'Només s’aplica als conductors professionals',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No existeix cap taxa permesa per a drogues.',
        c: 'La presència, per si mateixa, ja constitueix la infracció administrativa.',
        d: 'S’aplica a tots els conductors.',
      },
      explainCa: 'A diferència de l’alcohol, en drogues no hi ha taxa permesa: la infracció administrativa és conduir amb presència de drogues a l’organisme. S’exclouen les substàncies utilitzades sota prescripció facultativa i amb una finalitat terapèutica, sempre que no afectin la capacitat de conduir.',
      explainEs: 'A diferencia del alcohol, en drogas no hay tasa permitida: la infracción administrativa es conducir con presencia de drogas en el organismo. Se excluyen las sustancias utilizadas bajo prescripción facultativa y con una finalidad terapéutica, siempre que no afecten a la capacidad de conducir.',
      refs: [ref('rdleg-6-2015-ltsv', 'presència de drogues en l’organisme')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(34, [
    {
      n: 1,
      stem: 'Quines vies hi ha perquè un gos sigui considerat potencialment perillós?',
      options: [
        'Únicament pertànyer a una raça de la llista',
        'Per raça o encreuament, per episodis d’agressió previs i per ensinistrament per a l’atac i la defensa',
        'Únicament el pes de l’animal',
        'Només per decisió judicial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La raça és només una de les vies.',
        c: 'El pes és un dels indicadors físics, però no l’únic criteri.',
        d: 'La qualificació és administrativa, no judicial.',
      },
      explainCa: 'Un gos pot ser considerat potencialment perillós per pertànyer a una raça de la llista o ser-ne un encreuament, per haver tingut episodis d’agressions a persones o a altres gossos, o per haver estat ensinistrat per a l’atac i la defensa. També s’hi inclouen exemplars amb determinades característiques físiques.',
      explainEs: 'Un perro puede ser considerado potencialmente peligroso por pertenecer a una raza de la lista o ser un cruce, por haber tenido episodios de agresiones a personas o a otros perros, o por haber sido adiestrado para el ataque y la defensa. También se incluyen ejemplares con determinadas características físicas.',
      refs: [ref('llei-50-1999-app', 'concepte'), ref('llei-10-1999-gossos-cat', 'gossos considerats potencialment perillosos')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Qui atorga la llicència per a la tinença de gossos potencialment perillosos?',
      options: [
        'El Departament d’Interior de la Generalitat',
        'L’ajuntament del municipi de residència de la persona sol·licitant',
        'El col·legi de veterinaris',
        'La Delegació del Govern',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No té atribuïda aquesta competència.',
        c: 'Intervé en la identificació i els certificats, però no atorga la llicència.',
        d: 'No té aquesta competència.',
      },
      explainCa: 'La llicència administrativa per a la tinença d’animals potencialment perillosos l’atorga l’ajuntament del municipi de residència de la persona sol·licitant. A Roses és un tràmit municipal específic.',
      explainEs: 'La licencia administrativa para la tenencia de animales potencialmente peligrosos la otorga el ayuntamiento del municipio de residencia de la persona solicitante. En Roses es un trámite municipal específico.',
      refs: [ref('llei-50-1999-app', 'llicència administrativa'), ref('roses-tramits-animals', 'tràmit municipal a Roses')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'Quin d’aquests NO és un requisit per obtenir la llicència de tinença d’un gos potencialment perillós?',
      options: [
        'Ser major d’edat',
        'Disposar d’una assegurança de responsabilitat civil per danys a tercers',
        'Acreditar una formació prèvia com a ensinistrador caní',
        'Acreditar capacitat física i aptitud psicològica',
      ],
      correct: 'c',
      whyWrong: {
        a: 'Sí que és un requisit legal.',
        b: 'Sí que és un requisit legal.',
        d: 'Sí que és un requisit legal.',
      },
      explainCa: 'Els requisits són ser major d’edat, no haver estat condemnat per determinats delictes ni sancionat per infraccions greus o molt greus en la matèria, acreditar capacitat física i aptitud psicològica mitjançant certificat, i disposar d’una assegurança de responsabilitat civil per danys a tercers. No s’exigeix formació com a ensinistrador.',
      explainEs: 'Los requisitos son ser mayor de edad, no haber sido condenado por determinados delitos ni sancionado por infracciones graves o muy graves en la materia, acreditar capacidad física y aptitud psicológica mediante certificado, y disponer de un seguro de responsabilidad civil por daños a terceros. No se exige formación como adiestrador.',
      refs: [ref('llei-50-1999-app', 'requisits de la llicència'), ref('rd-287-2002-app', 'desenvolupament reglamentari')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'A la via pública, un gos potencialment perillós ha d’anar:',
      options: [
        'Solt però sota control visual',
        'Lligat amb corretja no extensible de longitud limitada i amb morrió',
        'Amb morrió però sense corretja',
        'Amb corretja extensible de fins a cinc metres',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La normativa exigeix expressament corretja i morrió.',
        c: 'Falta l’obligació de portar-lo lligat.',
        d: 'La corretja ha de ser no extensible i de longitud limitada.',
      },
      explainCa: 'A les vies públiques i als espais d’ús públic, el gos ha de portar obligatòriament morrió adequat a la seva raça i anar subjecte amb una cadena o corretja no extensible de longitud limitada. A més, una persona no pot conduir més d’un gos potencialment perillós alhora.',
      explainEs: 'En las vías públicas y en los espacios de uso público, el perro debe llevar obligatoriamente bozal adecuado a su raza e ir sujeto con una cadena o correa no extensible de longitud limitada. Además, una persona no puede conducir más de un perro potencialmente peligroso a la vez.',
      refs: [ref('rd-287-2002-app', 'mesures de seguretat a la via pública')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'La identificació per microxip i la inscripció al registre censal municipal són obligatòries per a:',
      options: [
        'Només els gossos potencialment perillosos',
        'Tots els gossos',
        'Només els gossos de més de deu quilos',
        'Només els gossos que surten a la via pública',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llicència és exclusiva dels potencialment perillosos, però la identificació i el cens no.',
        c: 'El pes no és el criteri.',
        d: 'L’obligació no depèn de l’ús que se’n faci.',
      },
      explainCa: 'La identificació mitjançant microxip i la inscripció al registre censal municipal són obligatòries per a tots els gossos. El que és exclusiu dels gossos potencialment perillosos és la llicència administrativa i la inscripció al registre específic.',
      explainEs: 'La identificación mediante microchip y la inscripción en el registro censal municipal son obligatorias para todos los perros. Lo que es exclusivo de los perros potencialmente peligrosos es la licencia administrativa y la inscripción en el registro específico.',
      refs: [
        ref('llei-10-1999-gossos-cat', 'identificació i registre'),
        ref('llei-7-2023-benestar-animal', 'obligacions generals de les persones titulars'),
      ],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(35, [
    {
      n: 1,
      stem: 'Segons l’article 1 de l’Ordenança municipal de circulació de Roses, el concepte de via urbana que fa servir l’ordenança inclou:',
      options: [
        'Únicament els carrers i places de titularitat municipal',
        'Els elements de vialitat i terrenys de titularitat privada destinats amb caràcter general a la circulació de vehicles',
        'Les travesseres i carreteres que creuen el terme, siguin de qui siguin',
        'Només les vies incloses al catàleg municipal de carrers',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’article 1.3 va més enllà: també hi entren els terrenys privats destinats amb caràcter general a la circulació.',
        c: 'L’ordenança desplega la competència municipal sobre vies urbanes, no sobre la xarxa interurbana.',
        d: 'L’ordenança no condiciona l’aplicació a cap catàleg.',
      },
      explainCa: 'L’article 1.3 diu que el concepte de via urbana comprèn tant els elements de vialitat en sentit estricte, les places i altres espais públics de titularitat municipal aptes per a la circulació, com els elements de vialitat i terrenys de titularitat privada destinats amb caràcter general a la circulació de vehicles. És una definició més àmplia del que sembla, i és la que decideix si l’ordenança s’aplica o no.',
      explainEs: 'El artículo 1.3 dice que el concepto de vía urbana comprende tanto los elementos de vialidad en sentido estricto, las plazas y otros espacios públicos de titularidad municipal aptos para la circulación, como los elementos de vialidad y terrenos de titularidad privada destinados con carácter general a la circulación de vehículos. Es una definición más amplia de lo que parece, y es la que decide si la ordenanza se aplica o no.',
      refs: [refv('roses-ordenanca-circulacio', 'art. 1.3, pàgina 3 del PDF', '2010-12-13')],
      difficulty: 'dificil',
    },
    {
      n: 2,
      stem: 'Davant d’una contradicció entre un senyal vertical i l’ordre d’un agent de la Policia Local, l’Ordenança de circulació de Roses estableix que:',
      options: [
        'Preval el senyal vertical, per seguretat jurídica',
        'Preval l’ordre de l’agent de l’autoritat',
        'Cal aturar-se i esperar instruccions del centre de comandament',
        'Preval el senyal si és preceptiu i l’ordre si és d’advertència',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’article 2.3 diu exactament el contrari.',
        c: 'L’ordenança no preveu cap suspensió d’aquest tipus.',
        d: 'L’ordenança no fa aquesta distinció.',
      },
      explainCa: 'L’article 2.3 estableix que els senyals i les ordres dels agents de la Policia Local o d’altres agents de l’autoritat prevaldran sobre qualsevol altre tipus de senyalització. És la regla que ordena qualsevol conflicte de senyals a la via urbana.',
      explainEs: 'El artículo 2.3 establece que las señales y las órdenes de los agentes de la Policía Local o de otros agentes de la autoridad prevalecerán sobre cualquier otro tipo de señalización. Es la regla que ordena cualquier conflicto de señales en la vía urbana.',
      refs: [refv('roses-ordenanca-circulacio', 'art. 2.3, pàgina 3 del PDF', '2010-12-13')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Segons l’article 46 bis de l’Ordenança de circulació de Roses, un vehicle de mobilitat personal pot circular per la calçada d’una via urbana:',
      options: [
        'Sempre, si respecta la velocitat de la via',
        'Només si la velocitat permesa en aquella via no supera els 30 km/h',
        'Només si la via té més d’un carril per sentit de circulació',
        'Mai: els VMP només poden anar per carril bici',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’article fixa un límit de velocitat de la via, no de conducció.',
        c: 'És justament un dels supòsits en què l’article ho prohibeix.',
        d: 'L’article 46 bis.2.a permet la calçada dins el límit de 30 km/h.',
      },
      explainCa: 'L’article 46 bis.2 permet als VMP circular per la calçada en vies urbanes sempre que la velocitat permesa en aquella via no superi els 30 km/h, i pels carrils bici adequadament senyalitzats. El punt 3 els ho prohibeix expressament quan la via permet més de 30 km/h o té més d’un carril per sentit, i també per voreres i zones de vianants llevat de les expressament autoritzades.',
      explainEs: 'El artículo 46 bis.2 permite a los VMP circular por la calzada en vías urbanas siempre que la velocidad permitida en esa vía no supere los 30 km/h, y por los carriles bici adecuadamente señalizados. El punto 3 se lo prohíbe expresamente cuando la vía permite más de 30 km/h o tiene más de un carril por sentido, y también por aceras y zonas peatonales salvo las expresamente autorizadas.',
      refs: [refv('roses-ordenanca-circulacio-mod-2021', 'art. 46 bis, punts 2 i 3, pàgines 3–4 del PDF', '2021-03-03')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quina edat mínima exigeix l’Ordenança de circulació de Roses per conduir un vehicle de mobilitat personal?',
      options: ['14 anys', '15 anys', '16 anys', 'No n’estableix cap'],
      correct: 'b',
      whyWrong: {
        a: 'És l’edat que proposava una de les opcions descartades a l’examen de 2021, no la de l’ordenança.',
        c: 'L’ordenança no fixa els 16 anys.',
        d: 'L’article 46 bis.4.a sí que fixa una edat mínima.',
      },
      explainCa: 'L’article 46 bis.4.a, incorporat per la modificació de 2021, exigeix una edat mínima de 15 anys per circular amb un vehicle de mobilitat personal. L’annex 1 tipifica circular amb edat inferior com a infracció lleu de 100 €, amb import bonificat de 50 €.',
      explainEs: 'El artículo 46 bis.4.a, incorporado por la modificación de 2021, exige una edad mínima de 15 años para circular con un vehículo de movilidad personal. El anexo 1 tipifica circular con edad inferior como infracción leve de 100 €, con importe bonificado de 50 €.',
      refs: [
        refv('roses-ordenanca-circulacio-mod-2021', 'art. 46 bis.4.a, pàgina 4 del PDF', '2021-03-03'),
        refv('roses-ordenanca-circulacio-mod-2021', 'annex 1, pàgina 5 del PDF', '2021-03-03'),
      ],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'A Roses, circular amb un vehicle de mobilitat personal sense casc homologat:',
      options: [
        'No és infracció: el casc només és recomanable',
        'És infracció greu segons l’annex de l’ordenança',
        'És infracció lleu de 50 €',
        'Només és infracció si es circula per la calçada',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’article 46 bis.4 el fa obligatori al terme de Roses.',
        c: 'L’annex el qualifica de greu, amb 200 € i 100 € bonificats.',
        d: 'L’obligació no distingeix per tipus de via.',
      },
      explainCa: 'L’ordenança de Roses exigeix casc homologat per conduir un VMP, i l’annex 1 tipifica circular-hi sense com a infracció greu de 200 €, amb import bonificat de 100 €. És una exigència municipal: no la fixa la norma estatal general, i per això sorprèn qui estudia només normativa estatal.',
      explainEs: 'La ordenanza de Roses exige casco homologado para conducir un VMP, y el anexo 1 tipifica circular sin él como infracción grave de 200 €, con importe bonificado de 100 €. Es una exigencia municipal: no la fija la norma estatal general, y por eso sorprende a quien estudia solo normativa estatal.',
      refs: [
        refv('roses-ordenanca-circulacio-mod-2021', 'art. 46 bis.4, pàgina 4 del PDF', '2021-03-03',
          'La taula de l’annex cita aquesta conducta com a 46 bis.4.i, mentre que l’articulat la situa a la lletra h. La discrepància és del document oficial; la conducta, en canvi, és inequívoca als dos textos.'),
        refv('roses-ordenanca-circulacio-mod-2021', 'annex 1, pàgina 5 del PDF', '2021-03-03'),
      ],
      difficulty: 'dificil',
    },
    {
      n: 6,
      stem: 'Les zones d’estacionament reservades per a persones amb discapacitat i mobilitat reduïda a Roses, després de la modificació de 2021:',
      options: [
        'Només poden ser d’ús general per a qualsevol titular de la targeta',
        'Poden ser d’ús general o d’ús individual per a un titular determinat',
        'Han de ser sempre d’ús individual',
        'Les atorga directament la Generalitat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La modificació de 2021 va crear precisament la modalitat individual.',
        c: 'Les d’ús general continuen existint.',
        d: 'És l’Ajuntament qui les estableix i les senyalitza.',
      },
      explainCa: 'La nova redacció de l’article 19 preveu dues modalitats: zones d’ús general, a disposició de qualsevol titular de la targeta d’aparcament, i zones d’ús individual, destinades a l’ús exclusiu d’un titular determinat prèviament autoritzat i del vehicle que figuri a la senyalització vertical corresponent.',
      explainEs: 'La nueva redacción del artículo 19 prevé dos modalidades: zonas de uso general, a disposición de cualquier titular de la tarjeta de aparcamiento, y zonas de uso individual, destinadas al uso exclusivo de un titular determinado previamente autorizado y del vehículo que figure en la señalización vertical correspondiente.',
      refs: [refv('roses-ordenanca-circulacio-mod-2021', 'art. 19, punts 1 a 3, pàgines 2–3 del PDF', '2021-03-03')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(36, [
    {
      n: 1,
      stem: 'Quin és l’objecte de l’Ordenança de mesures per fomentar i garantir la convivència ciutadana al municipi de Roses?',
      options: [
        'Regular l’activitat comercial i les terrasses del municipi',
        'Preservar l’espai públic com a lloc de convivència i civisme',
        'Establir el règim disciplinari del personal municipal',
        'Ordenar el trànsit de persones i vehicles a les vies urbanes',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És una matèria que hi apareix, però no és l’objecte que declara l’article 1.',
        c: 'No és matèria d’aquesta ordenança.',
        d: 'Aquest és l’objecte de l’ordenança de circulació.',
      },
      explainCa: 'L’article 1 declara que l’ordenança té per objecte preservar l’espai públic com a lloc de convivència i civisme, on totes les persones puguin desenvolupar en llibertat les seves activitats de lliure circulació, oci, trobada i esbarjo, amb ple respecte a la dignitat i als drets dels altres i a la pluralitat d’expressions culturals, polítiques, lingüístiques i religioses i de formes de vida.',
      explainEs: 'El artículo 1 declara que la ordenanza tiene por objeto preservar el espacio público como lugar de convivencia y civismo, donde todas las personas puedan desarrollar en libertad sus actividades de libre circulación, ocio, encuentro y esparcimiento, con pleno respeto a la dignidad y a los derechos de los demás y a la pluralidad de expresiones culturales, políticas, lingüísticas y religiosas y de formas de vida.',
      refs: [refv('roses-ordenanca-convivencia', 'art. 1, pàgina 3 del PDF', '2019-05-29')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Després de la modificació de 2021, consumir begudes alcohòliques en un espai públic de Roses sense que se’n derivi cap alteració de la convivència:',
      options: [
        'No és infracció, perquè la prohibició exigeix alterar la convivència',
        'És infracció, llevat que sigui en terrasses i vetlladors o en festes o actes populars autoritzats',
        'És infracció només si hi ha menors a prop',
        'És infracció molt greu en tot cas',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Aquesta era la regla fins que la modificació de 2021 va afegir el punt 4 a l’article 10.',
        c: 'L’afluència de menors és una de les circumstàncies del punt 1, no la condició del punt 4.',
        d: 'L’annex el qualifica de lleu, amb 100 €.',
      },
      explainCa: 'El punt 4 de l’article 10, afegit per la modificació aprovada definitivament el 24 de febrer de 2021, prohibeix el consum de begudes alcohòliques als espais públics encara que no es pertorbi la convivència ciutadana. Les excepcions són els establiments i espais reservats expressament per a aquesta finalitat, com terrasses i vetlladors, i les festes o actes populars amb l’oportuna autorització. L’annex el tipifica com a infracció lleu de 100 €.',
      explainEs: 'El punto 4 del artículo 10, añadido por la modificación aprobada definitivamente el 24 de febrero de 2021, prohíbe el consumo de bebidas alcohólicas en los espacios públicos aunque no se perturbe la convivencia ciudadana. Las excepciones son los establecimientos y espacios reservados expresamente para esa finalidad, como terrazas y veladores, y las fiestas o actos populares con la oportuna autorización. El anexo lo tipifica como infracción leve de 100 €.',
      refs: [
        refv('roses-ordenanca-convivencia-mod-2021', 'modificació primera (art. 10.4), pàgina 1 del PDF', '2021-03-19'),
        refv('roses-ordenanca-convivencia-mod-2021', 'annex, art. 10.4, pàgina 3 del PDF', '2021-03-19'),
      ],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Segons la redacció vigent de l’article 11.1 de l’Ordenança de convivència de Roses, la venda ambulant sense autorització municipal:',
      options: [
        'Està prohibida a tot el municipi',
        'Està prohibida excepte dins l’àmbit del mercat municipal de no sedentaris',
        'Només està prohibida al passeig marítim',
        'Està permesa si el venedor no ocupa la via pública',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Aquesta excepció era a la redacció de 2019 i la modificació de 2021 la va suprimir.',
        c: 'La prohibició no té àmbit territorial restringit.',
        d: 'L’ocupació de via pública se sanciona a més, per la normativa sectorial.',
      },
      explainCa: 'La modificació de 2021 va donar nova redacció al punt 1 de l’article 11: la venda ambulant sense autorització municipal resta prohibida a tot el municipi, sense l’excepció del mercat de no sedentaris que hi havia al text de 2019. A més, si la venda s’exerceix amb ocupació de via pública, aquesta ocupació se sanciona per la normativa sectorial vigent.',
      explainEs: 'La modificación de 2021 dio nueva redacción al punto 1 del artículo 11: la venta ambulante sin autorización municipal queda prohibida en todo el municipio, sin la excepción del mercado de no sedentarios que había en el texto de 2019. Además, si la venta se ejerce con ocupación de vía pública, esa ocupación se sanciona por la normativa sectorial vigente.',
      refs: [refv('roses-ordenanca-convivencia-mod-2021', 'modificació segona (art. 11.1), pàgina 2 del PDF', '2021-03-19')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Com va quedar tipificada la venda ambulant no autoritzada a l’annex de l’Ordenança de convivència després de la modificació de 2021?',
      options: [
        'Infracció greu, 1.500 €',
        'Infracció lleu, 600 €',
        'Infracció molt greu, 3.000 €',
        'Infracció lleu, 100 €',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Aquesta era la qualificació del text de 2019, que la modificació va rebaixar.',
        c: 'L’annex no la qualifica de molt greu.',
        d: 'És l’import del consum d’alcohol de l’article 10.4.',
      },
      explainCa: 'La modificació cinquena de 2021 rebaixa l’article 11.1 de greu amb 1.500 € a lleu amb 600 €, i l’11.2 de greu amb 750 € a lleu amb 500 €. Al mateix acte, l’article 16 —conductes vandàliques— passa de greu amb 1.000 € a lleu amb 300 €. És un canvi a la baixa i per això sorprèn.',
      explainEs: 'La modificación quinta de 2021 rebaja el artículo 11.1 de grave con 1.500 € a leve con 600 €, y el 11.2 de grave con 750 € a leve con 500 €. En el mismo acto, el artículo 16 —conductas vandálicas— pasa de grave con 1.000 € a leve con 300 €. Es un cambio a la baja y por eso sorprende.',
      refs: [refv('roses-ordenanca-convivencia-mod-2021', 'modificació cinquena (annex, art. 11.1 i 11.2), pàgina 3 del PDF', '2021-03-19')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Quina reducció preveu l’article 28 de l’Ordenança de convivència de Roses per al pagament voluntari abans de la resolució sancionadora?',
      options: ['El 10 %', 'El 20 %', 'El 50 %', 'Cap: l’import és fix'],
      correct: 'b',
      whyWrong: {
        a: 'L’ordenança fixa el 20 %, no el 10 %.',
        c: 'El 50 % no apareix a l’article 28.',
        d: 'L’article 28 preveu expressament la bonificació.',
      },
      explainCa: 'La modificació quarta de 2021 afegeix a l’article 28 que, en cas de pagament voluntari abans de la resolució sancionadora, s’aplica una bonificació del 20 % als imports denunciats. La persona presumptament responsable també pot reconèixer voluntàriament la seva responsabilitat, i en tots dos casos l’òrgan resolutori aplica una reducció de com a mínim el 20 %, acumulables entre si, condicionada al desistiment o renúncia de qualsevol acció o recurs en via administrativa.',
      explainEs: 'La modificación cuarta de 2021 añade al artículo 28 que, en caso de pago voluntario antes de la resolución sancionadora, se aplica una bonificación del 20 % a los importes denunciados. La persona presuntamente responsable también puede reconocer voluntariamente su responsabilidad, y en ambos casos el órgano resolutorio aplica una reducción de al menos el 20 %, acumulables entre sí, condicionada al desistimiento o renuncia de cualquier acción o recurso en vía administrativa.',
      refs: [refv('roses-ordenanca-convivencia-mod-2021', 'modificació quarta (art. 28), pàgina 2 del PDF', '2021-03-19')],
      difficulty: 'mitjana',
    },
    {
      n: 6,
      stem: 'L’Ordenança de convivència de Roses s’aplica:',
      options: [
        'Només als espais de domini públic municipal',
        'A tot el terme municipal i, especialment, als espais de domini públic municipal i als d’ús públic',
        'Només al nucli urbà i les urbanitzacions',
        'Només als espais tancats de titularitat municipal',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’article 2 hi afegeix els espais d’ús públic i abasta tot el terme.',
        c: 'No hi ha cap limitació al nucli urbà.',
        d: 'L’ordenança regula sobretot l’espai públic obert.',
      },
      explainCa: 'L’article 2 estableix que l’ordenança s’aplica a tot el terme municipal de Roses i, especialment, als espais de domini públic municipal i als d’ús públic. Aquesta última categoria és la que permet aplicar-la a espais que no són estrictament de titularitat municipal però que tenen ús públic.',
      explainEs: 'El artículo 2 establece que la ordenanza se aplica a todo el término municipal de Roses y, especialmente, a los espacios de dominio público municipal y a los de uso público. Esta última categoría es la que permite aplicarla a espacios que no son estrictamente de titularidad municipal pero que tienen uso público.',
      refs: [refv('roses-ordenanca-convivencia', 'art. 2, pàgina 3 del PDF', '2019-05-29')],
      difficulty: 'facil',
    },
  ]),
]
