import type { Question } from '../../../schemas/index.ts'
import { questionsFor, ref } from '../authoring.ts'

export const QUESTIONS_01_05: Question[] = [
  ...questionsFor(1, [
    {
      n: 1,
      stem: 'Quants articles té la Constitució espanyola de 1978?',
      options: ['155 articles', '169 articles', '178 articles', '182 articles'],
      correct: 'b',
      whyWrong: {
        a: '155 és el número d’un article concret sobre mesures de compliment forçós autonòmic, no el total.',
        c: 'No correspon a cap dada de la Constitució.',
        d: 'No correspon a cap dada de la Constitució.',
      },
      explainCa: 'La Constitució té 169 articles, distribuïts en un títol preliminar i deu títols, més quatre disposicions addicionals, nou transitòries, una derogatòria i una final.',
      explainEs: 'La Constitución tiene 169 artículos, distribuidos en un título preliminar y diez títulos, más cuatro disposiciones adicionales, nueve transitorias, una derogatoria y una final.',
      refs: [ref('ce-1978', 'estructura general')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Segons l’article 1.1 de la Constitució, quins són els valors superiors de l’ordenament jurídic?',
      options: [
        'La dignitat, la solidaritat, la seguretat i la justícia',
        'La llibertat, la justícia, la igualtat i el pluralisme polític',
        'La llibertat, la igualtat, la fraternitat i la legalitat',
        'La sobirania, la unitat, l’autonomia i la solidaritat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La dignitat de la persona apareix a l’article 10 com a fonament de l’ordre polític, no com a valor superior de l’article 1.1.',
        c: 'És el lema de la Revolució Francesa, no el text constitucional.',
        d: 'Són principis de l’article 2 sobre l’organització territorial.',
      },
      explainCa: 'L’article 1.1 constitueix Espanya en un Estat social i democràtic de dret que propugna com a valors superiors del seu ordenament jurídic la llibertat, la justícia, la igualtat i el pluralisme polític.',
      explainEs: 'El artículo 1.1 constituye a España en un Estado social y democrático de derecho que propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad y el pluralismo político.',
      refs: [ref('ce-1978', 'art. 1.1')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'Quin d’aquests principis NO està garantit expressament per l’article 9.3 de la Constitució?',
      options: [
        'La jerarquia normativa',
        'La irretroactivitat de les disposicions sancionadores no favorables',
        'La proporcionalitat de les penes',
        'La interdicció de l’arbitrarietat dels poders públics',
      ],
      correct: 'c',
      whyWrong: {
        a: 'Sí que hi apareix expressament.',
        b: 'Sí que hi apareix expressament.',
        d: 'És l’últim principi que enumera l’article 9.3.',
      },
      explainCa: 'L’article 9.3 garanteix el principi de legalitat, la jerarquia normativa, la publicitat de les normes, la irretroactivitat de les disposicions sancionadores no favorables o restrictives de drets individuals, la seguretat jurídica, la responsabilitat i la interdicció de l’arbitrarietat dels poders públics. La proporcionalitat de les penes és un principi penal derivat, però no consta en aquesta enumeració.',
      explainEs: 'El artículo 9.3 garantiza el principio de legalidad, la jerarquía normativa, la publicidad de las normas, la irretroactividad de las disposiciones sancionadoras no favorables o restrictivas de derechos individuales, la seguridad jurídica, la responsabilidad y la interdicción de la arbitrariedad de los poderes públicos. La proporcionalidad de las penas es un principio penal derivado, pero no consta en esta enumeración.',
      refs: [ref('ce-1978', 'art. 9.3')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'La reforma agreujada de l’article 168 de la Constitució s’exigeix, entre altres supòsits, quan la reforma afecta:',
      options: [
        'El títol VIII, sobre organització territorial',
        'El títol preliminar, la secció 1a del capítol II del títol I o el títol II',
        'Qualsevol article del títol I',
        'El títol VII, sobre economia i hisenda',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El títol VIII es reforma per la via ordinària de l’article 167.',
        c: 'Només la secció 1a del capítol II del títol I, no tot el títol I.',
        d: 'Es reforma per la via ordinària.',
      },
      explainCa: 'L’article 168 s’aplica a la revisió total de la Constitució o a una revisió parcial que afecti el títol preliminar, la secció 1a del capítol II del títol I (drets fonamentals i llibertats públiques) o el títol II (la Corona). Exigeix majoria de dos terços, dissolució de les Corts, ratificació per les noves cambres i referèndum.',
      explainEs: 'El artículo 168 se aplica a la revisión total de la Constitución o a una revisión parcial que afecte al título preliminar, la sección 1ª del capítulo II del título I (derechos fundamentales y libertades públicas) o el título II (la Corona). Exige mayoría de dos tercios, disolución de las Cortes, ratificación por las nuevas cámaras y referéndum.',
      refs: [ref('ce-1978', 'art. 167 i 168')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Segons l’article 1.3 de la Constitució, la forma política de l’Estat espanyol és:',
      options: [
        'La república parlamentària',
        'La monarquia parlamentària',
        'La monarquia constitucional',
        'L’Estat autonòmic',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La Constitució estableix una monarquia, no una república.',
        c: '«Monarquia constitucional» és una categoria històrica; el text diu literalment «monarquia parlamentària».',
        d: 'L’Estat autonòmic descriu l’organització territorial, no la forma política.',
      },
      explainCa: 'L’article 1.3 diu literalment que la forma política de l’Estat espanyol és la monarquia parlamentària. Convé recordar el terme exacte perquè es pregunta sovint amb distractors molt propers.',
      explainEs: 'El artículo 1.3 dice literalmente que la forma política del Estado español es la monarquía parlamentaria. Conviene recordar el término exacto porque se pregunta a menudo con distractores muy próximos.',
      refs: [ref('ce-1978', 'art. 1.3')],
      difficulty: 'facil',
    },
  ]),

  ...questionsFor(2, [
    {
      n: 1,
      stem: 'El recurs d’empara davant el Tribunal Constitucional protegeix:',
      options: [
        'Tots els drets i deures del títol I de la Constitució',
        'L’article 14, els articles 15 a 29 i l’objecció de consciència de l’article 30.2',
        'Només els articles 15 a 29',
        'Els principis rectors de la política social i econòmica',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La secció 2a i el capítol III del títol I no tenen empara constitucional.',
        c: 'Deixa fora l’article 14 i l’objecció de consciència, que sí que estan emparats.',
        d: 'Els principis rectors només es poden al·legar d’acord amb el que disposin les lleis que els desenvolupin.',
      },
      explainCa: 'L’article 53.2 estableix que qualsevol ciutadà pot recabar la tutela de les llibertats i drets reconeguts a l’article 14 i a la secció 1a del capítol II (articles 15 a 29), i aquesta protecció s’estén també a l’objecció de consciència de l’article 30.2.',
      explainEs: 'El artículo 53.2 establece que cualquier ciudadano puede recabar la tutela de las libertades y derechos reconocidos en el artículo 14 y en la sección 1ª del capítulo II (artículos 15 a 29), y esta protección se extiende también a la objeción de conciencia del artículo 30.2.',
      refs: [ref('ce-1978', 'art. 53.2')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quina és la durada màxima de la detenció preventiva segons l’article 17.2 de la Constitució?',
      options: ['24 hores', '48 hores', '72 hores', '96 hores'],
      correct: 'c',
      whyWrong: {
        a: '24 hores és el termini màxim de detenció d’un menor i el termini per resoldre un habeas corpus, no el general.',
        b: 'No correspon a cap termini constitucional.',
        d: 'La pròrroga fins a 5 dies és possible en supòsits de terrorisme, però no és el termini de l’article 17.2.',
      },
      explainCa: 'La detenció preventiva no pot durar més del temps estrictament necessari per fer les esbrinacions tendents a l’esclariment dels fets i, en tot cas, dins el termini màxim de setanta-dues hores la persona detinguda ha de ser posada en llibertat o a disposició de l’autoritat judicial.',
      explainEs: 'La detención preventiva no puede durar más del tiempo estrictamente necesario para realizar las averiguaciones tendentes al esclarecimiento de los hechos y, en todo caso, dentro del plazo máximo de setenta y dos horas la persona detenida debe ser puesta en libertad o a disposición de la autoridad judicial.',
      refs: [ref('ce-1978', 'art. 17.2')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'La suspensió individual de drets prevista a l’article 55.2 de la Constitució, en relació amb bandes armades o terrorisme, pot afectar:',
      options: [
        'El dret de reunió i el de manifestació',
        'El termini màxim de detenció preventiva, la inviolabilitat del domicili i el secret de les comunicacions',
        'El dret a la tutela judicial efectiva',
        'La llibertat de circulació i de residència',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El dret de reunió només es pot suspendre de manera general en estat d’excepció o de setge.',
        c: 'La tutela judicial efectiva no és suspendible en cap cas.',
        d: 'La llibertat de circulació entra a la suspensió general de l’article 55.1, no a la individual.',
      },
      explainCa: 'L’article 55.2 permet, mitjançant llei orgànica i amb la necessària intervenció judicial i el control parlamentari adequat, suspendre de forma individual els drets dels articles 17.2 (termini de detenció), 18.2 (inviolabilitat del domicili) i 18.3 (secret de les comunicacions) per a persones determinades en relació amb investigacions sobre bandes armades o elements terroristes.',
      explainEs: 'El artículo 55.2 permite, mediante ley orgánica y con la necesaria intervención judicial y el adecuado control parlamentario, suspender de forma individual los derechos de los artículos 17.2 (plazo de detención), 18.2 (inviolabilidad del domicilio) y 18.3 (secreto de las comunicaciones) para personas determinadas en relación con investigaciones sobre bandas armadas o elementos terroristas.',
      refs: [ref('ce-1978', 'art. 55')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'El dret de reunió pacífica i sense armes reconegut a l’article 21 de la Constitució:',
      options: [
        'Requereix autorització prèvia de l’autoritat governativa',
        'No requereix autorització prèvia; en llocs de trànsit públic i manifestacions cal comunicació prèvia',
        'Només es pot exercir en recintes tancats',
        'Requereix autorització judicial quan es faci a la via pública',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La Constitució exclou expressament l’autorització prèvia.',
        c: 'L’article 21 no limita el dret a recintes tancats.',
        d: 'No hi ha autorització judicial prèvia; l’autoritat governativa només pot prohibir per raons fonamentades d’alteració de l’ordre públic amb perill per a persones o béns.',
      },
      explainCa: 'L’article 21.1 reconeix el dret de reunió pacífica i sense armes sense necessitat d’autorització prèvia. L’apartat 2 exigeix comunicació prèvia a l’autoritat en els casos de reunions en llocs de trànsit públic i de manifestacions; l’autoritat només les pot prohibir quan hi hagi raons fonamentades d’alteració de l’ordre públic amb perill per a persones o béns.',
      explainEs: 'El artículo 21.1 reconoce el derecho de reunión pacífica y sin armas sin necesidad de autorización previa. El apartado 2 exige comunicación previa a la autoridad en los casos de reuniones en lugares de tránsito público y de manifestaciones; la autoridad solo puede prohibirlas cuando existan razones fundadas de alteración del orden público con peligro para personas o bienes.',
      refs: [ref('ce-1978', 'art. 21')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'El Defensor del Poble és:',
      options: [
        'Un òrgan del poder judicial',
        'Un alt comissionat de les Corts Generals designat per aquestes',
        'Un òrgan dependent del Govern',
        'Un magistrat del Tribunal Constitucional amb funcions especials',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No forma part del poder judicial ni exerceix funcions jurisdiccionals.',
        c: 'És independent del Govern; precisament supervisa l’activitat de l’Administració.',
        d: 'No és membre del Tribunal Constitucional, tot i que està legitimat per interposar recurs d’empara i d’inconstitucionalitat.',
      },
      explainCa: 'L’article 54 configura el Defensor del Poble com a alt comissionat de les Corts Generals, designat per aquestes per a la defensa dels drets del títol I, i li atribueix la facultat de supervisar l’activitat de l’Administració, donant-ne compte a les Corts.',
      explainEs: 'El artículo 54 configura al Defensor del Pueblo como alto comisionado de las Cortes Generales, designado por estas para la defensa de los derechos del título I, y le atribuye la facultad de supervisar la actividad de la Administración, dando cuenta de ello a las Cortes.',
      refs: [ref('ce-1978', 'art. 54')],
      difficulty: 'facil',
    },
  ]),

  ...questionsFor(3, [
    {
      n: 1,
      stem: 'L’Estatut d’autonomia de Catalunya vigent va ser aprovat per:',
      options: [
        'La Llei orgànica 4/1979, de 18 de desembre',
        'La Llei orgànica 6/2006, de 19 de juliol',
        'La Llei 6/2006, de 19 de juliol',
        'El Decret 306/2006, de 20 de juliol',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És l’Estatut de Sau, de 1979, substituït per l’actual.',
        c: 'Un estatut d’autonomia s’aprova sempre per llei orgànica, no per llei ordinària.',
        d: 'Aquest decret només va donar publicitat a la llei orgànica; no és la norma aprovatòria.',
      },
      explainCa: 'L’Estatut vigent és la Llei orgànica 6/2006, de 19 de juliol, de reforma de l’Estatut d’autonomia de Catalunya, que va substituir l’Estatut de 1979.',
      explainEs: 'El Estatuto vigente es la Ley orgánica 6/2006, de 19 de julio, de reforma del Estatuto de autonomía de Cataluña, que sustituyó al Estatuto de 1979.',
      refs: [ref('lo-6-2006-eac', 'norma aprovatòria')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Segons l’Estatut, la llengua pròpia de Catalunya és:',
      options: [
        'El català, que és també llengua oficial juntament amb el castellà',
        'El català i el castellà, totes dues llengües pròpies',
        'El castellà, i el català és llengua cooficial',
        'El català, única llengua oficial de Catalunya',
      ],
      correct: 'a',
      whyWrong: {
        b: 'La llengua pròpia és només el català; el castellà és oficial però no es qualifica de pròpia.',
        c: 'Inverteix els termes de l’Estatut.',
        d: 'El castellà també és oficial a Catalunya, i l’aranès ho és igualment.',
      },
      explainCa: 'L’Estatut estableix que la llengua pròpia de Catalunya és el català i que és també, com el castellà, llengua oficial. L’aranès, variant de l’occità, és la llengua pròpia de l’Aran i també és oficial a Catalunya.',
      explainEs: 'El Estatuto establece que la lengua propia de Cataluña es el catalán y que es también, como el castellano, lengua oficial. El aranés, variante del occitano, es la lengua propia del Arán y también es oficial en Cataluña.',
      refs: [ref('lo-6-2006-eac', 'drets i deures lingüístics')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'El dret d’opció lingüística reconegut per l’Estatut implica que:',
      options: [
        'Les administracions poden triar en quina llengua atenen la ciutadania',
        'Les persones tenen dret a ser ateses en la llengua oficial que triïn',
        'Només es pot exercir davant l’Administració de la Generalitat',
        'Cal sol·licitar-lo prèviament per escrit',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’opció correspon a la persona, no a l’Administració.',
        c: 'També vincula els ens locals i, en els termes previstos, l’Administració de l’Estat a Catalunya.',
        d: 'No requereix cap sol·licitud prèvia.',
      },
      explainCa: 'El dret d’opció lingüística permet a qualsevol persona adreçar-se a les administracions i ser-hi atesa en la llengua oficial que esculli, sense que se li pugui exigir cap tipus de traducció. Per a un agent de policia local, això vol dir estar en condicions d’atendre en català i en castellà.',
      explainEs: 'El derecho de opción lingüística permite a cualquier persona dirigirse a las administraciones y ser atendida en la lengua oficial que escoja, sin que se le pueda exigir ningún tipo de traducción. Para un agente de policía local, esto significa estar en condiciones de atender en catalán y en castellano.',
      refs: [ref('lo-6-2006-eac', 'drets lingüístics davant les administracions')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quina sentència del Tribunal Constitucional va declarar inconstitucionals o va reinterpretar diversos preceptes de l’Estatut de 2006?',
      options: [
        'La STC 31/2010',
        'La STC 76/1983',
        'La STC 4/1981',
        'La STC 259/2015',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Resol sobre la LOAPA, molt anterior a l’Estatut de 2006.',
        c: 'És una sentència primerenca sobre autonomia local.',
        d: 'No és la sentència sobre l’Estatut de 2006.',
      },
      explainCa: 'La sentència 31/2010 del Tribunal Constitucional va resoldre el recurs d’inconstitucionalitat contra l’Estatut de 2006 i va declarar inconstitucionals alguns preceptes i va fixar la interpretació conforme d’altres. Per això cal treballar sempre amb el text consolidat i comprovar si l’article estudiat està afectat.',
      explainEs: 'La sentencia 31/2010 del Tribunal Constitucional resolvió el recurso de inconstitucionalidad contra el Estatuto de 2006 y declaró inconstitucionales algunos preceptos y fijó la interpretación conforme de otros. Por eso hay que trabajar siempre con el texto consolidado y comprobar si el artículo estudiado está afectado.',
      refs: [ref('lo-6-2006-eac', 'text consolidat després de la STC 31/2010')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Segons l’Estatut, quin és l’ens bàsic de l’organització territorial de Catalunya i del govern local?',
      options: ['La comarca', 'La vegueria', 'El municipi', 'La província'],
      correct: 'c',
      whyWrong: {
        a: 'La comarca és un ens supramunicipal de cooperació.',
        b: 'La vegueria és l’àmbit territorial específic per a l’exercici del govern intermunicipal de cooperació local.',
        d: 'La província té la seva pròpia configuració constitucional, però l’ens bàsic és el municipi.',
      },
      explainCa: 'L’Estatut reconeix el municipi com a ens bàsic de l’organització territorial de Catalunya i com a mitjà essencial de participació de la comunitat local en els afers públics, en la mateixa línia que la legislació bàsica de règim local.',
      explainEs: 'El Estatuto reconoce el municipio como ente básico de la organización territorial de Cataluña y como medio esencial de participación de la comunidad local en los asuntos públicos, en la misma línea que la legislación básica de régimen local.',
      refs: [ref('lo-6-2006-eac', 'govern local'), ref('llei-7-1985-lrbrl', 'art. 1 i 11')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(4, [
    {
      n: 1,
      stem: 'El president o presidenta de la Generalitat de Catalunya és:',
      options: [
        'Nomenat directament pel Rei entre els diputats',
        'Elegit pel Parlament d’entre els seus membres i nomenat pel Rei',
        'Elegit directament per la ciutadania en les eleccions',
        'Designat pel Govern de l’Estat a proposta del Parlament',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El Rei nomena, però no tria: qui elegeix és el Parlament.',
        c: 'L’elecció és parlamentària, no directa.',
        d: 'El Govern de l’Estat no intervé en la designació.',
      },
      explainCa: 'El president de la Generalitat és elegit pel Parlament d’entre els seus membres i nomenat pel Rei. Té la més alta representació de la Generalitat i, alhora, la representació ordinària de l’Estat a Catalunya.',
      explainEs: 'El presidente de la Generalitat es elegido por el Parlamento de entre sus miembros y nombrado por el Rey. Tiene la más alta representación de la Generalitat y, a la vez, la representación ordinaria del Estado en Cataluña.',
      refs: [ref('lo-6-2006-eac', 'la Presidència de la Generalitat')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'La durada ordinària del mandat del Parlament de Catalunya és de:',
      options: ['Quatre anys', 'Cinc anys', 'Sis anys', 'Tres anys'],
      correct: 'a',
      whyWrong: {
        b: 'Cinc anys és el mandat dels vocals del Consell General del Poder Judicial.',
        c: 'No correspon a cap mandat parlamentari.',
        d: 'No correspon a cap mandat parlamentari.',
      },
      explainCa: 'Els diputats del Parlament de Catalunya són elegits per un mandat de quatre anys, mitjançant sufragi universal, lliure, igual, directe i secret, sens perjudici de la possibilitat de dissolució anticipada.',
      explainEs: 'Los diputados del Parlamento de Cataluña son elegidos por un mandato de cuatro años, mediante sufragio universal, libre, igual, directo y secreto, sin perjuicio de la posibilidad de disolución anticipada.',
      refs: [ref('lo-6-2006-eac', 'el Parlament')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'La relació entre la Generalitat i les policies locals de Catalunya és de:',
      options: [
        'Dependència jeràrquica directa del Departament d’Interior',
        'Coordinació, mantenint la dependència de l’alcalde o alcaldessa',
        'Independència total, sense cap relació institucional',
        'Tutela financera exclusivament',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Les policies locals depenen de l’alcalde, no del Departament d’Interior.',
        c: 'Hi ha un sistema de seguretat pública integrat que les vincula.',
        d: 'La coordinació va molt més enllà de la vessant financera.',
      },
      explainCa: 'La Generalitat té competència sobre la coordinació de les policies locals, però aquestes depenen jeràrquicament de l’alcalde o alcaldessa del municipi. Coordinar inclou homogeneïtzar mitjans, formació, uniformitat i criteris d’actuació, però no substituir el comandament municipal.',
      explainEs: 'La Generalitat tiene competencia sobre la coordinación de las policías locales, pero estas dependen jerárquicamente del alcalde o alcaldesa del municipio. Coordinar incluye homogeneizar medios, formación, uniformidad y criterios de actuación, pero no sustituir el mando municipal.',
      refs: [
        ref('lo-6-2006-eac', 'competències en seguretat pública'),
        ref('llei-16-1991-policies-locals', 'dependència dels cossos de policia local'),
      ],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quin és l’òrgan superior col·legiat que dirigeix l’acció política i l’Administració de la Generalitat?',
      options: [
        'El Parlament de Catalunya',
        'El Govern o Consell Executiu',
        'El Consell de Garanties Estatutàries',
        'La Sindicatura de Comptes',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El Parlament exerceix la potestat legislativa i el control, no la direcció executiva.',
        c: 'És un òrgan consultiu sobre l’adequació de les normes a l’Estatut i a la Constitució.',
        d: 'És l’òrgan fiscalitzador extern dels comptes i de la gestió econòmica.',
      },
      explainCa: 'El Govern o Consell Executiu és l’òrgan superior col·legiat que dirigeix l’acció política i l’Administració de la Generalitat, i exerceix la funció executiva i la potestat reglamentària.',
      explainEs: 'El Gobierno o Consejo Ejecutivo es el órgano superior colegiado que dirige la acción política y la Administración de la Generalitat, y ejerce la función ejecutiva y la potestad reglamentaria.',
      refs: [ref('lo-6-2006-eac', 'el Govern')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'La formació dels membres dels cossos de policia local de Catalunya correspon principalment a:',
      options: [
        'L’Escola Nacional de Policia d’Àvila',
        'L’Institut de Seguretat Pública de Catalunya',
        'Cada ajuntament de manera autònoma',
        'La Direcció General de la Policia de l’Estat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Forma els membres del Cos Nacional de Policia.',
        c: 'Els ajuntaments seleccionen, però la formació bàsica és centralitzada.',
        d: 'No té competències sobre policies locals de Catalunya.',
      },
      explainCa: 'L’Institut de Seguretat Pública de Catalunya és el centre de la Generalitat encarregat de la formació dels cossos policials de Catalunya, inclosos els agents de les policies locals, com a instrument del sistema de seguretat pública.',
      explainEs: 'El Instituto de Seguridad Pública de Cataluña es el centro de la Generalitat encargado de la formación de los cuerpos policiales de Cataluña, incluidos los agentes de las policías locales, como instrumento del sistema de seguridad pública.',
      refs: [ref('llei-4-2003-seguretat-publica', 'formació i coordinació policial')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(5, [
    {
      n: 1,
      stem: 'Quins són els tres elements del municipi segons la legislació bàsica de règim local?',
      options: [
        'Territori, població i organització',
        'Territori, pressupost i alcaldia',
        'Població, padró i ple municipal',
        'Terme municipal, veïnat i ordenances',
      ],
      correct: 'a',
      whyWrong: {
        b: 'El pressupost és un instrument de gestió, no un element constitutiu.',
        c: 'El padró és l’instrument on consta la població, no un element autònom.',
        d: 'Les ordenances són producte de la potestat reglamentària, no un element del municipi.',
      },
      explainCa: 'La llei defineix el municipi com l’entitat local bàsica de l’organització territorial de l’Estat, amb personalitat jurídica i plena capacitat, i n’identifica com a elements el territori, la població i l’organització.',
      explainEs: 'La ley define el municipio como la entidad local básica de la organización territorial del Estado, con personalidad jurídica y plena capacidad, e identifica como sus elementos el territorio, la población y la organización.',
      refs: [ref('llei-7-1985-lrbrl', 'art. 11')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Qui té la condició de veí d’un municipi?',
      options: [
        'Qualsevol persona que hi resideixi de fet',
        'Qui estigui inscrit al padró municipal d’habitants',
        'Qui hi tingui un immoble en propietat',
        'Qui hi pagui l’impost sobre béns immobles',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Residir de fet no atorga la condició jurídica de veí sense inscripció padronal.',
        c: 'La propietat immobiliària no determina el veïnatge.',
        d: 'Ser subjecte passiu d’un tribut no és el criteri legal.',
      },
      explainCa: 'El conjunt de persones inscrites al padró municipal constitueix la població del municipi, i les persones inscrites en són veïnes. La inscripció al padró és, doncs, el fet determinant de la condició de veí, amb els drets i deures que comporta.',
      explainEs: 'El conjunto de personas inscritas en el padrón municipal constituye la población del municipio, y las personas inscritas son sus vecinas. La inscripción en el padrón es, pues, el hecho determinante de la condición de vecino, con los derechos y deberes que conlleva.',
      refs: [ref('llei-7-1985-lrbrl', 'art. 15 i 16')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Quin d’aquests òrgans NO és d’existència obligatòria en tots els municipis?',
      options: [
        'L’alcalde o alcaldessa',
        'El ple',
        'La junta de govern local',
        'Els tinents d’alcalde',
      ],
      correct: 'c',
      whyWrong: {
        a: 'És sempre obligatori.',
        b: 'És sempre obligatori.',
        d: 'Són sempre obligatoris i els nomena l’alcalde entre els membres de la junta de govern o, si no n’hi ha, entre els regidors.',
      },
      explainCa: 'L’alcalde, els tinents d’alcalde i el ple existeixen en tots els ajuntaments. La junta de govern local només és obligatòria als municipis amb població superior a cinc mil habitants i en aquells en què ho disposi el seu reglament orgànic o ho acordi el ple.',
      explainEs: 'El alcalde, los tenientes de alcalde y el pleno existen en todos los ayuntamientos. La junta de gobierno local solo es obligatoria en los municipios con población superior a cinco mil habitantes y en aquellos en que lo disponga su reglamento orgánico o lo acuerde el pleno.',
      refs: [ref('llei-7-1985-lrbrl', 'art. 20')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'Quina d’aquestes és una competència pròpia del municipi en matèria de seguretat?',
      options: [
        'La direcció de la investigació de delictes greus',
        'La policia local i la seguretat en llocs públics',
        'La gestió del sistema penitenciari',
        'L’expedició del document nacional d’identitat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Correspon a la policia judicial sota direcció del jutge o del Ministeri Fiscal.',
        c: 'És competència autonòmica o estatal, mai municipal.',
        d: 'És competència de l’Administració General de l’Estat.',
      },
      explainCa: 'La legislació bàsica de règim local atribueix als municipis, entre les competències pròpies, la policia local i la seguretat en llocs públics, així com el trànsit, l’estacionament de vehicles i la mobilitat, i la protecció civil i la prevenció i extinció d’incendis.',
      explainEs: 'La legislación básica de régimen local atribuye a los municipios, entre las competencias propias, la policía local y la seguridad en lugares públicos, así como el tráfico, el estacionamiento de vehículos y la movilidad, y la protección civil y la prevención y extinción de incendios.',
      refs: [ref('llei-7-1985-lrbrl', 'art. 25')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'La presumpció de legitimitat i l’executivitat dels actes municipals és:',
      options: [
        'Una obligació imposada als ajuntaments',
        'Una potestat reconeguda als municipis per la legislació de règim local',
        'Una regla exclusiva de l’Administració de l’Estat',
        'Un privilegi que requereix autorització judicial prèvia',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És una prerrogativa a favor del municipi, no una càrrega.',
        c: 'La llei l’atribueix expressament també als ens locals.',
        d: 'Precisament permet actuar sense autorització judicial prèvia.',
      },
      explainCa: 'Entre les potestats que la legislació bàsica reconeix als municipis hi ha la presumpció de legitimitat i l’executivitat dels seus actes, juntament amb les potestats d’execució forçosa i sancionadora. Per això una ordenança o una sanció desplega efectes tot i que s’hagi recorregut, llevat que se’n suspengui l’execució.',
      explainEs: 'Entre las potestades que la legislación básica reconoce a los municipios está la presunción de legitimidad y la ejecutividad de sus actos, junto con las potestades de ejecución forzosa y sancionadora. Por eso una ordenanza o una sanción despliega efectos aunque se haya recurrido, salvo que se suspenda su ejecución.',
      refs: [ref('llei-7-1985-lrbrl', 'art. 4')],
      difficulty: 'dificil',
    },
  ]),
]
