import type { Question } from '../../../schemas/index.ts'
import { questionsFor, ref } from '../authoring.ts'

export const QUESTIONS_11_15: Question[] = [
  ...questionsFor(11, [
    {
      n: 1,
      stem: 'El règim disciplinari dels cossos de policia local de Catalunya es regula principalment a:',
      options: [
        'L’Estatut bàsic de l’empleat públic exclusivament',
        'La Llei 16/1991 i el Decret 179/2015',
        'La Llei orgànica 2/1986 de forces i cossos de seguretat',
        'El reglament orgànic de cada ajuntament',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’EBEP té caràcter supletori en aquesta matèria.',
        c: 'Fixa principis d’actuació, però no el règim disciplinari de les policies locals catalanes.',
        d: 'El reglament municipal desenvolupa aspectes organitzatius, no el règim disciplinari.',
      },
      explainCa: 'La Llei 16/1991 de les policies locals conté el règim disciplinari propi i el Decret 179/2015 aprova el reglament del procediment aplicable. L’Estatut bàsic de l’empleat públic actua com a norma supletòria.',
      explainEs: 'La Ley 16/1991 de las policías locales contiene el régimen disciplinario propio y el Decreto 179/2015 aprueba el reglamento del procedimiento aplicable. El Estatuto básico del empleado público actúa como norma supletoria.',
      refs: [
        ref('llei-16-1991-policies-locals', 'règim disciplinari'),
        ref('decret-179-2015-disciplinari', 'reglament del procediment'),
      ],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Com es classifiquen les faltes disciplinàries dels membres dels cossos de policia local?',
      options: [
        'Greus i lleus',
        'Molt greus, greus i lleus',
        'Molt greus i greus',
        'Lleus, greus, molt greus i gravíssimes',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Falta la categoria de molt greus.',
        c: 'Falta la categoria de lleus.',
        d: 'No existeix la categoria de «gravíssimes».',
      },
      explainCa: 'Les faltes disciplinàries es classifiquen en molt greus, greus i lleus, i a cada categoria li correspon un ventall propi de sancions i un règim de prescripció diferenciat.',
      explainEs: 'Las faltas disciplinarias se clasifican en muy graves, graves y leves, y a cada categoría le corresponde un abanico propio de sanciones y un régimen de prescripción diferenciado.',
      refs: [ref('llei-16-1991-policies-locals', 'classificació de les faltes')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'La suspensió provisional de funcions durant la tramitació d’un expedient disciplinari és:',
      options: [
        'Una sanció anticipada',
        'Una mesura cautelar que no prejutja el resultat de l’expedient',
        'Una conseqüència automàtica de tota incoació',
        'Una decisió que només pot adoptar un jutge',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No és una sanció: no hi ha declaració de responsabilitat.',
        c: 'S’ha d’acordar motivadament, no és automàtica.',
        d: 'L’acorda l’òrgan administratiu competent dins el procediment disciplinari.',
      },
      explainCa: 'La suspensió provisional és una mesura cautelar que es pot adoptar durant la instrucció per assegurar l’eficàcia de la resolució o evitar la persistència dels efectes de la infracció. Si l’expedient acaba sense sanció, la persona ha de ser reposada en els seus drets.',
      explainEs: 'La suspensión provisional es una medida cautelar que puede adoptarse durante la instrucción para asegurar la eficacia de la resolución o evitar la persistencia de los efectos de la infracción. Si el expediente acaba sin sanción, la persona debe ser repuesta en sus derechos.',
      refs: [ref('decret-179-2015-disciplinari', 'mesures cautelars')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quina és la sanció més greu prevista per a una falta molt greu d’un membre d’un cos de policia local?',
      options: [
        'La suspensió de funcions',
        'La separació del servei',
        'El trasllat forçós de lloc de treball',
        'La destitució del càrrec de comandament',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És greu, però no la màxima.',
        c: 'No és la sanció màxima.',
        d: 'Correspon típicament a faltes greus i afecta el càrrec, no la condició de funcionari.',
      },
      explainCa: 'La separació del servei és la sanció més greu del catàleg disciplinari: comporta la pèrdua de la condició de funcionari i només es pot imposar per faltes molt greus, després d’un expedient amb totes les garanties.',
      explainEs: 'La separación del servicio es la sanción más grave del catálogo disciplinario: comporta la pérdida de la condición de funcionario y solo puede imponerse por faltas muy graves, tras un expediente con todas las garantías.',
      refs: [ref('llei-16-1991-policies-locals', 'catàleg de sancions')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'En la graduació de la sanció disciplinària NO es té en compte:',
      options: [
        'La intencionalitat',
        'La pertorbació del servei',
        'La reincidència',
        'La situació econòmica de la persona expedientada',
      ],
      correct: 'd',
      whyWrong: {
        a: 'És un criteri de graduació habitual.',
        b: 'És un criteri de graduació habitual.',
        c: 'És un criteri de graduació habitual.',
      },
      explainCa: 'Els criteris de graduació de les sancions disciplinàries són la intencionalitat, la pertorbació del servei, els danys i perjudicis causats a l’Administració o a la ciutadania, la reincidència i el grau de participació. La capacitat econòmica és un criteri propi de les multes administratives, no de les sancions disciplinàries.',
      explainEs: 'Los criterios de graduación de las sanciones disciplinarias son la intencionalidad, la perturbación del servicio, los daños y perjuicios causados a la Administración o a la ciudadanía, la reincidencia y el grado de participación. La capacidad económica es un criterio propio de las multas administrativas, no de las sanciones disciplinarias.',
      refs: [ref('llei-16-1991-policies-locals', 'graduació de les sancions')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(12, [
    {
      n: 1,
      stem: 'Quina llei regula el procediment administratiu comú de les administracions públiques?',
      options: ['La Llei 40/2015', 'La Llei 39/2015', 'La Llei 30/1992', 'La Llei 19/2013'],
      correct: 'b',
      whyWrong: {
        a: 'Regula el règim jurídic del sector públic.',
        c: 'Va ser derogada per les lleis 39/2015 i 40/2015.',
        d: 'Regula la transparència i el bon govern.',
      },
      explainCa: 'La Llei 39/2015, d’1 d’octubre, regula el procediment administratiu comú de les administracions públiques, és a dir, les relacions «cap enfora» amb la ciutadania. La seva bessona, la Llei 40/2015, regula el funcionament intern del sector públic.',
      explainEs: 'La Ley 39/2015, de 1 de octubre, regula el procedimiento administrativo común de las administraciones públicas, es decir, las relaciones «hacia fuera» con la ciudadanía. Su gemela, la Ley 40/2015, regula el funcionamiento interno del sector público.',
      refs: [ref('llei-39-2015-pac', 'objecte i àmbit')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Quan un agent de la Policia Local de Roses formula una denúncia per infracció de l’ordenança de convivència:',
      options: [
        'Imposa directament la sanció corresponent',
        'Inicia el procediment sancionador, que resoldrà l’òrgan competent',
        'Trasllada l’assumpte al jutjat de guàrdia',
        'Aplica la sanció si la persona denunciada la reconeix',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La sanció l’imposa l’òrgan competent, no l’agent denunciant.',
        c: 'Es tracta d’una infracció administrativa, no penal.',
        d: 'El reconeixement pot comportar reducció d’import, però no substitueix la resolució.',
      },
      explainCa: 'La denúncia és un acte d’iniciació del procediment. La sanció només es pot imposar mitjançant resolució de l’òrgan competent, després de donar audiència a la persona interessada i de respectar la presumpció d’innocència.',
      explainEs: 'La denuncia es un acto de iniciación del procedimiento. La sanción solo puede imponerse mediante resolución del órgano competente, tras dar audiencia a la persona interesada y respetar la presunción de inocencia.',
      refs: [ref('llei-39-2015-pac', 'art. 54, 58 i 63')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Quin d’aquests principis és específic de la potestat sancionadora?',
      options: [
        'El principi d’oficialitat',
        'El principi de tipicitat',
        'El principi de celeritat',
        'El principi de contradicció',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És un principi general del procediment.',
        c: 'És un principi general del procediment.',
        d: 'És un principi general del procediment.',
      },
      explainCa: 'Els principis específics de la potestat sancionadora són la legalitat, la tipicitat, la irretroactivitat, la responsabilitat, la proporcionalitat, la prescripció i el non bis in idem. La tipicitat exigeix que la infracció i la sanció estiguin previstes en una norma amb rang suficient.',
      explainEs: 'Los principios específicos de la potestad sancionadora son la legalidad, la tipicidad, la irretroactividad, la responsabilidad, la proporcionalidad, la prescripción y el non bis in idem. La tipicidad exige que la infracción y la sanción estén previstas en una norma con rango suficiente.',
      refs: [ref('llei-40-2015-rjsp', 'art. 25 a 31')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'La presumpció d’innocència en el procediment administratiu sancionador:',
      options: [
        'No s’aplica perquè no és un procés penal',
        'S’aplica plenament i correspon a l’Administració provar els fets',
        'S’aplica només si la sanció supera un determinat import',
        'Queda desvirtuada automàticament per la denúncia d’un agent',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Les garanties penals s’apliquen, amb matisos, al dret administratiu sancionador.',
        c: 'La quantia no condiciona les garanties.',
        d: 'La denúncia d’un agent té valor probatori qualificat, però admet prova en contra.',
      },
      explainCa: 'Els procediments sancionadors respecten la presumpció d’innocència: correspon a l’Administració acreditar els fets. Les denúncies formulades per agents de l’autoritat tenen valor probatori qualificat pel que fa als fets constatats directament, però sempre admeten prova en contra.',
      explainEs: 'Los procedimientos sancionadores respetan la presunción de inocencia: corresponde a la Administración acreditar los hechos. Las denuncias formuladas por agentes de la autoridad tienen valor probatorio cualificado en cuanto a los hechos constatados directamente, pero siempre admiten prueba en contra.',
      refs: [ref('llei-39-2015-pac', 'art. 53.2 i 77'), ref('ce-1978', 'art. 24.2')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'El principi d’oficialitat en el procediment administratiu significa que:',
      options: [
        'Només l’Administració pot iniciar procediments',
        'L’Administració ha d’impulsar el procediment d’ofici en totes les seves fases',
        'Els actes han de constar sempre per escrit',
        'Les persones interessades no poden proposar prova',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Els procediments també s’inicien a sol·licitud de la persona interessada.',
        c: 'La forma escrita és un requisit dels actes, no el principi d’oficialitat.',
        d: 'Les persones interessades sí que poden proposar prova.',
      },
      explainCa: 'El principi d’oficialitat obliga l’Administració a impulsar d’ofici el procediment en totes les seves fases, sense esperar que la persona interessada ho demani, i a acordar simultàniament els tràmits que admetin un impuls simultani.',
      explainEs: 'El principio de oficialidad obliga a la Administración a impulsar de oficio el procedimiento en todas sus fases, sin esperar a que la persona interesada lo pida, y a acordar simultáneamente los trámites que admitan un impulso simultáneo.',
      refs: [ref('llei-39-2015-pac', 'art. 71')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(13, [
    {
      n: 1,
      stem: 'En quin termini s’ha de notificar una resolució administrativa des que es dicta l’acte?',
      options: ['5 dies', '10 dies', '15 dies', '1 mes'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon al termini legal de notificació.',
        c: '15 dies és el període d’exposició pública del pressupost, entre altres.',
        d: 'Un mes és el termini d’interposició de recursos, no de notificació.',
      },
      explainCa: 'Tota resolució s’ha de notificar a les persones interessades en el termini de deu dies a partir de la data en què l’acte s’hagi dictat, amb el text íntegre, la indicació de si posa fi a la via administrativa i els recursos procedents.',
      explainEs: 'Toda resolución debe notificarse a las personas interesadas en el plazo de diez días a partir de la fecha en que el acto se haya dictado, con el texto íntegro, la indicación de si pone fin a la vía administrativa y los recursos procedentes.',
      refs: [ref('llei-39-2015-pac', 'art. 40')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quin d’aquests supòsits és causa de nul·litat de ple dret d’un acte administratiu?',
      options: [
        'Que l’hagi dictat un òrgan inferior en lloc del superior jeràrquic',
        'Que l’hagi dictat un òrgan manifestament incompetent per raó de la matèria o del territori',
        'Que contingui un defecte de forma sense indefensió',
        'Que s’hagi dictat fora de termini quan el termini no és essencial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La incompetència jeràrquica és causa d’anul·labilitat i, a més, convalidable.',
        c: 'Un defecte de forma sense indefensió és una simple irregularitat no invalidant.',
        d: 'L’extemporaneïtat només invalida quan la naturalesa del termini ho imposa.',
      },
      explainCa: 'Són nuls de ple dret, entre altres, els actes que lesionen drets susceptibles d’empara constitucional, els dictats per òrgan manifestament incompetent per raó de la matèria o del territori, els de contingut impossible, els constitutius d’infracció penal i els dictats prescindint totalment del procediment.',
      explainEs: 'Son nulos de pleno derecho, entre otros, los actos que lesionan derechos susceptibles de amparo constitucional, los dictados por órgano manifiestamente incompetente por razón de la materia o del territorio, los de contenido imposible, los constitutivos de infracción penal y los dictados prescindiendo total y absolutamente del procedimiento.',
      refs: [ref('llei-39-2015-pac', 'art. 47')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'Quins actes administratius han de ser motivats?',
      options: [
        'Tots, sense excepció',
        'Només els sancionadors',
        'Els que limiten drets subjectius, resolen recursos, se separen del criteri precedent, els sancionadors i els discrecionals, entre altres',
        'Cap, perquè es presumeixen legítims',
      ],
      correct: 'c',
      whyWrong: {
        a: 'La llei enumera supòsits concrets, no imposa motivació universal.',
        b: 'Els sancionadors són només un dels supòsits.',
        d: 'La presumpció de legitimitat no eximeix de motivar.',
      },
      explainCa: 'La llei exigeix motivació, amb referència succinta de fets i fonaments de dret, per als actes que limiten drets subjectius o interessos legítims, els que resolen procediments de revisió o recursos, els que se separen del criteri seguit en actuacions precedents, els sancionadors, els que suspenen actes i els que s’adopten en exercici de potestats discrecionals, entre altres.',
      explainEs: 'La ley exige motivación, con sucinta referencia de hechos y fundamentos de derecho, para los actos que limitan derechos subjetivos o intereses legítimos, los que resuelven procedimientos de revisión o recursos, los que se apartan del criterio seguido en actuaciones precedentes, los sancionadores, los que suspenden actos y los que se adoptan en ejercicio de potestades discrecionales, entre otros.',
      refs: [ref('llei-39-2015-pac', 'art. 35')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Un acte anul·lable, a diferència d’un acte nul de ple dret:',
      options: [
        'No produeix cap efecte des de l’origen',
        'Produeix efectes fins que s’anul·la i pot ser convalidat',
        'No es pot impugnar mai',
        'Només pot ser declarat invàlid pel Tribunal Constitucional',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Aquesta és la característica de la nul·litat de ple dret.',
        c: 'Els actes anul·lables són plenament impugnables.',
        d: 'La jurisdicció competent és la contenciosa administrativa.',
      },
      explainCa: 'L’acte anul·lable és eficaç mentre no s’anul·li i, si el vici ho permet, es pot convalidar esmenant el defecte. L’acte nul de ple dret, en canvi, no produeix efectes des de l’origen i no admet convalidació.',
      explainEs: 'El acto anulable es eficaz mientras no se anule y, si el vicio lo permite, puede convalidarse subsanando el defecto. El acto nulo de pleno derecho, en cambio, no produce efectos desde el origen y no admite convalidación.',
      refs: [ref('llei-39-2015-pac', 'art. 47, 48 i 52')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Una notificació que ometi els recursos procedents:',
      options: [
        'És nul·la de ple dret i no produeix cap efecte',
        'Produeix efectes des que la persona interessada fa una actuació que en demostri el coneixement o interposa el recurs procedent',
        'Obliga a repetir tot el procediment des de l’inici',
        'És plenament vàlida perquè el peu de recurs és opcional',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei preveu una regla de convalidació, no la nul·litat automàtica.',
        c: 'Només cal esmenar la notificació, no repetir el procediment.',
        d: 'El peu de recurs és un contingut obligatori de la notificació.',
      },
      explainCa: 'Les notificacions que continguin el text íntegre de l’acte però ometin altres requisits produeixen efectes a partir de la data en què la persona interessada faci actuacions que suposin el coneixement del contingut i l’abast de la resolució, o interposi qualsevol recurs procedent.',
      explainEs: 'Las notificaciones que contengan el texto íntegro del acto pero omitan otros requisitos surten efecto a partir de la fecha en que la persona interesada realice actuaciones que supongan el conocimiento del contenido y alcance de la resolución, o interponga cualquier recurso procedente.',
      refs: [ref('llei-39-2015-pac', 'art. 40.3')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(14, [
    {
      n: 1,
      stem: 'Els menors d’edat davant l’Administració:',
      options: [
        'No tenen capacitat d’obrar en cap cas',
        'Tenen capacitat d’obrar per a l’exercici i la defensa dels drets que l’ordenament els permet sense assistència',
        'Només poden actuar mitjançant representant legal',
        'Tenen capacitat plena a partir dels setze anys',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei els reconeix expressament capacitat en determinats supòsits.',
        c: 'No sempre cal representant legal.',
        d: 'La llei no fixa aquest llindar general.',
      },
      explainCa: 'Tenen capacitat d’obrar davant les administracions, a més de les persones amb capacitat d’obrar segons les normes civils, els menors d’edat per a l’exercici i la defensa d’aquells dels seus drets i interessos l’actuació dels quals estigui permesa per l’ordenament sense l’assistència de qui n’exerceixi la pàtria potestat o la tutela.',
      explainEs: 'Tienen capacidad de obrar ante las administraciones, además de las personas con capacidad de obrar según las normas civiles, los menores de edad para el ejercicio y defensa de aquellos de sus derechos e intereses cuya actuación esté permitida por el ordenamiento sin la asistencia de quien ejerza la patria potestad o la tutela.',
      refs: [ref('llei-39-2015-pac', 'art. 3')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Qui presenta una denúncia administrativa adquireix per aquest sol fet la condició de persona interessada?',
      options: [
        'Sí, sempre',
        'No; cal ser titular d’un dret o interès legítim afectat',
        'Sí, si la denúncia prospera',
        'Només si la denúncia és per escrit',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La denúncia no atribueix per si mateixa la condició d’interessat.',
        c: 'El resultat del procediment no altera la condició d’interessat.',
        d: 'La forma de la denúncia és irrellevant a aquests efectes.',
      },
      explainCa: 'La presentació d’una denúncia no confereix, per si sola, la condició de persona interessada en el procediment. Per ser-ho cal promoure’l com a titular de drets o interessos legítims, o tenir drets o interessos legítims que puguin resultar afectats per la resolució.',
      explainEs: 'La presentación de una denuncia no confiere, por sí sola, la condición de persona interesada en el procedimiento. Para serlo hay que promoverlo como titular de derechos o intereses legítimos, o tener derechos o intereses legítimos que puedan resultar afectados por la resolución.',
      refs: [ref('llei-39-2015-pac', 'art. 4 i 62')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'Per a quin d’aquests actes NO cal acreditar la representació?',
      options: [
        'Interposar un recurs',
        'Renunciar a drets',
        'Realitzar actes de tràmit ordinari',
        'Formular sol·licituds',
      ],
      correct: 'c',
      whyWrong: {
        a: 'És un dels actes en què la llei exigeix acreditar la representació.',
        b: 'És un dels actes en què la llei exigeix acreditar la representació.',
        d: 'És un dels actes en què la llei exigeix acreditar la representació.',
      },
      explainCa: 'Cal acreditar la representació per formular sol·licituds, presentar declaracions responsables o comunicacions, interposar recursos, desistir d’accions i renunciar a drets en nom d’una altra persona. Per als actes i gestions de mer tràmit es presumeix la representació.',
      explainEs: 'Hay que acreditar la representación para formular solicitudes, presentar declaraciones responsables o comunicaciones, interponer recursos, desistir de acciones y renunciar a derechos en nombre de otra persona. Para los actos y gestiones de mero trámite se presume la representación.',
      refs: [ref('llei-39-2015-pac', 'art. 5')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quin d’aquests és un dret de les persones en les seves relacions amb les administracions públiques?',
      options: [
        'Obtenir sempre una resolució favorable',
        'No presentar documents ja aportats o elaborats per qualsevol Administració',
        'Escollir quin funcionari tramita el seu expedient',
        'Accedir a la informació reservada de la investigació',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El dret és a obtenir resposta, no a obtenir-la favorable.',
        c: 'La distribució de tasques és una decisió organitzativa interna.',
        d: 'L’accés a informació reservada està limitat per la llei.',
      },
      explainCa: 'Entre els drets de les persones hi ha el de no presentar dades o documents no exigits per les normes, ni documents que ja hagin estat aportats anteriorment per la persona interessada a qualsevol Administració o que hagin estat elaborats per aquestes.',
      explainEs: 'Entre los derechos de las personas está el de no presentar datos o documentos no exigidos por las normas, ni documentos que ya hayan sido aportados anteriormente por la persona interesada a cualquier Administración o que hayan sido elaborados por estas.',
      refs: [ref('llei-39-2015-pac', 'art. 13 i 53')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Una persona pot dirigir-se a l’Ajuntament de Roses en castellà i ser-hi atesa en aquesta llengua?',
      options: [
        'No, perquè el català és la llengua pròpia',
        'Sí, perquè el castellà també és llengua oficial i regeix el dret d’opció lingüística',
        'Només si acredita que no entén el català',
        'Només si presenta una traducció jurada',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Ser llengua pròpia no exclou l’oficialitat del castellà.',
        c: 'No cal acreditar res: l’opció és lliure.',
        d: 'Exigir traduccions a la persona interessada està prohibit.',
      },
      explainCa: 'Tant l’Estatut com la legislació de procediment reconeixen el dret d’opció lingüística: les persones poden utilitzar qualsevol de les llengües oficials i han de ser ateses en la que triïn, sense que se’ls pugui exigir cap traducció.',
      explainEs: 'Tanto el Estatuto como la legislación de procedimiento reconocen el derecho de opción lingüística: las personas pueden utilizar cualquiera de las lenguas oficiales y deben ser atendidas en la que elijan, sin que se les pueda exigir ninguna traducción.',
      refs: [ref('llei-39-2015-pac', 'art. 15'), ref('lo-6-2006-eac', 'drets lingüístics')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(15, [
    {
      n: 1,
      stem: 'Quan un termini administratiu s’assenyala per dies i la norma no diu res més, s’entenen:',
      options: ['Dies naturals', 'Dies hàbils, excloent dissabtes, diumenges i festius', 'Dies laborables de l’Administració actuant', 'Dies hàbils, incloent-hi els dissabtes'],
      correct: 'b',
      whyWrong: {
        a: 'Cal fer constar expressament quan els dies són naturals.',
        c: 'El criteri legal és el de dies hàbils, definit uniformement.',
        d: 'Els dissabtes estan expressament exclosos des de la Llei 39/2015.',
      },
      explainCa: 'Sempre que per llei o pel dret de la Unió Europea no s’expressi altra cosa, quan els terminis s’assenyalin per dies s’entén que són hàbils, i s’exclouen del còmput els dissabtes, els diumenges i els declarats festius. Si s’expressen en dies naturals, s’ha de fer constar.',
      explainEs: 'Siempre que por ley o por el derecho de la Unión Europea no se exprese otra cosa, cuando los plazos se señalen por días se entiende que son hábiles, y se excluyen del cómputo los sábados, los domingos y los declarados festivos. Si se expresan en días naturales, debe hacerse constar.',
      refs: [ref('llei-39-2015-pac', 'art. 30.1 i 30.2')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quin és el termini màxim per notificar la resolució d’un procediment quan la norma reguladora no en fixa cap?',
      options: ['Un mes', 'Tres mesos', 'Sis mesos', 'Un any'],
      correct: 'b',
      whyWrong: {
        a: 'Un mes és el termini de resolució del recurs de reposició.',
        c: 'Sis mesos és el màxim que pot fixar una norma amb rang de llei en determinats casos.',
        d: 'No correspon al termini supletori legal.',
      },
      explainCa: 'Quan les normes reguladores dels procediments no fixin el termini màxim, aquest serà de tres mesos. El termini es compta des de la data de l’acord d’iniciació en els procediments d’ofici, i des de l’entrada de la sol·licitud al registre de l’òrgan competent en els iniciats a sol·licitud de la persona interessada.',
      explainEs: 'Cuando las normas reguladoras de los procedimientos no fijen el plazo máximo, este será de tres meses. El plazo se cuenta desde la fecha del acuerdo de iniciación en los procedimientos de oficio, y desde la entrada de la solicitud en el registro del órgano competente en los iniciados a solicitud de la persona interesada.',
      refs: [ref('llei-39-2015-pac', 'art. 21')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'En un procediment sancionador iniciat d’ofici, la manca de resolució en termini produeix:',
      options: [
        'Silenci estimatori a favor de la persona interessada',
        'La caducitat del procediment',
        'La pròrroga automàtica del termini',
        'La confirmació de la sanció proposada',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El silenci positiu opera en procediments iniciats a sol·licitud de la persona interessada.',
        c: 'La llei no preveu cap pròrroga automàtica per inactivitat.',
        d: 'La inactivitat mai pot perjudicar la persona expedientada.',
      },
      explainCa: 'En els procediments iniciats d’ofici dels quals pugui derivar l’exercici de potestats sancionadores o, en general, efectes desfavorables o de gravamen, el venciment del termini màxim sense dictar resolució produeix la caducitat del procediment.',
      explainEs: 'En los procedimientos iniciados de oficio de los que pueda derivarse el ejercicio de potestades sancionadoras o, en general, efectos desfavorables o de gravamen, el vencimiento del plazo máximo sin dictar resolución produce la caducidad del procedimiento.',
      refs: [ref('llei-39-2015-pac', 'art. 25.1.b')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'Si l’últim dia d’un termini administratiu és inhàbil:',
      options: [
        'El termini venç igualment aquell dia',
        'S’entén prorrogat al primer dia hàbil següent',
        'S’avança a l’últim dia hàbil anterior',
        'El termini queda suspès indefinidament',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei preveu expressament la pròrroga.',
        c: 'La pròrroga opera cap endavant, mai cap enrere.',
        d: 'No hi ha suspensió: només desplaçament al dia hàbil següent.',
      },
      explainCa: 'Quan l’últim dia del termini sigui inhàbil, s’entén prorrogat al primer dia hàbil següent. Aquesta és una regla de garantia per a la persona interessada.',
      explainEs: 'Cuando el último día del plazo sea inhábil, se entiende prorrogado al primer día hábil siguiente. Esta es una regla de garantía para la persona interesada.',
      refs: [ref('llei-39-2015-pac', 'art. 30.5')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'Un funcionari amb amistat íntima amb la persona interessada en un expedient:',
      options: [
        'Pot continuar tramitant-lo si actua amb imparcialitat',
        'S’ha d’abstenir i comunicar-ho al seu superior',
        'Només s’ha d’abstenir si la persona interessada ho demana',
        'Ha de ser cessat automàticament del seu lloc',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei no deixa la decisió a la valoració subjectiva del funcionari.',
        c: 'L’abstenció és un deure d’ofici; la recusació és la via de la persona interessada.',
        d: 'L’abstenció afecta l’expedient concret, no el lloc de treball.',
      },
      explainCa: 'Són motius d’abstenció, entre altres, tenir interès personal en l’assumpte, tenir parentiu proper amb les persones interessades, tenir amistat íntima o enemistat manifesta, i haver intervingut com a perit o testimoni. Qui hi concorri s’ha d’abstenir i comunicar-ho al superior immediat.',
      explainEs: 'Son motivos de abstención, entre otros, tener interés personal en el asunto, tener parentesco cercano con las personas interesadas, tener amistad íntima o enemistad manifiesta, y haber intervenido como perito o testigo. Quien incurra en ellos debe abstenerse y comunicarlo al superior inmediato.',
      refs: [ref('llei-40-2015-rjsp', 'art. 23 i 24')],
      difficulty: 'mitjana',
    },
  ]),
]
