import type { Question } from '../../../schemas/index.ts'
import { questionsFor, ref, refv } from '../authoring.ts'

export const QUESTIONS_16_20: Question[] = [
  ...questionsFor(16, [
    {
      n: 1,
      stem: 'Quines són les quatre fases del procediment administratiu?',
      options: [
        'Iniciació, ordenació, instrucció i finalització',
        'Iniciació, tramitació, resolució i execució',
        'Sol·licitud, informe, audiència i resolució',
        'Incoació, prova, proposta i notificació',
      ],
      correct: 'a',
      whyWrong: {
        b: 'L’execució és posterior al procediment, no una de les seves fases.',
        c: 'Són tràmits concrets, no fases.',
        d: 'Són tràmits concrets, no fases.',
      },
      explainCa: 'La llei estructura el procediment en quatre fases: iniciació, ordenació, instrucció i finalització. L’execució de l’acte ja pertany a una etapa posterior.',
      explainEs: 'La ley estructura el procedimiento en cuatro fases: iniciación, ordenación, instrucción y finalización. La ejecución del acto ya pertenece a una etapa posterior.',
      refs: [refv('llei-39-2015-pac', 'títol IV, capítols II a VI', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'El tràmit d’audiència s’ha de concedir per un termini:',
      options: [
        'No inferior a deu dies ni superior a quinze',
        'De trenta dies com a mínim',
        'De cinc dies improrrogables',
        'D’un mes en tot cas',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Trenta dies és el mínim d’informació pública d’una ordenança.',
        c: 'És inferior al mínim legal.',
        d: 'No correspon al termini d’audiència.',
      },
      explainCa: 'Instruït el procediment i immediatament abans de redactar la proposta de resolució, s’ha de posar de manifest a les persones interessades, que disposaran d’un termini no inferior a deu dies ni superior a quinze per formular al·legacions i presentar documents.',
      explainEs: 'Instruido el procedimiento e inmediatamente antes de redactar la propuesta de resolución, debe ponerse de manifiesto a las personas interesadas, que dispondrán de un plazo no inferior a diez días ni superior a quince para formular alegaciones y presentar documentos.',
      refs: [refv('llei-39-2015-pac', 'art. 82', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Quina d’aquestes NO és una forma de començar un procediment d’ofici?',
      options: [
        'Per pròpia iniciativa de l’òrgan',
        'Per ordre superior',
        'Per petició raonada d’altres òrgans',
        'Per sol·licitud de la persona interessada',
      ],
      correct: 'd',
      whyWrong: {
        a: 'És una de les quatre formes legals d’iniciació d’ofici.',
        b: 'És una de les quatre formes legals d’iniciació d’ofici.',
        c: 'És una de les quatre formes legals d’iniciació d’ofici.',
      },
      explainCa: 'Els procediments s’inicien d’ofici per acord de l’òrgan competent, bé per pròpia iniciativa, bé com a conseqüència d’ordre superior, per petició raonada d’altres òrgans o per denúncia. La sol·licitud de la persona interessada és, per definició, l’altra via d’iniciació.',
      explainEs: 'Los procedimientos se inician de oficio por acuerdo del órgano competente, bien por propia iniciativa, bien como consecuencia de orden superior, por petición razonada de otros órganos o por denuncia. La solicitud de la persona interesada es, por definición, la otra vía de iniciación.',
      refs: [refv('llei-39-2015-pac', 'art. 54 i 58', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quina diferència hi ha entre desistiment i renúncia?',
      options: [
        'Cap: són sinònims legals',
        'Qui desisteix abandona la sol·licitud però conserva el dret; qui renuncia abandona el dret mateix',
        'El desistiment només el pot fer l’Administració',
        'La renúncia només opera en procediments sancionadors',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Tenen efectes clarament diferents.',
        c: 'El desistiment el fa la persona interessada.',
        d: 'La renúncia no és pròpia dels procediments sancionadors.',
      },
      explainCa: 'El desistiment posa fi al procediment concret però permet tornar a exercir el dret més endavant si no ha prescrit. La renúncia, en canvi, extingeix el dret en què es fonamenta la sol·licitud, i per això només és possible quan l’ordenament no la prohibeix.',
      explainEs: 'El desistimiento pone fin al procedimiento concreto pero permite volver a ejercer el derecho más adelante si no ha prescrito. La renuncia, en cambio, extingue el derecho en que se fundamenta la solicitud, y por eso solo es posible cuando el ordenamiento no la prohíbe.',
      refs: [refv('llei-39-2015-pac', 'art. 94', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Les mesures provisionals en un procediment administratiu:',
      options: [
        'Només es poden adoptar un cop dictada la resolució',
        'Es poden adoptar per assegurar l’eficàcia de la resolució, fins i tot abans de la iniciació en casos d’urgència inajornable',
        'Són sempre definitives',
        'No es poden adoptar mai en procediments sancionadors',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Precisament serveixen per al període anterior a la resolució.',
        c: 'Són provisionals per definició i s’han d’aixecar o confirmar.',
        d: 'Són freqüents en procediments sancionadors.',
      },
      explainCa: 'Iniciat el procediment, l’òrgan competent pot adoptar d’ofici o a instància de part les mesures provisionals que consideri oportunes per assegurar l’eficàcia de la resolució. Abans de la iniciació, en casos d’urgència inajornable i per a la protecció provisional dels interessos implicats, es poden adoptar mesures que hauran de ser confirmades, modificades o aixecades en l’acord d’iniciació.',
      explainEs: 'Iniciado el procedimiento, el órgano competente puede adoptar de oficio o a instancia de parte las medidas provisionales que estime oportunas para asegurar la eficacia de la resolución. Antes de la iniciación, en casos de urgencia inaplazable y para la protección provisional de los intereses implicados, pueden adoptarse medidas que deberán ser confirmadas, modificadas o levantadas en el acuerdo de iniciación.',
      refs: [refv('llei-39-2015-pac', 'art. 56', '2026-08-24')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(17, [
    {
      n: 1,
      stem: 'Quins són els mitjans d’execució forçosa previstos per la Llei 39/2015?',
      options: [
        'Constrenyiment sobre el patrimoni, execució subsidiària, multa coercitiva i compulsió sobre les persones',
        'Multa, embargament, precinte i detenció',
        'Execució subsidiària, sanció, decomís i tancament',
        'Constrenyiment, expropiació, sanció i clausura',
      ],
      correct: 'a',
      whyWrong: {
        b: 'La detenció és una mesura penal o de seguretat ciutadana, mai un mitjà d’execució forçosa administrativa.',
        c: 'La sanció i el decomís no són mitjans d’execució forçosa.',
        d: 'L’expropiació és una institució diferent.',
      },
      explainCa: 'La llei enumera de manera tancada quatre mitjans d’execució forçosa: constrenyiment sobre el patrimoni, execució subsidiària, multa coercitiva i compulsió sobre les persones. Cal advertiment previ i s’ha d’escollir el mitjà menys restrictiu de la llibertat individual.',
      explainEs: 'La ley enumera de manera cerrada cuatro medios de ejecución forzosa: apremio sobre el patrimonio, ejecución subsidiaria, multa coercitiva y compulsión sobre las personas. Se requiere apercibimiento previo y debe escogerse el medio menos restrictivo de la libertad individual.',
      refs: [refv('llei-39-2015-pac', 'art. 100', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'El termini per interposar un recurs d’alçada contra un acte exprés és de:',
      options: ['15 dies', 'Un mes', 'Dos mesos', 'Tres mesos'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon al termini legal.',
        c: 'Dos mesos és el termini del recurs contenciós administratiu.',
        d: 'Tres mesos és el termini quan l’acte és presumpte, no exprés.',
      },
      explainCa: 'El recurs d’alçada s’ha d’interposar en el termini d’un mes si l’acte és exprés. Si no ho és, el sol·licitant i altres possibles interessats poden interposar-lo en qualsevol moment a partir de l’endemà del dia en què es produeixin els efectes del silenci administratiu.',
      explainEs: 'El recurso de alzada debe interponerse en el plazo de un mes si el acto es expreso. Si no lo es, el solicitante y otros posibles interesados pueden interponerlo en cualquier momento a partir del día siguiente a aquel en que se produzcan los efectos del silencio administrativo.',
      refs: [refv('llei-39-2015-pac', 'art. 122', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'El recurs potestatiu de reposició s’interposa contra actes que:',
      options: [
        'No posen fi a la via administrativa',
        'Posen fi a la via administrativa',
        'Són actes de tràmit no qualificats',
        'Ja són ferms i inatacables',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Contra aquests actes procedeix el recurs d’alçada.',
        c: 'Els actes de tràmit no qualificats no són directament recurribles.',
        d: 'Contra actes ferms només cap el recurs extraordinari de revisió.',
      },
      explainCa: 'Els actes administratius que posin fi a la via administrativa poden ser recorreguts potestativament en reposició davant el mateix òrgan que els hagi dictat, o ser impugnats directament davant l’ordre jurisdiccional contenciós administratiu.',
      explainEs: 'Los actos administrativos que pongan fin a la vía administrativa pueden ser recurridos potestativamente en reposición ante el mismo órgano que los hubiera dictado, o ser impugnados directamente ante el orden jurisdiccional contencioso-administrativo.',
      refs: [refv('llei-39-2015-pac', 'art. 123', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'El termini màxim per resoldre i notificar un recurs de reposició és de:',
      options: ['15 dies', 'Un mes', 'Tres mesos', 'Sis mesos'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon al termini legal.',
        c: 'Tres mesos és el termini de resolució del recurs d’alçada.',
        d: 'No correspon al termini legal.',
      },
      explainCa: 'El termini màxim per dictar i notificar la resolució del recurs de reposició és d’un mes. Transcorregut aquest termini sense resolució expressa, es pot entendre desestimat i queda oberta la via contenciosa administrativa.',
      explainEs: 'El plazo máximo para dictar y notificar la resolución del recurso de reposición es de un mes. Transcurrido ese plazo sin resolución expresa, puede entenderse desestimado y queda abierta la vía contencioso-administrativa.',
      refs: [refv('llei-39-2015-pac', 'art. 124', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Per anul·lar un acte declaratiu de drets que sigui merament anul·lable, l’Administració ha de:',
      options: [
        'Revocar-lo directament en qualsevol moment',
        'Declarar-lo lesiu per a l’interès públic i impugnar-lo davant la jurisdicció contenciosa administrativa',
        'Sol·licitar-ho al Tribunal Constitucional',
        'Esperar que la persona interessada el recorri',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La revocació lliure només és possible per a actes desfavorables o de gravamen.',
        c: 'El Tribunal Constitucional no coneix d’aquests assumptes.',
        d: 'L’Administració disposa d’una via pròpia i no depèn de la iniciativa aliena.',
      },
      explainCa: 'La declaració de lesivitat és el camí per anul·lar actes favorables anul·lables: s’ha de declarar la lesivitat dins els quatre anys següents a la notificació de l’acte i, després, impugnar-lo davant la jurisdicció contenciosa administrativa. La revisió d’ofici directa queda reservada als actes nuls de ple dret.',
      explainEs: 'La declaración de lesividad es el camino para anular actos favorables anulables: debe declararse la lesividad dentro de los cuatro años siguientes a la notificación del acto y, después, impugnarlo ante la jurisdicción contencioso-administrativa. La revisión de oficio directa queda reservada a los actos nulos de pleno derecho.',
      refs: [refv('llei-39-2015-pac', 'art. 106, 107 i 109', '2026-08-24')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(18, [
    {
      n: 1,
      stem: 'Per exercir el dret d’accés a la informació pública cal:',
      options: [
        'Motivar sempre la sol·licitud',
        'No cal motivar-la, tot i que es pot exposar el motiu',
        'Acreditar un interès legítim',
        'Ser veí del municipi',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei exclou expressament l’exigència de motivació.',
        c: 'El dret és universal, sense necessitat d’interès qualificat.',
        d: 'Qualsevol persona hi té dret, sigui o no veïna.',
      },
      explainCa: 'La sol·licitud d’accés no ha de ser motivada, tot i que la persona sol·licitant pot exposar els motius pels quals demana la informació i aquests es podran tenir en compte en dictar resolució. L’absència de motivació no pot ser per si sola causa de rebuig.',
      explainEs: 'La solicitud de acceso no tiene que ser motivada, aunque la persona solicitante puede exponer los motivos por los que solicita la información y estos podrán tenerse en cuenta al dictar resolución. La ausencia de motivación no puede ser por sí sola causa de rechazo.',
      refs: [refv('llei-19-2013-transp', 'art. 17', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'El termini màxim per resoldre una sol·licitud d’accés a la informació pública és de:',
      options: ['10 dies', '15 dies', 'Un mes', 'Tres mesos'],
      correct: 'c',
      whyWrong: {
        a: 'No correspon al termini legal.',
        b: 'No correspon al termini legal.',
        d: 'Tres mesos és el termini supletori general de la Llei 39/2015, no el d’aquest procediment.',
      },
      explainCa: 'La resolució en què es concedeixi o es denegui l’accés s’ha de notificar en el termini màxim d’un mes des de la recepció de la sol·licitud per l’òrgan competent per resoldre, prorrogable per un mes més si el volum o la complexitat ho justifiquen.',
      explainEs: 'La resolución en la que se conceda o deniegue el acceso debe notificarse en el plazo máximo de un mes desde la recepción de la solicitud por el órgano competente para resolver, prorrogable por otro mes si el volumen o la complejidad lo justifican.',
      refs: [refv('llei-19-2013-transp', 'art. 20', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Quin òrgan resol les reclamacions en matèria d’accés a la informació pública a Catalunya?',
      options: [
        'El Síndic de Greuges',
        'La Comissió de Garantia del Dret d’Accés a la Informació Pública',
        'El Consell de Transparència i Bon Govern estatal',
        'El Tribunal Superior de Justícia de Catalunya',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Supervisa l’activitat de les administracions, però no resol aquestes reclamacions.',
        c: 'Actua en l’àmbit estatal; Catalunya té òrgan propi.',
        d: 'Actua com a jurisdicció, no com a òrgan de reclamació administrativa prèvia.',
      },
      explainCa: 'La Llei catalana 19/2014 crea la Comissió de Garantia del Dret d’Accés a la Informació Pública (GAIP) com a òrgan independent encarregat de resoldre les reclamacions contra les resolucions en matèria d’accés a la informació pública.',
      explainEs: 'La Ley catalana 19/2014 crea la Comisión de Garantía del Derecho de Acceso a la Información Pública (GAIP) como órgano independiente encargado de resolver las reclamaciones contra las resoluciones en materia de acceso a la información pública.',
      refs: [refv('llei-19-2014-transp-cat', 'Comissió de Garantia del Dret d’Accés', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'La publicitat activa consisteix en:',
      options: [
        'Respondre les sol·licituds d’informació que arriben',
        'Publicar periòdicament i actualitzada informació sense que ningú l’hagi demanat',
        'Publicar anuncis institucionals als mitjans',
        'Difondre les sancions imposades',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Això és el dret d’accés, la cara reactiva de la transparència.',
        c: 'La publicitat institucional és una altra cosa.',
        d: 'La difusió de sancions està limitada per la protecció de dades.',
      },
      explainCa: 'La publicitat activa obliga els subjectes obligats a publicar de forma periòdica i actualitzada la informació institucional, organitzativa i de planificació, la de rellevància jurídica i la econòmica, pressupostària i estadística, sense necessitat de cap sol·licitud prèvia.',
      explainEs: 'La publicidad activa obliga a los sujetos obligados a publicar de forma periódica y actualizada la información institucional, organizativa y de planificación, la de relevancia jurídica y la económica, presupuestaria y estadística, sin necesidad de solicitud previa.',
      refs: [refv('llei-19-2013-transp', 'art. 5 a 8', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'Que una informació estigui relacionada amb la prevenció o investigació d’il·lícits:',
      options: [
        'La converteix automàticament en secreta',
        'Permet limitar l’accés si es justifica un perjudici concret i de manera proporcionada',
        'Obliga a denegar l’accés en tot cas',
        'No afecta gens el dret d’accés',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Els límits no operen automàticament: cal justificar-los.',
        c: 'Es pot donar accés parcial ocultant només la part protegida.',
        d: 'Sí que és un dels límits taxats que preveu la llei.',
      },
      explainCa: 'La prevenció, la investigació i la sanció dels il·lícits penals, administratius o disciplinaris és un dels límits al dret d’accés. Ara bé, l’aplicació dels límits ha de ser justificada i proporcionada al seu objecte i finalitat, i quan sigui possible s’ha de concedir accés parcial.',
      explainEs: 'La prevención, la investigación y la sanción de los ilícitos penales, administrativos o disciplinarios es uno de los límites al derecho de acceso. Ahora bien, la aplicación de los límites debe ser justificada y proporcionada a su objeto y finalidad, y cuando sea posible debe concederse acceso parcial.',
      refs: [refv('llei-19-2013-transp', 'art. 14 i 16', '2026-08-24')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(19, [
    {
      n: 1,
      stem: 'Quin és el vector d’entrada més freqüent dels incidents de ciberseguretat?',
      options: [
        'Les vulnerabilitats de dia zero',
        'L’enginyeria social, especialment la pesca d’identitat per correu',
        'Els atacs de força bruta contra servidors',
        'La intercepció física de cablejat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Són rares i cares; no expliquen el volum d’incidents.',
        c: 'Existeixen, però són molt menys freqüents que l’enginyeria social.',
        d: 'És excepcional en entorns civils.',
      },
      explainCa: 'La major part dels incidents comencen amb una persona que fa clic on no toca. L’enginyeria social —correus, missatges i trucades que exploten la confiança i la pressa— és el vector dominant, per damunt de qualsevol vulnerabilitat tècnica.',
      explainEs: 'La mayoría de los incidentes empiezan con una persona que hace clic donde no debe. La ingeniería social —correos, mensajes y llamadas que explotan la confianza y la prisa— es el vector dominante, por encima de cualquier vulnerabilidad técnica.',
      refs: [ref('agencia-ciberseguretat-catalunya', 'recomanacions i tipologia d’incidents')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Quin organisme executa les polítiques públiques de ciberseguretat a Catalunya?',
      options: [
        'L’Institut Nacional de Ciberseguretat',
        'L’Agència de Ciberseguretat de Catalunya',
        'El Centre Criptològic Nacional',
        'L’Agència Espanyola de Protecció de Dades',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És l’organisme estatal de referència, no el català.',
        c: 'Actua en l’àmbit dels sistemes classificats de l’Estat.',
        d: 'És l’autoritat de protecció de dades, no de ciberseguretat.',
      },
      explainCa: 'L’Agència de Ciberseguretat de Catalunya és l’organisme de la Generalitat encarregat d’executar les polítiques públiques en matèria de ciberseguretat, de prevenir i respondre incidents i de difondre la cultura de la ciberseguretat.',
      explainEs: 'La Agencia de Ciberseguridad de Cataluña es el organismo de la Generalitat encargado de ejecutar las políticas públicas en materia de ciberseguridad, de prevenir y responder a incidentes y de difundir la cultura de la ciberseguridad.',
      refs: [ref('agencia-ciberseguretat-catalunya', 'funcions institucionals')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'Quina d’aquestes definicions correspon al ransomware?',
      options: [
        'Programari que xifra la informació de la víctima i n’exigeix un rescat',
        'Correu que suplanta una entitat per robar credencials',
        'Trucada telefònica fraudulenta per obtenir dades',
        'Programari que registra les pulsacions del teclat',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Això és el phishing.',
        c: 'Això és el vishing.',
        d: 'Això és un keylogger.',
      },
      explainCa: 'El ransomware o programari de segrest xifra els fitxers de la víctima i n’exigeix un pagament per recuperar-los. La millor defensa no és pagar, sinó disposar de còpies de seguretat aïllades i comprovades.',
      explainEs: 'El ransomware o programa de secuestro cifra los archivos de la víctima y exige un pago para recuperarlos. La mejor defensa no es pagar, sino disponer de copias de seguridad aisladas y comprobadas.',
      refs: [ref('agencia-ciberseguretat-catalunya', 'tipologia d’amenaces')],
      difficulty: 'facil',
    },
    {
      n: 4,
      stem: 'Davant una denúncia per estafa en línia, la primera actuació policial ha de ser:',
      options: [
        'Contactar directament amb el presumpte estafador',
        'Preservar les proves: captures amb data i URL completa, justificants i converses senceres',
        'Recomanar a la víctima que esborri els missatges per seguretat',
        'Bloquejar el compte bancari de la víctima',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Podria alertar l’autor i destruir proves.',
        c: 'Esborrar destrueix la traça probatòria.',
        d: 'És una decisió de l’entitat i de la víctima, no una primera diligència policial.',
      },
      explainCa: 'La prioritat és preservar la traça digital abans que desaparegui: captures completes amb data i adreça, justificants de pagament, dades del compte de destinació i converses íntegres. Aquestes diligències són pràcticament irrepetibles.',
      explainEs: 'La prioridad es preservar la traza digital antes de que desaparezca: capturas completas con fecha y dirección, justificantes de pago, datos de la cuenta de destino y conversaciones íntegras. Estas diligencias son prácticamente irrepetibles.',
      refs: [ref('agencia-ciberseguretat-catalunya', 'preservació de proves digitals')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Quina d’aquestes és la mesura d’autoprotecció més robusta per a un compte professional?',
      options: [
        'Canviar la contrasenya cada setmana',
        'Fer servir verificació en dos passos amb aplicació d’autenticació o clau física',
        'Utilitzar una contrasenya llarga i reutilitzar-la en tots els serveis',
        'Rebre els codis de verificació per SMS',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El canvi freqüent forçat empitjora la qualitat de les contrasenyes.',
        c: 'La reutilització anul·la l’avantatge de la longitud.',
        d: 'És millor que res, però el segrest de la línia telefònica la burla.',
      },
      explainCa: 'La verificació en dos passos amb aplicació d’autenticació o clau física resisteix el phishing i el segrest de línia telefònica, a diferència dels codis per SMS. Combinada amb contrasenyes llargues i úniques per servei, és la mesura amb més impacte.',
      explainEs: 'La verificación en dos pasos con aplicación de autenticación o llave física resiste el phishing y el secuestro de línea telefónica, a diferencia de los códigos por SMS. Combinada con contraseñas largas y únicas por servicio, es la medida de mayor impacto.',
      refs: [ref('agencia-ciberseguretat-catalunya', 'mesures d’autoprotecció')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(20, [
    {
      n: 1,
      stem: 'Quin d’aquests NO és un principi del tractament de dades del Reglament general de protecció de dades?',
      options: [
        'Minimització de dades',
        'Limitació de la finalitat',
        'Gratuïtat del tractament',
        'Responsabilitat proactiva',
      ],
      correct: 'c',
      whyWrong: {
        a: 'És un dels principis expressos.',
        b: 'És un dels principis expressos.',
        d: 'És un dels principis expressos.',
      },
      explainCa: 'Els principis són licitud, lleialtat i transparència; limitació de la finalitat; minimització de dades; exactitud; limitació del termini de conservació; integritat i confidencialitat; i responsabilitat proactiva. La gratuïtat no és un principi del tractament.',
      explainEs: 'Los principios son licitud, lealtad y transparencia; limitación de la finalidad; minimización de datos; exactitud; limitación del plazo de conservación; integridad y confidencialidad; y responsabilidad proactiva. La gratuidad no es un principio del tratamiento.',
      refs: [refv('rgpd-2016-679', 'art. 5', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Quina és la base de legitimació habitual del tractament de dades en l’actuació policial?',
      options: [
        'El consentiment de la persona interessada',
        'El compliment d’una obligació legal i l’exercici de poders públics',
        'L’interès legítim del responsable',
        'L’execució d’un contracte',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Demanar consentiment per a una actuació coercitiva seria contradictori i el consentiment no seria lliure.',
        c: 'L’interès legítim està exclòs per als tractaments duts a terme per autoritats públiques en l’exercici de les seves funcions.',
        d: 'No hi ha relació contractual en l’actuació policial.',
      },
      explainCa: 'L’actuació policial es basa en el compliment d’una obligació legal i en el compliment d’una missió d’interès públic o l’exercici de poders públics. El consentiment no és una base vàlida quan hi ha un desequilibri clar de poder, com passa entre l’autoritat i la persona administrada.',
      explainEs: 'La actuación policial se basa en el cumplimiento de una obligación legal y en el cumplimiento de una misión de interés público o el ejercicio de poderes públicos. El consentimiento no es una base válida cuando hay un desequilibrio claro de poder, como ocurre entre la autoridad y la persona administrada.',
      refs: [refv('rgpd-2016-679', 'art. 6', '2026-08-24'), refv('lo-3-2018-lopdgdd', 'tractaments per obligació legal', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'Els tractaments de dades amb finalitats de prevenció, investigació i enjudiciament d’infraccions penals es regeixen per:',
      options: [
        'El règim general del Reglament general de protecció de dades',
        'La normativa específica que transposa la Directiva (UE) 2016/680',
        'La Llei de transparència',
        'El règim de seguretat privada',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Aquests tractaments queden fora de l’àmbit d’aplicació general del Reglament.',
        c: 'Regula l’accés a la informació pública, no la protecció de dades.',
        d: 'No té res a veure amb la matèria.',
      },
      explainCa: 'La Directiva (UE) 2016/680 estableix un règim propi per als tractaments amb finalitats policials i penals, transposat a l’ordenament espanyol per la Llei orgànica 7/2021. Confondre aquest règim amb el del Reglament general és un error habitual.',
      explainEs: 'La Directiva (UE) 2016/680 establece un régimen propio para los tratamientos con fines policiales y penales, traspuesto al ordenamiento español por la Ley orgánica 7/2021. Confundir este régimen con el del Reglamento general es un error habitual.',
      refs: [refv('lo-7-2021-dades-policials', 'objecte i àmbit d’aplicació', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'El dret a la protecció de dades personals:',
      options: [
        'És una manifestació del dret a la intimitat sense autonomia pròpia',
        'És un dret fonamental autònom, diferenciat del dret a la intimitat',
        'És un dret de configuració legal sense rang constitucional',
        'Només protegeix les dades sensibles',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La jurisprudència constitucional n’ha afirmat l’autonomia.',
        c: 'Té fonament constitucional a l’article 18.4.',
        d: 'Protegeix qualsevol dada personal, no només les categories especials.',
      },
      explainCa: 'La Constitució preveu a l’article 18.4 que la llei limitarà l’ús de la informàtica per garantir l’honor i la intimitat personal i familiar i el ple exercici dels drets. D’aquesta previsió n’ha derivat un dret fonamental autònom a la protecció de dades, diferent del dret a la intimitat.',
      explainEs: 'La Constitución prevé en el artículo 18.4 que la ley limitará el uso de la informática para garantizar el honor y la intimidad personal y familiar y el pleno ejercicio de los derechos. De esta previsión se ha derivado un derecho fundamental autónomo a la protección de datos, distinto del derecho a la intimidad.',
      refs: [refv('ce-1978', 'art. 18.4', '2026-08-24'), refv('lo-3-2018-lopdgdd', 'objecte', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Publicar a xarxes socials imatges gravades per una càmera de vehicle policial seria:',
      options: [
        'Lícit si no s’identifiquen matrícules',
        'Un tractament nou que necessitaria base legal pròpia i que, en general, seria il·lícit',
        'Lícit sempre, perquè les imatges s’han obtingut en via pública',
        'Lícit si ho autoritza el comandament de servei',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Ocultar matrícules no elimina el caràcter personal de les dades ni legitima la finalitat.',
        c: 'La captació en via pública no converteix les dades en públiques.',
        d: 'Una autorització interna no substitueix una base legal de tractament.',
      },
      explainCa: 'La difusió pública és una finalitat distinta de la que va legitimar la captació. Sense una base legal específica per a aquesta nova finalitat, la publicació vulnera el principi de limitació de la finalitat i pot generar responsabilitat administrativa, disciplinària i, si escau, penal.',
      explainEs: 'La difusión pública es una finalidad distinta de la que legitimó la captación. Sin una base legal específica para esa nueva finalidad, la publicación vulnera el principio de limitación de la finalidad y puede generar responsabilidad administrativa, disciplinaria y, en su caso, penal.',
      refs: [refv('rgpd-2016-679', 'art. 5.1.b', '2026-08-24'), refv('lo-7-2021-dades-policials', 'finalitats del tractament', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),
]
