import type { Question } from '../../../schemas/index.ts'
import { questionsFor, refv } from '../authoring.ts'

export const QUESTIONS_06_10: Question[] = [
  ...questionsFor(6, [
    {
      n: 1,
      stem: 'Quin és el termini mínim d’informació pública i audiència en la tramitació d’una ordenança municipal?',
      options: ['15 dies', '20 dies', '30 dies', '60 dies'],
      correct: 'c',
      whyWrong: {
        a: '15 dies hàbils és el termini previ a l’entrada en vigor un cop publicada, no el d’informació pública.',
        b: 'No correspon a cap termini d’aquest procediment.',
        d: 'No és el mínim legal, tot i que el ple podria ampliar-lo.',
      },
      explainCa: 'Després de l’aprovació inicial pel ple s’obre un període d’informació pública i audiència a les persones interessades per un termini mínim de trenta dies per presentar reclamacions i suggeriments.',
      explainEs: 'Tras la aprobación inicial por el pleno se abre un período de información pública y audiencia a las personas interesadas por un plazo mínimo de treinta días para presentar reclamaciones y sugerencias.',
      refs: [refv('llei-7-1985-lrbrl', 'art. 49', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Qui té la competència per aprovar una ordenança municipal?',
      options: ['L’alcalde o alcaldessa', 'La junta de govern local', 'El ple de la corporació', 'La comissió informativa competent'],
      correct: 'c',
      whyWrong: {
        a: 'L’alcalde dicta bans i resolucions, però no aprova ordenances.',
        b: 'La junta de govern local assisteix l’alcalde i exerceix les competències delegades, no la potestat reglamentària plenària.',
        d: 'Les comissions informatives dictaminen, no aproven.',
      },
      explainCa: 'L’aprovació de les ordenances és una competència indelegable del ple de la corporació, tant en la fase inicial com en la definitiva.',
      explainEs: 'La aprobación de las ordenanzas es una competencia indelegable del pleno de la corporación, tanto en la fase inicial como en la definitiva.',
      refs: [refv('llei-7-1985-lrbrl', 'art. 22 i 49', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 3,
      stem: 'Un ban de l’alcaldia pot:',
      options: [
        'Crear infraccions i sancions noves',
        'Modificar el contingut d’una ordenança',
        'Recordar, concretar o advertir sobre el compliment de normes ja existents',
        'Substituir una ordenança quan hi ha urgència',
      ],
      correct: 'c',
      whyWrong: {
        a: 'Només una norma amb rang suficient pot tipificar infraccions i sancions.',
        b: 'Un acte de l’alcalde no pot modificar una norma aprovada pel ple.',
        d: 'La urgència no altera el sistema de fonts.',
      },
      explainCa: 'El ban és un acte de l’autoritat municipal, no una norma reglamentària. Serveix per recordar obligacions, concretar aspectes organitzatius o advertir la població, però no pot crear infraccions ni contradir una ordenança.',
      explainEs: 'El bando es un acto de la autoridad municipal, no una norma reglamentaria. Sirve para recordar obligaciones, concretar aspectos organizativos o advertir a la población, pero no puede crear infracciones ni contradecir una ordenanza.',
      refs: [refv('llei-7-1985-lrbrl', 'art. 21.1.e', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'On s’ha de publicar íntegrament una ordenança municipal de Roses perquè pugui entrar en vigor?',
      options: [
        'Al Diari Oficial de la Generalitat de Catalunya',
        'Al Butlletí Oficial de la Província de Girona',
        'Al Boletín Oficial del Estado',
        'Únicament al tauler d’anuncis de l’Ajuntament',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El DOGC publica normativa autonòmica; les ordenances locals van al butlletí provincial.',
        c: 'El BOE no publica ordenances municipals.',
        d: 'El tauler d’anuncis complementa, però no substitueix la publicació al butlletí provincial.',
      },
      explainCa: 'Les ordenances s’han de publicar íntegrament al butlletí oficial de la província —a Roses, el BOP de Girona— i no entren en vigor fins que hagi transcorregut el termini de quinze dies hàbils previst per a la comunicació a l’Estat i a la comunitat autònoma.',
      explainEs: 'Las ordenanzas deben publicarse íntegramente en el boletín oficial de la provincia —en Roses, el BOP de Girona— y no entran en vigor hasta que haya transcurrido el plazo de quince días hábiles previsto para la comunicación al Estado y a la comunidad autónoma.',
      refs: [refv('llei-7-1985-lrbrl', 'art. 65.2 i 70.2', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Si durant el període d’informació pública no es presenta cap reclamació ni suggeriment sobre una ordenança:',
      options: [
        'Cal repetir el tràmit amb un termini ampliat',
        'L’acord fins llavors provisional esdevé definitiu automàticament',
        'L’ordenança decau i cal iniciar de nou el procediment',
        'L’alcalde l’ha d’aprovar per decret',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No hi ha cap obligació de repetir el tràmit.',
        c: 'La manca de reclamacions no fa decaure l’expedient, sinó al contrari.',
        d: 'L’aprovació correspon al ple, no a l’alcalde.',
      },
      explainCa: 'Si no es presenta cap reclamació ni suggeriment, s’entén definitivament adoptat l’acord fins llavors provisional, sense necessitat d’un nou acord exprés del ple. Encara caldrà, això sí, la publicació íntegra al butlletí provincial.',
      explainEs: 'Si no se presenta ninguna reclamación ni sugerencia, se entiende definitivamente adoptado el acuerdo hasta entonces provisional, sin necesidad de un nuevo acuerdo expreso del pleno. Todavía hará falta, eso sí, la publicación íntegra en el boletín provincial.',
      refs: [refv('llei-7-1985-lrbrl', 'art. 49', '2026-08-24')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(7, [
    {
      n: 1,
      stem: 'El Tribunal Constitucional:',
      options: [
        'Forma part del poder judicial com a òrgan superior',
        'És un òrgan constitucional independent que no forma part del poder judicial',
        'És una sala especialitzada del Tribunal Suprem',
        'Depèn del Consell General del Poder Judicial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El títol IX el regula separadament del títol VI, dedicat al poder judicial.',
        c: 'Són òrgans diferents amb funcions distintes.',
        d: 'El CGPJ només proposa dos dels seus magistrats; no en depèn.',
      },
      explainCa: 'El Tribunal Constitucional es regula al títol IX de la Constitució, separat del títol VI dedicat al poder judicial. És un òrgan constitucional independent, únic en el seu ordre, amb jurisdicció en tot el territori espanyol.',
      explainEs: 'El Tribunal Constitucional se regula en el título IX de la Constitución, separado del título VI dedicado al poder judicial. Es un órgano constitucional independiente, único en su orden, con jurisdicción en todo el territorio español.',
      refs: [refv('ce-1978', 'títol IX, art. 159 i següents', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Els dotze magistrats del Tribunal Constitucional són nomenats pel Rei a proposta de:',
      options: [
        'Quatre del Congrés, quatre del Senat, dos del Govern i dos del CGPJ',
        'Sis del Congrés i sis del Senat',
        'Quatre del Congrés, quatre del Senat i quatre del Govern',
        'Sis del Govern i sis del Consell General del Poder Judicial',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Deixa fora el Govern i el CGPJ.',
        c: 'El Govern només en proposa dos, i el CGPJ n’ha de proposar dos.',
        d: 'Les cambres han de proposar-ne vuit en total.',
      },
      explainCa: 'Els dotze membres són nomenats pel Rei: quatre a proposta del Congrés per majoria de tres cinquenes parts, quatre a proposta del Senat per la mateixa majoria, dos a proposta del Govern i dos a proposta del Consell General del Poder Judicial.',
      explainEs: 'Los doce miembros son nombrados por el Rey: cuatro a propuesta del Congreso por mayoría de tres quintas partes, cuatro a propuesta del Senado por la misma mayoría, dos a propuesta del Gobierno y dos a propuesta del Consejo General del Poder Judicial.',
      refs: [refv('ce-1978', 'art. 159.1', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'Segons l’article 117 de la Constitució, la justícia:',
      options: [
        'Emana del Rei i s’administra en nom del poble',
        'Emana del poble i s’administra en nom del Rei',
        'Emana de les Corts Generals',
        'Emana del Consell General del Poder Judicial',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Inverteix exactament els termes del precepte.',
        c: 'Les Corts exerceixen la potestat legislativa.',
        d: 'El CGPJ és l’òrgan de govern del poder judicial, no la font de la justícia.',
      },
      explainCa: 'L’article 117.1 estableix que la justícia emana del poble i s’administra en nom del Rei per jutges i magistrats integrants del poder judicial, independents, inamovibles, responsables i sotmesos únicament a l’imperi de la llei.',
      explainEs: 'El artículo 117.1 establece que la justicia emana del pueblo y se administra en nombre del Rey por jueces y magistrados integrantes del poder judicial, independientes, inamovibles, responsables y sometidos únicamente al imperio de la ley.',
      refs: [refv('ce-1978', 'art. 117.1', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'Quin òrgan judicial culmina l’organització judicial dins el territori de Catalunya?',
      options: [
        'El Tribunal Suprem',
        'El Tribunal Superior de Justícia de Catalunya',
        'L’Audiència Nacional',
        'El Tribunal Constitucional',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És l’òrgan superior en tots els ordres a escala estatal, però no culmina l’organització judicial dins la comunitat autònoma.',
        c: 'Té competències específiques d’àmbit estatal.',
        d: 'No forma part del poder judicial.',
      },
      explainCa: 'El Tribunal Superior de Justícia de Catalunya culmina l’organització judicial dins el territori de la comunitat autònoma, sens perjudici de la jurisdicció que correspon al Tribunal Suprem.',
      explainEs: 'El Tribunal Superior de Justicia de Cataluña culmina la organización judicial dentro del territorio de la comunidad autónoma, sin perjuicio de la jurisdicción que corresponde al Tribunal Supremo.',
      refs: [refv('ce-1978', 'art. 152', '2026-08-24'), refv('lo-6-2006-eac', 'el poder judicial a Catalunya', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'La durada del mandat dels magistrats del Tribunal Constitucional és de:',
      options: ['Cinc anys', 'Sis anys', 'Nou anys', 'Dotze anys'],
      correct: 'c',
      whyWrong: {
        a: 'Cinc anys és el mandat dels vocals del Consell General del Poder Judicial.',
        b: 'No correspon a cap mandat del Tribunal Constitucional.',
        d: 'Dotze és el nombre de magistrats, no els anys de mandat.',
      },
      explainCa: 'Els magistrats del Tribunal Constitucional són designats per un període de nou anys i es renoven per terceres parts cada tres anys.',
      explainEs: 'Los magistrados del Tribunal Constitucional son designados por un período de nueve años y se renuevan por terceras partes cada tres años.',
      refs: [refv('ce-1978', 'art. 159.3', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(8, [
    {
      n: 1,
      stem: 'Segons l’Estatut bàsic de l’empleat públic, quines són les classes d’empleats públics?',
      options: [
        'Funcionaris de carrera, funcionaris interins, personal laboral i personal eventual',
        'Funcionaris de carrera i personal laboral únicament',
        'Funcionaris, contractats i col·laboradors',
        'Personal fix, personal temporal i alts càrrecs',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Omet els funcionaris interins i el personal eventual.',
        c: 'No és la classificació legal.',
        d: 'No és la classificació legal.',
      },
      explainCa: 'L’Estatut bàsic classifica els empleats públics en funcionaris de carrera, funcionaris interins, personal laboral (fix, per temps indefinit o temporal) i personal eventual.',
      explainEs: 'El Estatuto básico clasifica a los empleados públicos en funcionarios de carrera, funcionarios interinos, personal laboral (fijo, por tiempo indefinido o temporal) y personal eventual.',
      refs: [refv('rdleg-5-2015-trebep', 'art. 8', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'Quin d’aquests drets s’exerceix col·lectivament segons l’Estatut bàsic de l’empleat públic?',
      options: [
        'La inamovibilitat en la condició de funcionari de carrera',
        'La llibertat sindical',
        'La progressió en la carrera professional',
        'El respecte a la intimitat i a la dignitat en el treball',
      ],
      correct: 'b',
      whyWrong: {
        a: 'És un dret individual.',
        c: 'És un dret individual.',
        d: 'És un dret individual.',
      },
      explainCa: 'La llei distingeix els drets individuals dels drets individuals exercits col·lectivament. Entre aquests darrers hi ha la llibertat sindical, la negociació col·lectiva, l’exercici de la vaga amb garantia dels serveis essencials, el plantejament de conflictes col·lectius i el dret de reunió.',
      explainEs: 'La ley distingue los derechos individuales de los derechos individuales ejercidos colectivamente. Entre estos últimos están la libertad sindical, la negociación colectiva, el ejercicio de la huelga con garantía de los servicios esenciales, el planteamiento de conflictos colectivos y el derecho de reunión.',
      refs: [refv('rdleg-5-2015-trebep', 'art. 14 i 15', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'El deure d’obediència d’un empleat públic cedeix quan la instrucció rebuda:',
      options: [
        'Li sembla injusta',
        'Constitueix una infracció manifesta de l’ordenament jurídic',
        'Prové d’un superior d’una altra unitat',
        'No consta per escrit',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La discrepància personal no eximeix del deure d’obediència.',
        c: 'La qüestió competencial es resol per la via orgànica, no desobeint.',
        d: 'La forma verbal no invalida per si mateixa una instrucció.',
      },
      explainCa: 'Els principis de conducta obliguen a obeir les instruccions i ordres professionals dels superiors, «llevat que constitueixin una infracció manifesta de l’ordenament jurídic», i en aquest cas s’han de posar immediatament en coneixement dels òrgans d’inspecció. La mateixa excepció apareix als principis bàsics d’actuació policial, on l’obediència deguda no pot emparar ordres que constitueixin manifestament delicte o siguin contràries a la Constitució o a les lleis.',
      explainEs: 'Los principios de conducta obligan a obedecer las instrucciones y órdenes profesionales de los superiores, «salvo que constituyan una infracción manifiesta del ordenamiento jurídico», y en ese caso deben ponerse inmediatamente en conocimiento de los órganos de inspección. La misma excepción aparece en los principios básicos de actuación policial, donde la obediencia debida no puede amparar órdenes que constituyan manifiestamente delito o sean contrarias a la Constitución o a las leyes.',
      refs: [refv('rdleg-5-2015-trebep', 'art. 54', '2026-08-24'), refv('lo-2-1986-fcs', 'art. 5.1', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'El codi de conducta dels empleats públics està integrat per:',
      options: [
        'Els principis ètics i els principis de conducta',
        'Els drets i els deures',
        'Les faltes i les sancions',
        'Els principis d’actuació i el règim d’incompatibilitats',
      ],
      correct: 'a',
      whyWrong: {
        b: 'Drets i deures es regulen en capítols distints del codi de conducta.',
        c: 'Formen part del règim disciplinari.',
        d: 'Les incompatibilitats tenen llei pròpia.',
      },
      explainCa: 'L’Estatut bàsic disposa que els empleats públics han de complir amb diligència les tasques que tenen assignades i vetllar pels interessos generals, i que el seu codi de conducta està integrat pels principis ètics i pels principis de conducta que la mateixa llei enumera.',
      explainEs: 'El Estatuto básico dispone que los empleados públicos deben cumplir con diligencia las tareas que tienen asignadas y velar por los intereses generales, y que su código de conducta está integrado por los principios éticos y por los principios de conducta que la propia ley enumera.',
      refs: [refv('rdleg-5-2015-trebep', 'art. 52, 53 i 54', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 5,
      stem: 'L’abstenció en els assumptes en què es tingui un interès personal és, segons l’Estatut bàsic:',
      options: [
        'Una recomanació de bones pràctiques',
        'Un principi ètic d’obligat compliment',
        'Una obligació que només afecta els alts càrrecs',
        'Un dret que l’empleat pot exercir si vol',
      ],
      correct: 'b',
      whyWrong: {
        a: 'No és una recomanació: forma part del codi de conducta amb valor normatiu.',
        c: 'Afecta tot el personal al servei de les administracions públiques.',
        d: 'No és facultatiu: és un deure.',
      },
      explainCa: 'Entre els principis ètics hi ha el deure d’abstenir-se en els assumptes en què es tingui un interès personal, així com de tota activitat privada que pugui suposar un risc de conflicte d’interessos amb el lloc públic. La regulació concreta de l’abstenció i la recusació és a la Llei 40/2015.',
      explainEs: 'Entre los principios éticos está el deber de abstenerse en los asuntos en que se tenga un interés personal, así como de toda actividad privada que pueda suponer un riesgo de conflicto de intereses con el puesto público. La regulación concreta de la abstención y la recusación está en la Ley 40/2015.',
      refs: [refv('rdleg-5-2015-trebep', 'art. 53', '2026-08-24'), refv('llei-40-2015-rjsp', 'art. 23', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),

  ...questionsFor(9, [
    {
      n: 1,
      stem: 'El principi general de la Llei 53/1984 d’incompatibilitats és que el personal al servei de les administracions públiques:',
      options: [
        'Pot ocupar dos llocs si les jornades són compatibles',
        'Només pot ocupar un lloc de treball al sector públic',
        'Pot ocupar tants llocs com vulgui si ho comunica',
        'No pot exercir cap activitat privada en cap cas',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La compatibilitat horària no és el criteri: la regla és un sol lloc.',
        c: 'La comunicació no substitueix l’autorització i no aixeca la regla general.',
        d: 'L’activitat privada és possible amb reconeixement previ de compatibilitat en els casos permesos.',
      },
      explainCa: 'La llei estableix que el personal comprès en el seu àmbit no podrà ocupar més d’un lloc de treball al sector públic ni percebre més d’una remuneració amb càrrec a pressupostos públics, llevat dels supòsits d’excepció expressament previstos.',
      explainEs: 'La ley establece que el personal comprendido en su ámbito no podrá ocupar más de un puesto de trabajo en el sector público ni percibir más de una remuneración con cargo a presupuestos públicos, salvo los supuestos de excepción expresamente previstos.',
      refs: [refv('llei-53-1984-incompat', 'art. 1', '2026-08-24')],
      difficulty: 'facil',
    },
    {
      n: 2,
      stem: 'No es pot autoritzar la compatibilitat per a activitats privades quan el complement específic o concepte equiparable supera:',
      options: [
        'El 20 % de la retribució bàsica',
        'El 30 % de la retribució bàsica, exclosa l’antiguitat',
        'El 50 % de la retribució total',
        'El 30 % de la retribució total, inclosa l’antiguitat',
      ],
      correct: 'b',
      whyWrong: {
        a: 'El percentatge legal és el 30 %, no el 20 %.',
        c: 'La base de càlcul és la retribució bàsica, no la total.',
        d: 'L’antiguitat s’exclou expressament del càlcul.',
      },
      explainCa: 'La llei impedeix autoritzar la compatibilitat per exercir activitats privades quan la quantia del complement específic o concepte equiparable supera el trenta per cent de la retribució bàsica, exclosos els conceptes que tinguin origen en l’antiguitat.',
      explainEs: 'La ley impide autorizar la compatibilidad para ejercer actividades privadas cuando la cuantía del complemento específico o concepto equiparable supera el treinta por ciento de la retribución básica, excluidos los conceptos que tengan su origen en la antigüedad.',
      refs: [refv('llei-53-1984-incompat', 'art. 16.4', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 3,
      stem: 'El reconeixement de compatibilitat per a una segona activitat:',
      options: [
        'Permet ajustar la jornada i l’horari del lloc principal',
        'No pot modificar la jornada de treball ni l’horari de la persona interessada',
        'Suspèn temporalment les obligacions del lloc principal',
        'Només és necessari si l’activitat és remunerada per una administració',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La llei ho prohibeix expressament.',
        c: 'Les obligacions del lloc principal es mantenen íntegres.',
        d: 'També cal reconeixement per a activitats privades.',
      },
      explainCa: 'La llei estableix que el reconeixement de compatibilitat no podrà modificar la jornada de treball ni l’horari de la persona interessada, i queda automàticament sense efecte en cas de canvi de lloc al sector públic.',
      explainEs: 'La ley establece que el reconocimiento de compatibilidad no podrá modificar la jornada de trabajo ni el horario de la persona interesada, y queda automáticamente sin efecto en caso de cambio de puesto en el sector público.',
      refs: [refv('llei-53-1984-incompat', 'art. 14', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 4,
      stem: 'En cap cas es pot autoritzar l’exercici d’activitats privades que:',
      options: [
        'Es facin fora de l’horari laboral',
        'Es relacionin amb assumptes en què la persona intervingui o hagi intervingut els dos últims anys',
        'Estiguin remunerades per sota d’un llindar determinat',
        'Es facin en un municipi diferent',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Fer-ho fora d’horari no legitima per si sol l’activitat.',
        c: 'La quantia de la retribució privada no és el criteri.',
        d: 'El territori no és el criteri legal.',
      },
      explainCa: 'La llei prohibeix reconèixer la compatibilitat per a activitats privades relacionades directament amb les que desenvolupa el departament, organisme o entitat on la persona presta serveis, i molt especialment les relatives a assumptes en què estigui intervenint o hagi intervingut en els dos últims anys.',
      explainEs: 'La ley prohíbe reconocer la compatibilidad para actividades privadas relacionadas directamente con las que desarrolla el departamento, organismo o entidad donde la persona presta servicios, y muy especialmente las relativas a asuntos en que esté interviniendo o haya intervenido en los dos últimos años.',
      refs: [refv('llei-53-1984-incompat', 'art. 11 i 12', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 5,
      stem: 'Iniciar una activitat privada abans d’obtenir el reconeixement de compatibilitat:',
      options: [
        'És vàlid si posteriorment s’obté l’autorització',
        'Constitueix per si mateix un incompliment del règim d’incompatibilitats',
        'Només és problemàtic si genera un conflicte d’interessos real',
        'És admissible durant els tres primers mesos',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’autorització posterior no sana l’exercici previ sense títol.',
        c: 'El règim és preventiu: no exigeix que el conflicte s’hagi materialitzat.',
        d: 'No hi ha cap període de gràcia.',
      },
      explainCa: 'El règim d’incompatibilitats és preventiu i exigeix un acte administratiu **previ i exprés** de reconeixement. Exercir l’activitat sense aquest reconeixement és un incompliment, amb independència que després s’obtingui l’autorització o que no s’arribi a produir cap conflicte concret.',
      explainEs: 'El régimen de incompatibilidades es preventivo y exige un acto administrativo **previo y expreso** de reconocimiento. Ejercer la actividad sin ese reconocimiento es un incumplimiento, con independencia de que después se obtenga la autorización o de que no llegue a producirse ningún conflicto concreto.',
      refs: [refv('llei-53-1984-incompat', 'art. 3 i 14', '2026-08-24')],
      difficulty: 'dificil',
    },
  ]),

  ...questionsFor(10, [
    {
      n: 1,
      stem: 'Quins impostos són d’exigència obligatòria per als ajuntaments?',
      options: [
        'IBI, IAE i IVTM',
        'IBI, ICIO i plusvàlua',
        'IAE, ICIO i IVTM',
        'IBI, IVTM i plusvàlua',
      ],
      correct: 'a',
      whyWrong: {
        b: 'L’ICIO i la plusvàlua són potestatius.',
        c: 'L’ICIO és potestatiu.',
        d: 'La plusvàlua és potestativa.',
      },
      explainCa: 'Els ajuntaments han d’exigir obligatòriament l’impost sobre béns immobles, l’impost sobre activitats econòmiques i l’impost sobre vehicles de tracció mecànica. L’impost sobre construccions, instal·lacions i obres i l’impost sobre l’increment de valor dels terrenys de naturalesa urbana són potestatius i requereixen ordenança fiscal.',
      explainEs: 'Los ayuntamientos deben exigir obligatoriamente el impuesto sobre bienes inmuebles, el impuesto sobre actividades económicas y el impuesto sobre vehículos de tracción mecánica. El impuesto sobre construcciones, instalaciones y obras y el impuesto sobre el incremento de valor de los terrenos de naturaleza urbana son potestativos y requieren ordenanza fiscal.',
      refs: [refv('rdleg-2-2004-trlrhl', 'art. 59', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 2,
      stem: 'Si el pressupost municipal no està aprovat definitivament l’1 de gener:',
      options: [
        'L’ajuntament no pot fer cap despesa fins que s’aprovi',
        'Es prorroga automàticament el de l’exercici anterior amb els seus crèdits inicials',
        'L’aprova per decret l’alcalde amb caràcter provisional',
        'El fixa la Generalitat de manera subsidiària',
      ],
      correct: 'b',
      whyWrong: {
        a: 'La pròrroga automàtica evita precisament la paràlisi del municipi.',
        c: 'L’alcalde no pot aprovar el pressupost per decret.',
        d: 'La Generalitat no substitueix la corporació en aquesta funció.',
      },
      explainCa: 'Si en iniciar-se l’exercici econòmic no ha entrat en vigor el pressupost corresponent, es considerarà automàticament prorrogat el de l’anterior, amb els seus crèdits inicials, sens perjudici de les modificacions que escaiguin.',
      explainEs: 'Si al iniciarse el ejercicio económico no ha entrado en vigor el presupuesto correspondiente, se considerará automáticamente prorrogado el del anterior, con sus créditos iniciales, sin perjuicio de las modificaciones que procedan.',
      refs: [refv('rdleg-2-2004-trlrhl', 'art. 169.6', '2026-08-24')],
      difficulty: 'mitjana',
    },
    {
      n: 3,
      stem: 'La diferència essencial entre una taxa i un preu públic és que:',
      options: [
        'La taxa la fixa el ple i el preu públic l’alcalde',
        'La taxa retribueix serveis de recepció obligatòria o en règim de monopoli públic; el preu públic, serveis de recepció voluntària que també presta el sector privat',
        'La taxa és sempre més cara que el preu públic',
        'El preu públic només s’aplica a empreses',
      ],
      correct: 'b',
      whyWrong: {
        a: 'L’òrgan competent no és el criteri de distinció.',
        c: 'La quantia no és el criteri de distinció.',
        d: 'Els preus públics també s’apliquen a particulars.',
      },
      explainCa: 'Les taxes retribueixen la utilització privativa o l’aprofitament especial del domini públic i la prestació de serveis o realització d’activitats que no siguin de sol·licitud voluntària o que no els presti el sector privat. Els preus públics retribueixen serveis de sol·licitud voluntària que també presta el sector privat.',
      explainEs: 'Las tasas retribuyen la utilización privativa o el aprovechamiento especial del dominio público y la prestación de servicios o realización de actividades que no sean de solicitud voluntaria o que no los preste el sector privado. Los precios públicos retribuyen servicios de solicitud voluntaria que también presta el sector privado.',
      refs: [refv('rdleg-2-2004-trlrhl', 'art. 20 i 41', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 4,
      stem: 'El pressupost general de l’entitat local s’ha de remetre al ple per a la seva aprovació abans del:',
      options: ['31 d’agost', '15 d’octubre', '30 de novembre', '31 de desembre'],
      correct: 'b',
      whyWrong: {
        a: 'No correspon a cap termini de la tramitació pressupostària.',
        c: 'No correspon a cap termini de la tramitació pressupostària.',
        d: 'El 31 de desembre és la data límit d’aprovació definitiva, no de remissió al ple.',
      },
      explainCa: 'El president de la corporació forma el pressupost general i, informat per la Intervenció, el remet al ple abans del 15 d’octubre per a la seva aprovació, esmena o devolució. L’aprovació definitiva ha de tenir lloc abans del 31 de desembre.',
      explainEs: 'El presidente de la corporación forma el presupuesto general y, informado por la Intervención, lo remite al pleno antes del 15 de octubre para su aprobación, enmienda o devolución. La aprobación definitiva debe tener lugar antes del 31 de diciembre.',
      refs: [refv('rdleg-2-2004-trlrhl', 'art. 168 i 169', '2026-08-24')],
      difficulty: 'dificil',
    },
    {
      n: 5,
      stem: 'Les multes i sancions imposades per l’Ajuntament de Roses en matèria de trànsit són, dins la hisenda local:',
      options: [
        'Un impost municipal',
        'Un recurs de la hisenda local dins la categoria de multes i sancions',
        'Una taxa per prestació de serveis',
        'Un preu públic',
      ],
      correct: 'b',
      whyWrong: {
        a: 'Els impostos són tributs sense contraprestació, no sancions.',
        c: 'La taxa retribueix un servei; la multa castiga una infracció.',
        d: 'El preu públic retribueix un servei voluntari.',
      },
      explainCa: 'La llei enumera com a recursos de les hisendes locals, entre altres, els ingressos de dret privat, els tributs propis, les participacions en tributs de l’Estat i de les comunitats autònomes, les subvencions, els preus públics, les operacions de crèdit i **les multes i sancions** en l’àmbit de les seves competències.',
      explainEs: 'La ley enumera como recursos de las haciendas locales, entre otros, los ingresos de derecho privado, los tributos propios, las participaciones en tributos del Estado y de las comunidades autónomas, las subvenciones, los precios públicos, las operaciones de crédito y **las multas y sanciones** en el ámbito de sus competencias.',
      refs: [refv('rdleg-2-2004-trlrhl', 'art. 2', '2026-08-24')],
      difficulty: 'mitjana',
    },
  ]),
]
