/**
 * Registre d'exàmens oficials i plànols de simulacre de Roses.
 *
 * Els plànols (`ExamBlueprint`) codifiquen les regles reals de la convocatòria
 * i són la font única de veritat per al motor de puntuació.
 *
 * El registre d'exàmens (`OfficialExam`) llista els 30 quadernets publicats pel
 * tribunal, tots amb còpia local verificada pel seu SHA-256.
 * `importStatus: 'imported'` vol dir que les preguntes ja són al banc, amb la
 * resposta que hi va marcar el tribunal; `pending-source` vol dir que el
 * document hi és però encara no s'ha transcrit. Mai s'inventa el contingut
 * d'un examen ni se'n dedueix cap resposta.
 */
import type { ExamBlueprint, ExamComposition, OfficialExam } from '../../schemas/index.ts'
import { CONEIXEMENTS_SCORING, CULTURA_GENERAL_SCORING } from '../../../src/engines/scoring.ts'

export const ROSES_BLUEPRINTS: ExamBlueprint[] = [
  {
    blueprintId: 'roses-cultura-general',
    title: {
      ca: 'Simulacre de cultura general',
      es: 'Simulacro de cultura general',
    },
    track: 'cultura-general',
    questionCount: 20,
    durationMinutes: 20,
    reserveCount: 1,
    scoring: CULTURA_GENERAL_SCORING,
    composition: [
      { label: { ca: 'Cultura general', es: 'Cultura general' }, tag: 'cultura-general', count: 10 },
      { label: { ca: 'Actualitat social, cultural i política', es: 'Actualidad social, cultural y política' }, tag: 'actualitat', count: 10 },
    ],
    contentStatus: 'blocked-missing-content',
    contentNote:
      'El paquet d’actualitat és buit: cap font periodística ni institucional era accessible des de ' +
      'l’entorn de construcció (2026-08-23). Sense 10 preguntes d’actualitat vigents no es pot muntar ' +
      'la prova que descriuen les bases, i muntar-ne 20 de cultura general seria ensenyar un format ' +
      'fals. Per desbloquejar-lo: omplir content/municipalities/roses/current-affairs/ amb preguntes ' +
      'etiquetades `actualitat`, amb dynamic: true i reviewBy, i treure aquest marcador.',
    sourceId: 'roses-bases-2026-interins',
  },
  {
    blueprintId: 'roses-coneixements-professionals',
    title: {
      ca: 'Simulacre de coneixements professionals',
      es: 'Simulacro de conocimientos profesionales',
    },
    track: 'coneixements-professionals',
    questionCount: 40,
    durationMinutes: 60,
    reserveCount: 2,
    scoring: CONEIXEMENTS_SCORING,
    contentStatus: 'ready',
    sourceId: 'roses-bases-2026-interins',
  },
]

/**
 * Simulacre complet: les dues proves seguides, com el dia de l'examen.
 *
 * No és un plànol nou sinó la composició dels dos que ja hi ha. Cada prova
 * conserva el seu temps i les seves regles, i el veredicte final exigeix
 * aprovar-les totes dues, no que la mitjana doni 10.
 */
export const ROSES_COMPOSITIONS: ExamComposition[] = [
  {
    compositionId: 'roses-simulacre-complet',
    title: { ca: 'Simulacre complet', es: 'Simulacro completo' },
    subtitle: {
      ca: 'Cultura general seguida de coneixements professionals',
      es: 'Cultura general seguida de conocimientos profesionales',
    },
    blueprintIds: ['roses-cultura-general', 'roses-coneixements-professionals'],
    sourceId: 'roses-bases-2026-interins',
  },
]

/** Els quatre exàmens de prioritat P0 exigits per la convocatòria vigent. */
/**
 * Registre dels 30 quadernets oficials publicats per l'Ajuntament de Roses
 * (2016–2026), generat a partir del paquet de rescat de fonts i verificat pel
 * SHA-256 de cada document.
 *
 * `importStatus: 'imported'` vol dir que les preguntes són a
 * `questions/official-exams.ts`, transcrites del PDF amb la resposta que hi va
 * marcar el tribunal. `pending-source` vol dir que el document ja és al
 * projecte però encara no s'ha transcrit.
 *
 * Els sis exàmens de 2025 i 2026 (prioritat P0) estan importats. Els 24
 * històrics estan adoptats i pendents de transcripció; la nota de cada un diu
 * quantes preguntes s'hi han detectat i si la marca de resposta és llegible,
 * perquè els que no ho són exigeixen revisió visual abans d'entrar al banc.
 */
const ROSES_EXAM_REGISTRY: OfficialExam[] = [
  {
    examId: 'roses-2026-interins-cp',
    municipality: 'roses',
    year: 2026,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2026-04-15',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-policia-local-interins-2026_c1_prova-coneixements-professionals_15042026',
    sourceId: 'roses-examen-2026-interins-cp',
    priority: 'P0',
    importStatus: 'imported',
    questionIds: [
      'q-of-roses-2026-interins-cp-001',
      'q-of-roses-2026-interins-cp-002',
      'q-of-roses-2026-interins-cp-003',
      'q-of-roses-2026-interins-cp-004',
      'q-of-roses-2026-interins-cp-005',
      'q-of-roses-2026-interins-cp-006',
      'q-of-roses-2026-interins-cp-007',
      'q-of-roses-2026-interins-cp-008',
      'q-of-roses-2026-interins-cp-009',
      'q-of-roses-2026-interins-cp-010',
      'q-of-roses-2026-interins-cp-011',
      'q-of-roses-2026-interins-cp-012',
      'q-of-roses-2026-interins-cp-013',
      'q-of-roses-2026-interins-cp-014',
      'q-of-roses-2026-interins-cp-015',
      'q-of-roses-2026-interins-cp-016',
      'q-of-roses-2026-interins-cp-017',
      'q-of-roses-2026-interins-cp-018',
      'q-of-roses-2026-interins-cp-019',
      'q-of-roses-2026-interins-cp-020',
      'q-of-roses-2026-interins-cp-021',
      'q-of-roses-2026-interins-cp-022',
      'q-of-roses-2026-interins-cp-023',
      'q-of-roses-2026-interins-cp-024',
      'q-of-roses-2026-interins-cp-025',
      'q-of-roses-2026-interins-cp-026',
      'q-of-roses-2026-interins-cp-027',
      'q-of-roses-2026-interins-cp-028',
      'q-of-roses-2026-interins-cp-029',
      'q-of-roses-2026-interins-cp-030',
      'q-of-roses-2026-interins-cp-031',
      'q-of-roses-2026-interins-cp-032',
      'q-of-roses-2026-interins-cp-033',
      'q-of-roses-2026-interins-cp-034',
      'q-of-roses-2026-interins-cp-035',
      'q-of-roses-2026-interins-cp-036',
      'q-of-roses-2026-interins-cp-037',
      'q-of-roses-2026-interins-cp-038',
      'q-of-roses-2026-interins-cp-039',
      'q-of-roses-2026-interins-cp-040',
      'q-of-roses-2026-interins-cp-041',
      'q-of-roses-2026-interins-cp-042',
    ],
    expectedQuestionCount: 42,
    note:
      'Transcrit del quadernet oficial. Les respostes són les que porta marcades el document (marca: asterisc); no se n’ha deduït cap. Les de cultura general s’importen com a material històric i queden fora dels simulacres.',
  },
  {
    examId: 'roses-2026-interins-cg',
    municipality: 'roses',
    year: 2026,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2026-04-15',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-policia-local-interina-2026_c1_prova-cultura-general_15042026',
    sourceId: 'roses-examen-2026-interins-cg',
    priority: 'P0',
    importStatus: 'imported',
    questionIds: [
      'q-of-roses-2026-interins-cg-001',
      'q-of-roses-2026-interins-cg-002',
      'q-of-roses-2026-interins-cg-003',
      'q-of-roses-2026-interins-cg-004',
      'q-of-roses-2026-interins-cg-005',
      'q-of-roses-2026-interins-cg-006',
      'q-of-roses-2026-interins-cg-007',
      'q-of-roses-2026-interins-cg-008',
      'q-of-roses-2026-interins-cg-009',
      'q-of-roses-2026-interins-cg-010',
      'q-of-roses-2026-interins-cg-011',
      'q-of-roses-2026-interins-cg-012',
      'q-of-roses-2026-interins-cg-013',
      'q-of-roses-2026-interins-cg-014',
      'q-of-roses-2026-interins-cg-015',
      'q-of-roses-2026-interins-cg-016',
      'q-of-roses-2026-interins-cg-017',
      'q-of-roses-2026-interins-cg-018',
      'q-of-roses-2026-interins-cg-019',
      'q-of-roses-2026-interins-cg-020',
      'q-of-roses-2026-interins-cg-021',
    ],
    expectedQuestionCount: 21,
    note:
      'Transcrit del quadernet oficial. Les respostes són les que porta marcades el document (marca: asterisc); no se n’ha deduït cap. Les de cultura general s’importen com a material històric i queden fora dels simulacres.',
  },
  {
    examId: 'roses-2025-interins-cp',
    municipality: 'roses',
    year: 2025,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2025-04-16',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2025_c1_prova-coneixements-professionals_16042025',
    sourceId: 'roses-examen-2025-interins-cp',
    priority: 'P0',
    importStatus: 'imported',
    questionIds: [
      'q-of-roses-2025-interins-cp-001',
      'q-of-roses-2025-interins-cp-002',
      'q-of-roses-2025-interins-cp-003',
      'q-of-roses-2025-interins-cp-004',
      'q-of-roses-2025-interins-cp-005',
      'q-of-roses-2025-interins-cp-006',
      'q-of-roses-2025-interins-cp-007',
      'q-of-roses-2025-interins-cp-008',
      'q-of-roses-2025-interins-cp-009',
      'q-of-roses-2025-interins-cp-010',
      'q-of-roses-2025-interins-cp-011',
      'q-of-roses-2025-interins-cp-012',
      'q-of-roses-2025-interins-cp-013',
      'q-of-roses-2025-interins-cp-014',
      'q-of-roses-2025-interins-cp-015',
      'q-of-roses-2025-interins-cp-016',
      'q-of-roses-2025-interins-cp-017',
      'q-of-roses-2025-interins-cp-018',
      'q-of-roses-2025-interins-cp-019',
      'q-of-roses-2025-interins-cp-020',
      'q-of-roses-2025-interins-cp-021',
      'q-of-roses-2025-interins-cp-022',
      'q-of-roses-2025-interins-cp-023',
      'q-of-roses-2025-interins-cp-024',
      'q-of-roses-2025-interins-cp-025',
      'q-of-roses-2025-interins-cp-026',
      'q-of-roses-2025-interins-cp-027',
      'q-of-roses-2025-interins-cp-028',
      'q-of-roses-2025-interins-cp-029',
      'q-of-roses-2025-interins-cp-030',
      'q-of-roses-2025-interins-cp-031',
      'q-of-roses-2025-interins-cp-032',
      'q-of-roses-2025-interins-cp-033',
      'q-of-roses-2025-interins-cp-034',
      'q-of-roses-2025-interins-cp-035',
      'q-of-roses-2025-interins-cp-036',
      'q-of-roses-2025-interins-cp-037',
      'q-of-roses-2025-interins-cp-038',
      'q-of-roses-2025-interins-cp-039',
      'q-of-roses-2025-interins-cp-040',
      'q-of-roses-2025-interins-cp-041',
      'q-of-roses-2025-interins-cp-042',
    ],
    expectedQuestionCount: 42,
    note:
      'Transcrit del quadernet oficial. Les respostes són les que porta marcades el document (marca: asterisc); no se n’ha deduït cap. Les de cultura general s’importen com a material històric i queden fora dels simulacres.',
  },
  {
    examId: 'roses-2025-interins-cg',
    municipality: 'roses',
    year: 2025,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2025-04-16',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2025_c1_prova-cultura-general_16042025',
    sourceId: 'roses-examen-2025-interins-cg',
    priority: 'P0',
    importStatus: 'imported',
    questionIds: [
      'q-of-roses-2025-interins-cg-001',
      'q-of-roses-2025-interins-cg-002',
      'q-of-roses-2025-interins-cg-003',
      'q-of-roses-2025-interins-cg-004',
      'q-of-roses-2025-interins-cg-005',
      'q-of-roses-2025-interins-cg-006',
      'q-of-roses-2025-interins-cg-007',
      'q-of-roses-2025-interins-cg-008',
      'q-of-roses-2025-interins-cg-009',
      'q-of-roses-2025-interins-cg-010',
      'q-of-roses-2025-interins-cg-011',
      'q-of-roses-2025-interins-cg-012',
      'q-of-roses-2025-interins-cg-013',
      'q-of-roses-2025-interins-cg-014',
      'q-of-roses-2025-interins-cg-015',
      'q-of-roses-2025-interins-cg-016',
      'q-of-roses-2025-interins-cg-017',
      'q-of-roses-2025-interins-cg-018',
      'q-of-roses-2025-interins-cg-019',
      'q-of-roses-2025-interins-cg-020',
      'q-of-roses-2025-interins-cg-021',
    ],
    expectedQuestionCount: 21,
    note:
      'Transcrit del quadernet oficial. Les respostes són les que porta marcades el document (marca: asterisc); no se n’ha deduït cap. Les de cultura general s’importen com a material històric i queden fora dels simulacres.',
  },
  {
    examId: 'roses-2025-propietat-cp',
    municipality: 'roses',
    year: 2025,
    placeType: 'propietat',
    testType: 'coneixements-professionals',
    heldOn: '2025-12-03',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-policia-local-en-propietat-2025_c1_prova-coneixements-professionals_03122025',
    sourceId: 'roses-examen-2025-propietat-cp',
    priority: 'P0',
    importStatus: 'imported',
    questionIds: [
      'q-of-roses-2025-propietat-cp-001',
      'q-of-roses-2025-propietat-cp-002',
      'q-of-roses-2025-propietat-cp-003',
      'q-of-roses-2025-propietat-cp-004',
      'q-of-roses-2025-propietat-cp-005',
      'q-of-roses-2025-propietat-cp-006',
      'q-of-roses-2025-propietat-cp-007',
      'q-of-roses-2025-propietat-cp-008',
      'q-of-roses-2025-propietat-cp-009',
      'q-of-roses-2025-propietat-cp-010',
      'q-of-roses-2025-propietat-cp-011',
      'q-of-roses-2025-propietat-cp-012',
      'q-of-roses-2025-propietat-cp-013',
      'q-of-roses-2025-propietat-cp-014',
      'q-of-roses-2025-propietat-cp-015',
      'q-of-roses-2025-propietat-cp-016',
      'q-of-roses-2025-propietat-cp-017',
      'q-of-roses-2025-propietat-cp-018',
      'q-of-roses-2025-propietat-cp-019',
      'q-of-roses-2025-propietat-cp-020',
      'q-of-roses-2025-propietat-cp-021',
      'q-of-roses-2025-propietat-cp-022',
      'q-of-roses-2025-propietat-cp-023',
      'q-of-roses-2025-propietat-cp-024',
      'q-of-roses-2025-propietat-cp-025',
      'q-of-roses-2025-propietat-cp-026',
      'q-of-roses-2025-propietat-cp-027',
      'q-of-roses-2025-propietat-cp-028',
      'q-of-roses-2025-propietat-cp-029',
      'q-of-roses-2025-propietat-cp-030',
      'q-of-roses-2025-propietat-cp-031',
      'q-of-roses-2025-propietat-cp-032',
      'q-of-roses-2025-propietat-cp-033',
      'q-of-roses-2025-propietat-cp-034',
      'q-of-roses-2025-propietat-cp-035',
      'q-of-roses-2025-propietat-cp-036',
      'q-of-roses-2025-propietat-cp-037',
      'q-of-roses-2025-propietat-cp-038',
      'q-of-roses-2025-propietat-cp-039',
      'q-of-roses-2025-propietat-cp-040',
      'q-of-roses-2025-propietat-cp-041',
      'q-of-roses-2025-propietat-cp-042',
    ],
    expectedQuestionCount: 42,
    note:
      'Transcrit del quadernet oficial. Les respostes són les que porta marcades el document (marca: asterisc); no se n’ha deduït cap. Les de cultura general s’importen com a material històric i queden fora dels simulacres.',
  },
  {
    examId: 'roses-2025-propietat-cg',
    municipality: 'roses',
    year: 2025,
    placeType: 'propietat',
    testType: 'cultura-general',
    heldOn: '2025-12-03',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-policia-local-en-propietat-2025_c1_prova-cultura-general_03122025-1',
    sourceId: 'roses-examen-2025-propietat-cg',
    priority: 'P0',
    importStatus: 'imported',
    questionIds: [
      'q-of-roses-2025-propietat-cg-001',
      'q-of-roses-2025-propietat-cg-002',
      'q-of-roses-2025-propietat-cg-003',
      'q-of-roses-2025-propietat-cg-004',
      'q-of-roses-2025-propietat-cg-005',
      'q-of-roses-2025-propietat-cg-006',
      'q-of-roses-2025-propietat-cg-007',
      'q-of-roses-2025-propietat-cg-008',
      'q-of-roses-2025-propietat-cg-009',
      'q-of-roses-2025-propietat-cg-010',
      'q-of-roses-2025-propietat-cg-011',
      'q-of-roses-2025-propietat-cg-012',
      'q-of-roses-2025-propietat-cg-013',
      'q-of-roses-2025-propietat-cg-014',
      'q-of-roses-2025-propietat-cg-015',
      'q-of-roses-2025-propietat-cg-016',
      'q-of-roses-2025-propietat-cg-017',
      'q-of-roses-2025-propietat-cg-018',
      'q-of-roses-2025-propietat-cg-019',
      'q-of-roses-2025-propietat-cg-020',
      'q-of-roses-2025-propietat-cg-021',
    ],
    expectedQuestionCount: 21,
    note:
      'Transcrit del quadernet oficial. Les respostes són les que porta marcades el document (marca: asterisc); no se n’ha deduït cap. Les de cultura general s’importen com a material històric i queden fora dels simulacres.',
  },
  {
    examId: 'roses-2024-interins-cp',
    municipality: 'roses',
    year: 2024,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2024-04-03',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2024_c1_prova-coneixements-professionals_03042024',
    sourceId: 'roses-examen-2024-interins-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 40+2 preguntes amb marca de resposta llegible (ressaltat).',
  },
  {
    examId: 'roses-2024-interins-cg',
    municipality: 'roses',
    year: 2024,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2024-04-03',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2024_c1_prova-cultura-general_03042024',
    sourceId: 'roses-examen-2024-interins-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+1 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2024-propietat-cp',
    municipality: 'roses',
    year: 2024,
    placeType: 'propietat',
    testType: 'coneixements-professionals',
    heldOn: '2024-06-19',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-en-propietat-2024_c1_prova-coneixements-professionals_19062024',
    sourceId: 'roses-examen-2024-propietat-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 40+2 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2024-propietat-cg',
    municipality: 'roses',
    year: 2024,
    placeType: 'propietat',
    testType: 'cultura-general',
    heldOn: '2024-06-19',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-en-propietat-2024_c1_prova-cultura-general_19062024',
    sourceId: 'roses-examen-2024-propietat-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+1 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2023-interins-cp',
    municipality: 'roses',
    year: 2023,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2023-03-27',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2023_c2_-prova-coneixements-professionals_27032023',
    sourceId: 'roses-examen-2023-interins-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+1 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2023-interins-cg',
    municipality: 'roses',
    year: 2023,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2023-03-27',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2023_c2_prova-cultura-general_27032023',
    sourceId: 'roses-examen-2023-interins-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+1 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2022-interins-cp',
    municipality: 'roses',
    year: 2022,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2022-04-19',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2022_c2_prova-coneixements-professionals_19042022',
    sourceId: 'roses-examen-2022-interins-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+1 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2022-interins-cg',
    municipality: 'roses',
    year: 2022,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2022-04-19',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2022_c2_prova-cultura-general_19042022',
    sourceId: 'roses-examen-2022-interins-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+1 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2021-interins-cp',
    municipality: 'roses',
    year: 2021,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2021-04-27',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2021_c2_prova-coneixements-professionals_27042021',
    sourceId: 'roses-examen-2021-interins-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 15+2 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2021-interins-cg',
    municipality: 'roses',
    year: 2021,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2021-04-27',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2021_c2_prova-cultura-general_-27042021',
    sourceId: 'roses-examen-2021-interins-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 15+2 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2021-propietat-cp',
    municipality: 'roses',
    year: 2021,
    placeType: 'propietat',
    testType: 'coneixements-professionals',
    heldOn: '2021-04-13',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-en-propietat-2021_c2_prova-coneixements-professionals_13042021',
    sourceId: 'roses-examen-2021-propietat-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 25+2 preguntes, 26 de les quals sense marca de resposta inequívoca al text. Aquestes exigeixen revisió visual pregunta per pregunta abans d’importar-les.',
  },
  {
    examId: 'roses-2021-propietat-cg',
    municipality: 'roses',
    year: 2021,
    placeType: 'propietat',
    testType: 'cultura-general',
    heldOn: '2021-04-13',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-en-propietat-2021_c2_prova-cultura-general_13042021',
    sourceId: 'roses-examen-2021-propietat-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 25+2 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2019-interins-cp',
    municipality: 'roses',
    year: 2019,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2019-05-20',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins_prova-teorica-20052019',
    sourceId: 'roses-examen-2019-interins-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+2 preguntes amb marca de resposta llegible (color).',
  },
  {
    examId: 'roses-2019-interins-cg',
    municipality: 'roses',
    year: 2019,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2019-05-20',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins_prova-de-cultura-general-20052019',
    sourceId: 'roses-examen-2019-interins-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+2 preguntes amb marca de resposta llegible (color).',
  },
  {
    examId: 'roses-2019-propietat-cp',
    municipality: 'roses',
    year: 2019,
    placeType: 'propietat',
    testType: 'coneixements-professionals',
    heldOn: '2019-06-25',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-en-propietat-2019_c2_prova-coneixements-professionals_25062019',
    sourceId: 'roses-examen-2019-propietat-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 40+2 preguntes, 1 de les quals sense marca de resposta inequívoca al text. Aquestes exigeixen revisió visual pregunta per pregunta abans d’importar-les.',
  },
  {
    examId: 'roses-2019-propietat-cg',
    municipality: 'roses',
    year: 2019,
    placeType: 'propietat',
    testType: 'cultura-general',
    heldOn: '2019-06-25',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-en-propietat_prova-teorica-de-cultura-general-25062019',
    sourceId: 'roses-examen-2019-propietat-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 40+2 preguntes amb marca de resposta llegible (color).',
  },
  {
    examId: 'roses-2018-interins-cp',
    municipality: 'roses',
    year: 2018,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2018-05-09',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2018_c2_prova-coneixements-professionals_09052018',
    sourceId: 'roses-examen-2018-interins-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+0 preguntes, 1 de les quals sense marca de resposta inequívoca al text. Aquestes exigeixen revisió visual pregunta per pregunta abans d’importar-les.',
  },
  {
    examId: 'roses-2018-interins-cg',
    municipality: 'roses',
    year: 2018,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2018-05-09',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2018_c2_prova-cultura-general_09052018',
    sourceId: 'roses-examen-2018-interins-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+2 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2018-propietat-cp',
    municipality: 'roses',
    year: 2018,
    placeType: 'propietat',
    testType: 'coneixements-professionals',
    heldOn: '2018-07-31',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-en-propietat-2018_c2_prova-coneixements-professionals_31072018',
    sourceId: 'roses-examen-2018-propietat-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 40+2 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2018-propietat-cg',
    municipality: 'roses',
    year: 2018,
    placeType: 'propietat',
    testType: 'cultura-general',
    heldOn: '2018-07-31',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-en-propietat-2018_c2_prova-cultura-general_31072018',
    sourceId: 'roses-examen-2018-propietat-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 40+2 preguntes, 1 de les quals sense marca de resposta inequívoca al text. Aquestes exigeixen revisió visual pregunta per pregunta abans d’importar-les.',
  },
  {
    examId: 'roses-2017-interins-cp',
    municipality: 'roses',
    year: 2017,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2017-05-22',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2017_c2_prova-coneixements-professionals_22052017',
    sourceId: 'roses-examen-2017-interins-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+0 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2017-interins-cg',
    municipality: 'roses',
    year: 2017,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2017-05-22',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2017_c2_prova-cultura-general_22052017',
    sourceId: 'roses-examen-2017-interins-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+2 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2016-interins-cp',
    municipality: 'roses',
    year: 2016,
    placeType: 'interina',
    testType: 'coneixements-professionals',
    heldOn: '2016-04-15',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2016_c2_prova-coneixements-professionals_15042016',
    sourceId: 'roses-examen-2016-interins-cp',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 42,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 9+0 preguntes amb marca de resposta llegible (asterisc).',
  },
  {
    examId: 'roses-2016-interins-cg',
    municipality: 'roses',
    year: 2016,
    placeType: 'interina',
    testType: 'cultura-general',
    heldOn: '2016-04-15',
    url: 'https://www.roses.cat/fitxers/RRHH/proves-opos/agents-interins-2016_c2_prova-cultura-general_15042016',
    sourceId: 'roses-examen-2016-interins-cg',
    priority: 'P1',
    importStatus: 'pending-source',
    questionIds: [],
    expectedQuestionCount: 21,
    note:
      'Quadernet oficial adoptat i verificat pel seu SHA-256. Pendent de transcriure: prioritat P1. L’extracció detecta 20+2 preguntes amb marca de resposta llegible (asterisc).',
  },
]

export const ROSES_EXAMS: OfficialExam[] = ROSES_EXAM_REGISTRY
